<div class="aboutus">
    <div class="hero banner shape-parent mb-60 overflow-initial"
         style="background-image:url('<?php echo $this->getViewFileUrl('images/aboutus/hero.png'); ?>');">
        <div class="dark-overlay" style=""></div>
        <div class="container" style="">
            <div class="row col-12">
                <div class="col-12 col-lg-7">
                    <h1 class="text-white">We are Europe Online Services</h1>
                    <h3 class="text-white" style="font-weight:200">Your favourite online shipping service</h3>
                    <p class="text-white" >We enable you, to transport your favourite European products to your address in Asia. Europe Online Services connects the physical and digital world of parcel transportation between senders and receivers.</p>

                </div>

            </div>
        </div>
    </div>
    <div class="container ">
        <div class="row col-12">
            <h2 class="text-center">For Consumers</h2>
            <p>Europe Online Services enables Asian customers and consumers to transport parcels from Europe to Asia. With the use of our fully automatic platform and services, shopping in Europe has never been easier. Our platform is designed for simplicity, performance, and service of our customers. The system enables customers to safely deliver parcels to their homes in Asia. The whole system functions automatically and takes over the difficult transportation and documentation processes.</p>
            <p>At Europe Online Services, we are dedicated to making customers happy. Together with our partner SF Express, we keep parcel transportation simple, safe and cost-efficient.</p>
            <p><a href="<?php echo $this->getUrl('customer/account/create'); ?>" class="btn btn-primary">Explore the possibilities</a></p>
        </div>

    </div>

    <div class="mb-60 py-lg-40 block-mission" style="background-image:url('<?php echo $this->getViewFileUrl('images/aboutus/transportation.png'); ?>');">
        <div style="position:absolute;top:0;left:0; width:100%;height:100%;background: rgba(0,0,0,0.7);"></div>
        <div class="container py-100">
            <div class="row col-12 text-center">
               <h2 style="color:white;max-width:800px; margin:0 auto;">“Our mission is to become the world’s leading provider of transportation services!”</h2>

            </div>
        </div>
    </div>

    <div class="container pb-100 pt-lg-100 block-for-business" id="for-business">
        <div class="row col-12">
            <div class="col-12 col-lg-6 d-none d-lg-block text-center">
                <img src="<?php echo $this->getViewFileUrl('images/aboutus/for-business.png'); ?>" alt="" />
            </div>
            <div class="col-12 col-lg-6">
                <h3>For companies and businesses</h3>
                <p>For companies and businesses, we provide full cross-border logistic services for parcels and cargo from Europe to Asia. Europe Online Services connects the European market to every Asian consumer. Europe Online Services and partners provide customers with leading technology for smart logistics services.</p>
                <div class="row col-12">
                    <div class="col-6 pr-6">
                        <div style="width:100%; border:1px solid #ccc; border-radius:8px;padding:10px 20px;">
                            <img src="<?php echo $this->getViewFileUrl('images/icon-phone.svg'); ?>" alt="" style="margin-top:-2px;"/>
                            <strong style="margin-left:10%;font-size:14px;">Call us</strong>
                            <span style="margin-left:10%;font-size:14px;">0031 6 12345678</span>
                        </div>
                    </div>
                    <div class="col-6 pl-6">
                        <div style="width:100%; border:1px solid #ccc; border-radius:8px;padding:12px 10px 12px 20px;">
                            <img src="<?php echo $this->getViewFileUrl('images/icon-mail.svg'); ?>" alt="" style="margin-top:-2px;"/>
                            <strong style="margin-left:5%;font-size:12px;">Mail us</strong>
                            <span style="margin-left:5%;font-size:12px;">info@europeonlineservices.com</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        <div class="mb-60 py-lg-40 block-quote-parcel"
             style="background-image:url('<?php echo $this->getViewFileUrl('images/aboutus/parcel.png'); ?>');">
            <div class="dark-overlay"></div>
            <div class="container py-100">
                <div class="row col-12 text-center">
                    <h2 style="color:white;max-width:800px; margin:0 auto;">““We keep parcel transportation simple, safe, fast and affordable”!”</h2>

                </div>
            </div>
        </div>
</div>

<div  class="py-60">
    <div class="container step">
        <div class="row col-12 text-center">
            <h3 style="margin:auto; margin-bottom:40px;">Join us and we will expand your business in Europe and Asia</h3>
            <p class="text-center" style="width: 100%;">
                <a href="<?php echo $this->getUrl('customer/account/create'); ?>" class="btn btn-primary text-center" style="width: 250px;">Sign up for free</a>
            </p>
        </div>
    </div>

</div>

