<?php
?>

<?= $block->getChildHtml('info') ?>

    <div class="row col-flex mb-40 order-steps">
        <div class="col step step-active">
            <p>Create order</p>
        </div>
        <div class="col step step-active">
            <p>Consolidate</p>
        </div>
        <div class="col step step-active">
            <p>Upload ID</p>
        </div>
        <div class="col step">
            <p>Shipping</p>
        </div>
        <div class="col step">
            <p>Review & Payment</p>
        </div>
    </div>
    <div class="block">
        <div class="block-title"><strong>Upload Successfull!</strong></div>
        <p></p>
        <p>When the parcels are arrived to our warehouse, we will notice you by E-mail. </p>

    </div>
