<?php
/** @var \Magento\Framework\View\Element\Template $block */

$shipmentViewModel = $block->getData('shipment_view_model');
$orderViewModel = $block->getData('order_view_model');

$shipments = $shipmentViewModel->getShipments()->filterByCustomer()->filterByStatus(['During payment', 'Ready for payment'])->getSize();
$orders = $orderViewModel->getOrders()->filterByCustomer()->filterByStatus(['open:pricing'])->getSize();
if ($shipments > 0 || $orders > 0) {
    ?>
    <span class="countShipments" style="
    background: #dd0000;
    border-radius: 36px;
    height: 10px;
    width: 10px;
    padding-left: 9px;
    font-size: 11px;
    color: white;
    position: absolute;
    left: 28px;
    top: 8px;
    display: none;
"></span>


    <?php
}
?>



<script>
    require(["jquery", "Eos_Base/js/bootstrap.bundle.min",], function ($, bootstrap) {

        $('.countShipments').detach().appendTo("#block-collapsible-nav .item:nth-child(2)");

        $('.countShipments').parent().css('position', 'relative');
        $('.countShipments').show();
    });


</script>