<?php
$ObjectManager= \Magento\Framework\App\ObjectManager::getInstance();
$context = $ObjectManager->get('Magento\Framework\App\Http\Context');
$isLoggedIn = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
if ($isLoggedIn) {

?>
<div class="navbar navbar-top navbar-expand-lg navbar-eos">

    <div class="container">
        <a class="navbar-brand" href="/">
            <img width="45" src='<?php echo $this->getViewFileUrl('images/eos_logo_without_text.svg'); ?>' alt="" style="margin-top:-4px;" />
            <h3 style="display: inline;
    font-size: 16px;
    margin-left: 15px;
    color: #404040;">Europe Online Services</h3>
        </a>
        <a class="navbar-toggle" href="#navbar-mobile-style-2" data-fancybox="" data-base-class="fancybox-navbar" data-keyboard="false" data-auto-focus="false" data-touch="false" data-close-existing="true" data-small-btn="false" data-toolbar="false">
            <span></span>
            <span></span>
            <span></span>
        </a>
        <ul class="nav navbar-nav pt-8">
            <li class="nav-item">
                <a href="<?php echo $this->getUrl('/'); ?>" class="nav-link">
                    <span class="nav-link-name">Home</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="<?php echo $this->getUrl('frontportal/howitworks'); ?>" class="nav-link">
                    <span class="nav-link-name">How it works</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="<?php echo $this->getUrl('frontportal/pricing'); ?>" class="nav-link">
                    <span class="nav-link-name">Pricing</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="<?php echo $this->getUrl('customer/account'); ?>" class="nav-link">
                    <span class="nav-link-name">My account</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="<?php echo $this->getUrl('customer/account/logout'); ?>" class="nav-link">
                    <span class="nav-link-name"><?php echo __('Log out')?></span>
                </a>
            </li>
            <li class="nav-item ml-40">
                <a href="#" class="nav-link">
                    <img width="70" src='<?php echo $this->getViewFileUrl('images/sf-partnership.png'); ?>' alt="">
                </a>
            </li>
        </ul>
    </div>

</div>
    <div class="navbar navbar-mobile navbar-mobile-style-2" id="navbar-mobile-style-2">
        <div class="shape justify-content-end">
            <svg data-rellax-speed="0" width="544" height="362" viewBox="0 0 544 362" fill="none" xmlns="http://www.w3.org/2000/svg" style="transform: translate3d(0px, 0px, 0px);">
                <circle cx="320.5" cy="41.5" r="320.5" fill="#ececec"></circle>
            </svg>
        </div>
        <div class="navbar-head">
            <div class="container">
                <a class="navbar-brand" href="home.html">
                    <img width="70" src='<?php echo $this->getViewFileUrl('images/eos_logo_without_text.svg'); ?>' alt="">
                </a>
                <a class="navbar-toggle" href="#" data-fancybox-close="">
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </div>
        </div>
        <div class="container">
            <div class="row gh-1 justify-content-center">
                <div class="col-12 col-md-7 col-lg-5 col-xl-4">
                    <div class="navbar-body">
                        <ul class="nav navbar-nav navbar-nav-collapse">
                            <li class="nav-item">
                                <a href="<?php echo $this->getUrl('/'); ?>" class="nav-link">
                                    <span class="nav-link-name">Home</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="<?php echo $this->getUrl('frontportal/howitworks'); ?>" class="nav-link">
                                    <span class="nav-link-name">How it works</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="<?php echo $this->getUrl('frontportal/pricing'); ?>" class="nav-link">
                                    <span class="nav-link-name">Pricing</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="<?php echo $this->getUrl('customer/account'); ?>" class="nav-link">
                                    <span class="nav-link-name">My Account</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="<?php echo $this->getUrl('customer/account/logout'); ?>" class="nav-link">
                                    <span class="nav-link-name">Log out</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-1 d-none d-md-block"></div>
                <div class="col-12 col-md-4 col-lg-4 col-xl-3">
                    <div class="navbar-footer">
                        <div class="mb-60">
                            <h4 class="mb-17 font-weight-medium font-size-18">Contact info:</h4>
                            <ul class="list-group borderless font-size-14">
                                <li class="list-group-item">Email: <a href="mailto:info@europeonlineservices.com">info@europeonlineservices.com</a></li>
                                <li class="list-group-item">Phone: +31 6 11 39 29 56</a></li>
                            </ul>
                        </div>
                        <div class="mb-60">
                            <p class="lead mb-17 font-weight-medium">Warehouse NL Address:</p>
                            <ul class="list-group borderless font-size-17">
                                <li class="list-group-item">Delftweg 71</li>
                                <li class="list-group-item">2289 BA Rijswijk</li>
                                <li class="list-group-item">The Netherlands</li>
                            </ul>
                        </div>
                        <div class="mb-60">
                            <p class="lead mb-17 font-weight-medium">Warehouse DE Address:</p>
                            <ul class="list-group borderless font-size-17">
                                <li class="list-group-item">Andreas-Meyer-Str 45-47</li>
                                <li class="list-group-item">22113 Hamburg</li>
                                <li class="list-group-item">Germany</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
            <?php

        } else {

            ?>
    <div class="navbar navbar-top navbar-expand-lg navbar-eos">

        <div class="container">
            <a class="navbar-brand" href="/">
                <img width="45" src='<?php echo $this->getViewFileUrl('images/eos_logo_without_text.svg'); ?>' alt="" style="margin-top:-4px;">
                <h3 style="display: inline;
    font-size: 16px;
    margin-left: 15px;
    color: #404040;">Europe Online Services</h3>
            </a>
            <a class="navbar-toggle" href="#navbar-mobile-style-2" data-fancybox="" data-base-class="fancybox-navbar" data-keyboard="false" data-auto-focus="false" data-touch="false" data-close-existing="true" data-small-btn="false" data-toolbar="false">
                <span></span>
                <span></span>
                <span></span>
            </a>
            <ul class="nav navbar-nav pt-8">
                <li class="nav-item">
                    <a href="<?php echo $this->getUrl('/'); ?>" class="nav-link">
                        <span class="nav-link-name">Home</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="<?php echo $this->getUrl('frontportal/howitworks'); ?>" class="nav-link">
                        <span class="nav-link-name">How it works</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="<?php echo $this->getUrl('frontportal/pricing'); ?>" class="nav-link">
                        <span class="nav-link-name">Pricing</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="<?php echo $this->getUrl('customer/account/login') ?>" class="nav-link">
                        <span class="nav-link-name">Login <!--<img src="<?php /*echo $this->getViewFileUrl('images/icon-account.png'); */?>"/>--></span>
                    </a>
                </li>
                <!--<li class="nav-item navbar-dropdown">
                    <a href="#" class="nav-link">
                        <span class="nav-link-name">Language</span>
                        <svg width="6" height="10" viewBox="0 0 6 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M1 9L5 5L1 1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                        </svg>
                    </a>
                    <div class="dropdown-menu">
                        <ul class="nav navbar-nav pt-8">
                            <li class="nav-item">
                                <a href="portfolio-col-1-style-1.html" class="nav-link">
                                    <span class="nav-link-name">English</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="portfolio-col-1-style-2.html" class="nav-link">
                                    <span class="nav-link-name">Chinese</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>-->

                <li class="nav-item ml-40">
                    <a href="#" class="nav-link">
                        <img width="70" src='<?php echo $this->getViewFileUrl('images/sf-partnership.png'); ?>' alt="">
                    </a>
                </li>
            </ul>
    </div>
    </div>


    <div class="navbar navbar-mobile navbar-mobile-style-2" id="navbar-mobile-style-2">
        <div class="shape justify-content-end">
            <svg data-rellax-speed="0" width="544" height="362" viewBox="0 0 544 362" fill="none" xmlns="http://www.w3.org/2000/svg" style="transform: translate3d(0px, 0px, 0px);">
                <circle cx="320.5" cy="41.5" r="320.5" fill="#ececec"></circle>
            </svg>
        </div>
        <div class="navbar-head">
            <div class="container">
                <a class="navbar-brand" href="home.html">
                    <img width="70" src='<?php echo $this->getViewFileUrl('images/eos_logo_without_text.svg'); ?>' alt="">
                </a>
                <a class="navbar-toggle" href="#" data-fancybox-close="">
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </div>
        </div>
        <div class="container">
            <div class="row gh-1 justify-content-center">
                <div class="col-12 col-md-7 col-lg-5 col-xl-4">
                    <div class="navbar-body">
                        <ul class="nav navbar-nav navbar-nav-collapse">
                            <li class="nav-item">
                                <a href="<?php echo $this->getUrl('/'); ?>" class="nav-link">
                                    <span class="nav-link-name">Home</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="<?php echo $this->getUrl('frontportal/howitworks'); ?>" class="nav-link">
                                    <span class="nav-link-name">How it works</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="<?php echo $this->getUrl('frontportal/pricing'); ?>" class="nav-link">
                                    <span class="nav-link-name">Pricing</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="<?php echo $this->getUrl('customer/account/login'); ?>" class="nav-link">
                                    <span class="nav-link-name">Login</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-1 d-none d-md-block"></div>
                <div class="col-12 col-md-4 col-lg-4 col-xl-3">
                    <div class="navbar-footer">
                        <div class="mb-60">
                            <h4 class="mb-17 font-weight-medium font-size-18">Contact info:</h4>
                            <ul class="list-group borderless font-size-14">
                                <li class="list-group-item">Email: <a href="mailto:info@europeonlineservices.com">info@europeonlineservices.com</a></li>
                                <li class="list-group-item">Phone: +31 6 11 39 29 56</a></li>
                            </ul>
                        </div>
                        <div class="mb-60">
                            <p class="lead mb-17 font-weight-medium">Warehouse NL Address:</p>
                            <ul class="list-group borderless font-size-17">
                                <li class="list-group-item">Delftweg 71</li>
                                <li class="list-group-item">2289 BA Rijswijk</li>
                                <li class="list-group-item">The Netherlands</li>
                            </ul>
                        </div>
                        <div class="mb-60">
                            <p class="lead mb-17 font-weight-medium">Warehouse DE Address:</p>
                            <ul class="list-group borderless font-size-17">
                                <li class="list-group-item">Andreas-Meyer-Str 45-47</li>
                                <li class="list-group-item">22113 Hamburg</li>
                                <li class="list-group-item">Germany</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

            <?php

        }

        ?>


<script>
    require ([
            'jquery',
            'Eos_Base/js/bundle'
        ],
        function ($) {
            "use strict";
            $(window).on("load", function () {
                require([
                    'Eos_Base/js/themebau',
                    'Eos_Base/js/general'

                ]);


            });
            $('.block-collapsible-nav-content .item').each(function() {

                if($(this).find('.delimiter').length === 0) {
                    $(this).prepend('<div class="svg-holder"></div>');
                }
            });
        });
</script>
<style>
    .block-collapsible-nav-content .svg-holder {
        content: '';
        -webkit-mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/my-account.svg"); ?>) no-repeat;
        mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/my-account.svg"); ?>) no-repeat;
        -webkit-mask-size: 23px 23px;
        mask-size: 20px 20px;
        -webkit-mask-position: 50% 10%;
        mask-position: 50% 10%;
    }

    .block-collapsible-nav-content .item:nth-child(2) .svg-holder {
        -webkit-mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/to-do.svg"); ?>) no-repeat;
        mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/to-do.svg"); ?>) no-repeat;
        -webkit-mask-size: 20px 24px;
        mask-size: 20px 24px;
        -webkit-mask-position: 50% 40%;
        mask-position: 50% 40%;
    }
    .block-collapsible-nav-content .item:nth-child(4) .svg-holder {
        -webkit-mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/upload-parcel-info.svg"); ?>) no-repeat;
        mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/upload-parcel-info.svg"); ?>) no-repeat;
        -webkit-mask-size: 22px 22px;
        mask-size: 22px 22px;
        -webkit-mask-position: 50% 25%;
        mask-position: 50% 25%;
    }
    .block-collapsible-nav-content .item:nth-child(5) .svg-holder {
        -webkit-mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/create-shipment.svg"); ?>) no-repeat;
        mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/create-shipment.svg"); ?>) no-repeat;
        -webkit-mask-size: 25px 25px;
        mask-size: 25px 25px;
        -webkit-mask-position: 50% 30%;
        mask-position: 50% 30%;
    }
    .block-collapsible-nav-content .item:nth-child(6) .svg-holder {
        -webkit-mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/upload-id-card.svg"); ?>) no-repeat;
        mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/upload-id-card.svg"); ?>) no-repeat;
        -webkit-mask-size: 22px 22px;
        mask-size: 22px 22px;
        -webkit-mask-position: 50% 25%;
        mask-position: 50% 25%;
    }
    .block-collapsible-nav-content .item:nth-child(7) .svg-holder {
        -webkit-mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/shipping-status.svg"); ?>) no-repeat;
        mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/shipping-status.svg"); ?>) no-repeat;
        -webkit-mask-size: 20px 28px;
        mask-size: 20px 28px;
        -webkit-mask-position: 55% 10%;
        mask-position: 55% 10%;
    }


    .block-collapsible-nav-content .item:nth-child(9) .svg-holder {
        -webkit-mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/address-book.svg"); ?>) no-repeat;
        mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/address-book.svg"); ?>) no-repeat;
        -webkit-mask-size: 22px 26px;
        mask-size: 22px 26px;
        -webkit-mask-position: 50% 10%;
        mask-position: 50% 10%;
    }

    .block-collapsible-nav-content .item:nth-child(10) .svg-holder {
        -webkit-mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/account-settings.svg"); ?>) no-repeat;
        mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/account-settings.svg"); ?>) no-repeat;
        -webkit-mask-size: 22px 22px;
        mask-size: 22px 22px;
        -webkit-mask-position: 80% 30%;
        mask-position: 80% 30%;
    }

    .block-collapsible-nav-content .item:nth-child(11) .svg-holder {
        -webkit-mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/customer-service.svg"); ?>) no-repeat;
        mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/icons/customer-service.svg"); ?>) no-repeat;
        -webkit-mask-size: 20px 23px;
        mask-size: 20px 23px;
        -webkit-mask-position: 50% 10%;
        mask-position: 50% 10%;
    }

</style>
