    <div class="shape align-items-end mb-n160 shape-home-hero">
        <svg class="mb-n160" data-rellax-speed="-1" width="518" height="641" viewBox="0 0 518 641" fill="none" xmlns="http://www.w3.org/2000/svg">
            <circle cx="400.5" cy="320.5" r="320.5" fill="#3B7580" />
        </svg>
    </div>
    <div class="swiper swiper-portfolio swiper-portfolio-banner container text-white mt-sm-60" data-swiper-slides="1" data-swiper-speed="700" data-swiper-parallax="true" data-swiper-loop="true">
        <div class="swiper-container show-on-scroll" data-show-duration="800">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <a class="card card-portfolio card-overlay card-image-sm card-portfolio-banner text-white" href="#">
                                <span class="card-img swiper-image" data-swiper-parallax-x="20%">
                                    <img src="<?php echo $this->getViewFileUrl('images/Stock_bg.png'); ?>" alt="">
                                    <span class="background-color" style="background-color: rgba(14, 14, 14, .2);"></span>
                                </span>
                        <span class="card-img-overlay">
                                    <span class="card-title h2"><span class="card-title-decoration"></span>Shopping in Europe has never been easier.</span>
                                </span>
                    </a>
                </div>
                <div class="swiper-slide">
                    <a class="card card-portfolio card-overlay card-image-sm card-portfolio-banner text-white" href="#">
                                <span class="card-img swiper-image" data-swiper-parallax-x="20%">
                                    <img src="<?php echo $this->getViewFileUrl('images/bg_Boss.png'); ?>" alt="">
                                    <span class="background-color" style="background-color: rgba(14, 14, 14, .2);"></span>
                                </span>
                        <span class="card-img-overlay">
                                    <span class="card-title h2"><span class="card-title-decoration"></span>Some other text</span>
                                </span>
                    </a>
                </div>
            </div>
        </div>
        <div class="swiper-button-prev d-none d-sm-flex"><svg width='26' height='11' viewBox='0 0 26 11' fill='none' xmlns='http://www.w3.org/2000/svg'>
                <path d='M5.5 1L1 5.5L5.5 10' stroke='currentColor' stroke-width='1.3' stroke-linecap='round' stroke-linejoin='round' />
                <path d='M19 5.5H1' stroke='currentColor' stroke-width='1.3' stroke-linecap='round' stroke-linejoin='round' /></svg></div>
        <div class="swiper-button-next d-none d-sm-flex"><svg width='26' height='11' viewBox='0 0 26 11' fill='none' xmlns='http://www.w3.org/2000/svg'>
                <path d='M20.5 1L25 5.5L20.5 10' stroke='currentColor' stroke-width='1.3' stroke-linecap='round' stroke-linejoin='round' />
                <path d='M7 5.5H25' stroke='currentColor' stroke-width='1.3' stroke-linecap='round' stroke-linejoin='round' /></svg></div>
        <div class="swiper-pagination"></div>
    </div>
    </div>
    <div class="content-wrap">
        <div class="">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-lg-5 text-center text-lg-left show-on-scroll" data-show-delay="100" data-show-duration="800">
                        <h1 class="h2 mb-lg-0 text-gray-400 ">Premium parcel shipping from EU to China.</h1>
                    </div>
                    <div class="col-12 col-lg-5 ml-lg-100 justify-content-right-0 mt-5 box-shadow p-40 eos-home-register bg-white" data-show-delay="200" data-show-duration="100">

                        <form action="#" class="createOrderForm">
                            <div class="col-12 text-center">
                                <h4 class="text-grey-dark mb-40 mt-n10">Register</h4>

                            </div>
                            <div class="row gh-1 gv-2">

                                <div class="col-12 show-on-scroll pt-10" data-show-duration="400" data-show-distance="10" data-show-delay="470">
                                    <button class="btn w-full btn-primary btn-full" type="button" name="button">Create an account</button>
                                </div>

                                <div class="col-12 row show-on-scroll" data-show-duration="400" data-show-distance="10" data-show-delay="600">


                                    <div class="col-1">
                                        <img src="<?php echo $this->getViewFileUrl('images/Check.png'); ?>" width="20" />
                                    </div>
                                    <div class="col-11 pl-6 pt-2 font-italic font-size-16">
                                        <span>Official partner of SF Express</span>
                                    </div>
                                </div>
                                <div class="col-12 row show-on-scroll pt-10" data-show-duration="400" data-show-distance="10" data-show-delay="650">
                                    <div class="col-1">
                                        <img src="<?php echo $this->getViewFileUrl('images/Check.png'); ?>" width="20" />
                                    </div>
                                    <div class="col-11 pl-6 pt-2 font-italic font-size-16">
                                        <span>Affortable shipping</span>
                                    </div>
                                </div>
                                <div class="col-12 row show-on-scroll pt-10" data-show-duration="400" data-show-distance="10" data-show-delay="700">
                                    <div class="col-1">
                                        <img src="<?php echo $this->getViewFileUrl('images/Check.png'); ?>" width="20" />
                                    </div>
                                    <div class="col-11 pl-6 pt-2 font-italic font-size-16">
                                        <span>WeChat payment</span>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="py-40 mt-n8 shape-parent bg-white overflow-hidden" id="how-does-it-work">
            <div class="container">
                <h2 class="text-dark mb-100 mt-n10">How does it work</h2>
                <div class="row gh-1 gv-5">
                    <div class="col-12 col-lg-5">
                        <ul class="nav nav-opacity nav-tabs nav-gap-md flex-column text-dark" id="workTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active font-size-18" id="idea-tab" data-toggle="tab" href="#idea" role="tab" aria-controls="idea" aria-selected="true">Shop at your favourite brand</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link font-size-18" id="design-tab" data-toggle="tab" href="#design" role="tab" aria-controls="design" aria-selected="false">Register your order</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link font-size-18" id="development-tab" data-toggle="tab" href="#development" role="tab" aria-controls="development" aria-selected="false">Payment</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link font-size-18" id="release-tab" data-toggle="tab" href="#release" role="tab" aria-controls="release" aria-selected="false">Receive and enjoy!</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-12 col-lg-7">
                        <div class="tab-content text-dark mr-n30" id="workTabContent">
                            <div class="tab-pane fade show active" id="idea" role="tabpanel" aria-labelledby="idea-tab">
                                <div class="row gh-5 gv-5">
                                    <div class="col-md pr-60">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco </p>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="design" role="tabpanel" aria-labelledby="design-tab">
                                <div class="row gh-5 gv-5">
                                    <div class="col-md pr-60">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea </p>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="development" role="tabpanel" aria-labelledby="development-tab">
                                <div class="row gh-5 gv-5">
                                    <div class="col-md pr-60">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu</p>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="release" role="tabpanel" aria-labelledby="release-tab">
                                <div class="row gh-5 gv-5">
                                    <div class="col-lg pr-60">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr class="mt-100 mb-40 pb-7" style="border-top-color:#aaa">
            </div>
        </div>


