<!--<div class="navbar navbar-mobile navbar-mobile-style-2" id="navbar-mobile-style-2">-->

<!--    <div class="container">-->
<!--        <div class="row gh-1 justify-content-center">-->
            <div class="col-12 col-md-7 col-lg-5 col-xl-4">
                <div class="navbar-body">
                    <ul class="nav navbar-nav navbar-nav-collapse">
                        <li class="nav-item">
                            <a href="home-eos.html" class="nav-link">
                                <span class="nav-link-name">home</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="home-eos.html#how-does-it-work" class="nav-link">
                                <span class="nav-link-name">Services</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="login-eos.html" class="nav-link">
                                <span class="nav-link-name">Login</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-1 d-none d-md-block"></div>

<!--        </div>-->
<!--    </div>-->
<!--</div>-->
