<div class="col-12 col-md-4 col-lg-4 col-xl-3">
    <div class="navbar-footer">
        <div class="mb-60">
            <h4 class="mb-17 font-weight-medium font-size-18">Contact info:</h4>
            <ul class="list-group borderless font-size-14">
                <li class="list-group-item">Email: <a href="#">info@europeonlineservices.com</a></li>
                <li class="list-group-item">Phone: <a href="#">+31 6 12 34 56 78</a></li>
            </ul>
        </div>
        <div class="mb-60">
            <h4 class="mb-17 font-weight-medium font-size-18">Warehouse Address:</h4>
            <ul class="list-group borderless font-size-14">
                <li class="list-group-item">Straatnaam 123 Amsterdam</li>
                <li class="list-group-item">1234 AB, The Netherlands</li>
            </ul>
        </div>
    </div>
</div>
