<div class="shape justify-content-end">
    <svg data-rellax-speed="0" width="544" height="362" viewBox="0 0 544 362" fill="none" xmlns="http://www.w3.org/2000/svg" style="transform: translate3d(0px, 0px, 0px);">
        <circle cx="320.5" cy="41.5" r="320.5" fill="#ececec"></circle>
    </svg>
</div>
<div class="navbar-head">
    <div class="container">
        <a class="navbar-brand" href="home.html">
            <img width="90" src='<?php echo $this->getViewFileUrl('images/Eos_logo.svg'); ?>' alt="">
        </a>
        <a class="navbar-toggle" href="#" data-fancybox-close="">
            <span></span>
            <span></span>
            <span></span>
        </a>
    </div>
</div>
