<div  class="py-100">
    <div class="container step">
        <div class="row col-12 text-center">
            <h3 style="margin:auto; margin-bottom:20px;">Are you ready to start sending parcels from Europe to Asia?</h3>
            <p style="margin:0 auto;margin-bottom:25px;">Join us, and experience the simplicity of parcel transportation with Europe Online Services!</p>
            <p class="text-center" style="width: 100%;">
                <a href="#" class="btn btn-primary text-center" style="width: 250px;">Sign up for free</a>
            </p>
        </div>
    </div>

</div>
