<?php
/** @var \Magento\Framework\View\Element\Template $block */
/**@var Eos\WmsPortal\ViewModel\Orders $viewModel*/
$viewModel = $block->getData('view_model');
?>


<?php // $_items = $viewModel->getShipmentOrders(['open'], ['Shipment created'] , false,false); // Not booked + customer completed upload  ?>
<?php //  $_items = $viewModel->getShipmentOrders(null,null , false,false); // Booked + customer completed upload   ?>
<?php  $_items = $viewModel->getOrdersReadyForBatch(); // Booked + Either draft or completed order  ?>

<input type="hidden" class="orderlist-ready-for-batch-count" value="<?= count($_items)?>"/>
<?php if ($_items && count($_items)) : ?>

            <?php foreach ($_items as $_item) : ?>
                <?php

                    $shipment = $viewModel->getShipments(null, (isset($_item['shipment_id']) ? $_item['shipment_id'] : null));

                   // if (!in_array($_item['status'], array('open:init','open:webshop', 'open:warehouse','open:product'))) : ?>

                <tr class="orderlist orderlist-ready-for-batch">
                    <td data-th="<?= __('Date') ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_item['created_at']) ?></td>
                    <td data-th="<?= __('Tracking Nr.') ?>" class="col status"><?= /* @noEscape */ strtoupper($_item['webshop_tracking_number']) ?></td>
                    <td data-th="<?= __('Shipment ID') ?>" class="col status"><?= (isset($shipment['f_shipment_id']) ? $shipment['f_shipment_id'] : "");  ?></td>
                    <td data-th="<?= __('Shipment ID') ?>" class="col status"><?= (isset($shipment['awb_code']) ? $shipment['awb_code'] : "");  ?> <?= (isset($shipment['printUrl']) && $shipment['printUrl'] !== null ? " - <a href='" .$shipment['printUrl'] . "' target='_blank'>Print</a>" : "");  ?>  </td>
                    <td data-th="<?= __('Shipment Status') ?>" class="col status">
                        <?php
                            if(isset($shipment['status'])){

                                if($shipment['status'] === 'Ready for payment' && $viewModel->countParcelsShipment($_item['shipment_id']) === 0){
                                    echo ' <span id="tooltip-noparcels" data-toggle="tooltip" data-placement="top" title="No parcels found on this shipment. Be sure to fix this."> ' . $shipment['status'] . '
                                              <svg width="14" height="14" color="#dd0000" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="circle-exclamation" class="svg-inline--fa fa-circle-exclamation" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M256 0C114.6 0 0 114.6 0 256s114.6 256 256 256s256-114.6 256-256S397.4 0 256 0zM232 152C232 138.8 242.8 128 256 128s24 10.75 24 24v128c0 13.25-10.75 24-24 24S232 293.3 232 280V152zM256 400c-17.36 0-31.44-14.08-31.44-31.44c0-17.36 14.07-31.44 31.44-31.44s31.44 14.08 31.44 31.44C287.4 385.9 273.4 400 256 400z"></path></svg>
                                            </span>';
                                } else {
                                    echo $shipment['status'];
                                }


                            }
                        ?>
                    </td>
                    <td data-th="<?= __('Order Status') ?>" class="col status"><?= /* @noEscape */ $_item['status'] ?></td>
                    <td data-th="<?= __('Webshop') ?>" class="col status"><?= /* @noEscape */ $_item['webshop_title'] ?></td>
                    <td data-th="<?= __('Action') ?>" class="col action ">
                              <a href="<?php echo $this->getUrl('wms/orders/order', ['order_id'=> $_item['entity_id']]); ?>" name="<?= $_item['webshop_tracking_number'] ?>" >
                            <button class="btn btn-secondary btn-small mr-20 btn-modal" >
                                Details
                            </button>
                        </a>
                    </td>

                </tr>
            <?php
                   // endif;

            endforeach; ?>




<?php else : ?>
    <!--<div class="message info empty"><span><?/*= $viewModel->getEmptyOrdersMessage(); */?></span></div>-->
<?php endif ?>

