<?php
/** @var \Magento\Framework\View\Element\Template $block */
/**@var Eos\WmsPortal\ViewModel\Orders $viewModel*/
$viewModel = $block->getData('view_model');

?>

<?php  $_items = $viewModel->getOrdersAwaitingForPayment();  ?>

<input type="hidden" class="orderlist-awaiting-payment-count" value="<?= count($_items)?>"/>

<?php if ($_items && count($_items)) : ?>

    <?php foreach ($_items as $_item) : ?>

        <?php $shipment = $viewModel->getShipments(null, (isset($_item['shipment_id']) ? $_item['shipment_id'] : null)); ?>

        <?php if (!in_array($_item['status'], array('open:init','open:webshop', 'open:warehouse','open:product'))) : ?>

            <tr class="orderlist orderlist-awaiting-payment">
                <td data-th="<?= __('Date') ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_item['created_at']) ?></td>
                <td data-th="<?= __('Tracking Nr.') ?>" class="col status"><?= /* @noEscape */ strtoupper($_item['webshop_tracking_number']) ?></td>
                <td data-th="<?= __('Shipment ID') ?>" class="col status"><?= (isset($shipment['f_shipment_id']) ? $shipment['f_shipment_id'] : "");  ?></td>
                <td data-th="<?= __('Shipment ID') ?>" class="col status"><?= (isset($shipment['awb_code']) ? $shipment['awb_code'] : "");  ?> <?= (isset($shipment['printUrl']) && $shipment['printUrl'] !== null ? " - <a href='" .$shipment['printUrl'] . "' target='_blank'>Print</a>" : "");  ?>  </td>
                <td data-th="<?= __('Shipment Status') ?>" class="col status">
                    <?php
                    if(isset($shipment['status'])){

                        if($shipment['status'] === 'Ready for payment' && $viewModel->countParcelsShipment($_item['shipment_id']) === 0){
                            echo ' <span id="tooltip-noparcels" data-toggle="tooltip" data-placement="top" title="No parcels found on this shipment. Be sure to fix this."> ' . $shipment['status'] . '
                                                  <svg width="14" height="14" color="#dd0000" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="circle-exclamation" class="svg-inline--fa fa-circle-exclamation" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M256 0C114.6 0 0 114.6 0 256s114.6 256 256 256s256-114.6 256-256S397.4 0 256 0zM232 152C232 138.8 242.8 128 256 128s24 10.75 24 24v128c0 13.25-10.75 24-24 24S232 293.3 232 280V152zM256 400c-17.36 0-31.44-14.08-31.44-31.44c0-17.36 14.07-31.44 31.44-31.44s31.44 14.08 31.44 31.44C287.4 385.9 273.4 400 256 400z"></path></svg>
                                                </span>';
                        } else {
                            echo $shipment['status'];
                        }


                    }
                    ?>
                </td>
                <td data-th="<?= __('Order Status') ?>" class="col status"><?= /* @noEscape */ $_item['status'] ?></td>
                <td data-th="<?= __('Webshop') ?>" class="col status"><?= /* @noEscape */ $_item['webshop_title'] ?></td>
                <td data-th="<?= __('Action') ?>" class="col action ">

                    <a href="<?php echo $this->getUrl('wms/orders/order', ['order_id'=> $_item['entity_id']]); ?>" name="<?= $_item['webshop_tracking_number'] ?>" >
                        <button class="btn btn-secondary btn-small mr-20 btn-modal" >
                            Details
                        </button>
                    </a>
                </td>

            </tr>
        <?php endif; ?>

    <?php endforeach; ?>

<?php else : ?>
    <!--<div class="message info empty"><span><?/*= $viewModel->getEmptyOrdersMessage(); */?></span></div>-->
<?php endif ?>


<script>
    require(["jquery", "Eos_Base/js/bootstrap.bundle.min", 'Eos_Base/js/packageDetails','mage/url'], function ($, bootstrap,packageDetails,urlBuilder) {

        $('#tooltip-noparcels').on("hover", function (){
            $(this).tooltip('toggle')
        });

       $('.btn-modal').on("click", function() {
           $('.modal').remove();

           var myUrl = urlBuilder.build('wms/warehouse/book');

           var modal = '<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">\n' +
               '    <div class="modal-dialog modal-dialog-centered" role="document">\n' +
               '        <div class="modal-content">\n' +
               '            <div class="modal-header">\n' +
               '                <h5 class="modal-title" id="exampleModalLongTitle">Book parcel</h5>\n' +
               '                <button type="button" class="close" data-dismiss="modal" aria-label="Close">\n' +
               '                    <span aria-hidden="true">&times;</span>\n' +
               '                </button>\n' +
               '            </div>\n' +
               '            <div class="modal-body">\n' +
               '                <p>Are you sure you want to book: ' + $(this).attr('name') + '</p>' +
               '            </div>\n' +
               '            <div class="modal-footer">\n' +
               '                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>\n' +
               '                <a href="'+ myUrl + '/webshop_tracking_number/' + $(this).attr('name') + '/type/book" type="button" class="btn btn-primary">Save changes</a>\n' +
               '            </div>\n' +
               '        </div>\n' +
               '    </div>\n' +
               '</div>\n';

          $('body').append(modal);
       });


        $('.btn-modal-unbook').on("click", function() {
            $('.modal').remove();

            var newUrl = urlBuilder.build('wms/warehouse/book');

            var modal = '<div class="modal fade" id="unbookParcel" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">\n' +
                '    <div class="modal-dialog modal-dialog-centered" role="document">\n' +
                '        <div class="modal-content">\n' +
                '            <div class="modal-header">\n' +
                '                <h5 class="modal-title" id="exampleModalLongTitle">Book parcel</h5>\n' +
                '                <button type="button" class="close" data-dismiss="modal" aria-label="Close">\n' +
                '                    <span aria-hidden="true">&times;</span>\n' +
                '                </button>\n' +
                '            </div>\n' +
                '            <div class="modal-body">\n' +
                '                <p>Are you sure you want to unbook: ' + $(this).attr('name') + '</p>' +
                '            </div>\n' +
                '            <div class="modal-footer">\n' +
                '                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>\n' +
                '                <a href="'+ newUrl + '/webshop_tracking_number/' + $(this).attr('name') + '/type/unbook" type="button" class="btn btn-primary">Save changes</a>\n' +
                '            </div>\n' +
                '        </div>\n' +
                '    </div>\n' +
                '</div>\n';

            $('body').append(modal);
        });
    });


</script>
<!-- Modal -->
