<?php
/** @var \Magento\Framework\View\Element\Template $block */
/**@var Eos\WmsPortal\ViewModel\Orders $viewModel*/
$viewModel = $block->getData('view_model');

?>

<?php  $_items = $viewModel->getOrdersReadyForPayment();  ?>

<input type="hidden" class="orderlist-ready-for-payment-count" value="<?= count($_items)?>"/>
<?php if ($_items && count($_items)) : ?>

            <?php foreach ($_items as $_item) : ?>

                <?php

                    $shipment = $viewModel->getShipments(null, (isset($_item['shipment_id'])? $_item['shipment_id'] : null));

                    if ($shipment['status']) : ?>
                <tr class="orderlist orderlist-ready-for-payment">
                    <td data-th="<?= __('Date') ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_item['created_at']) ?></td>
                    <td data-th="<?= __('Tracking Nr.') ?>" class="col status"><?= /* @noEscape */ strtoupper($_item['webshop_tracking_number']) ?></td>
                    <td data-th="<?= __('Shipment ID') ?>" class="col status"><?= (isset($shipment['f_shipment_id']) ? $shipment['f_shipment_id'] : "");  ?></td>
                    <td data-th="<?= __('Shipment ID') ?>" class="col status"><?= (isset($shipment['awb_code']) ? $shipment['awb_code'] : "");  ?> <?= (isset($shipment['printUrl']) && $shipment['printUrl'] !== null ? " - <a href='" .$shipment['printUrl'] . "' target='_blank'>Print</a>" : "");  ?>  </td>
                    <td data-th="<?= __('Shipment Status') ?>" class="col status">
                        <?php
                            if(isset($shipment['status'])){

                                if($shipment['status'] === 'Ready for payment' && $viewModel->countParcelsShipment($_item['shipment_id']) === 0){
                                    echo ' <span id="tooltip-noparcels" data-toggle="tooltip" data-placement="top" title="No parcels found on this shipment. Be sure to fix this."> ' . $shipment['status'] . '
                                              <svg width="14" height="14" color="#dd0000" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="circle-exclamation" class="svg-inline--fa fa-circle-exclamation" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M256 0C114.6 0 0 114.6 0 256s114.6 256 256 256s256-114.6 256-256S397.4 0 256 0zM232 152C232 138.8 242.8 128 256 128s24 10.75 24 24v128c0 13.25-10.75 24-24 24S232 293.3 232 280V152zM256 400c-17.36 0-31.44-14.08-31.44-31.44c0-17.36 14.07-31.44 31.44-31.44s31.44 14.08 31.44 31.44C287.4 385.9 273.4 400 256 400z"></path></svg>
                                            </span>';
                                } else {
                                    echo $shipment['status'];
                                }


                            }
                        ?>
                    </td>
                    <td data-th="<?= __('Order Status') ?>" class="col status"><?= /* @noEscape */ $_item['status'] ?></td>
                    <td data-th="<?= __('Webshop') ?>" class="col status"><?= /* @noEscape */ $_item['webshop_title'] ?></td>
                    <td data-th="<?= __('Action') ?>" class="col action ">
                        <button class="btn btn-primary btn-small mr-20 btn-modal-confirm" name="<?= $_item['awb_code'] ?>" data-toggle="modal" data-target="#confirmParcel">
                            Confirm
                        </button>
                        <button class="btn btn-secondary btn-small mr-20 btn-modal-consolidate" name="<?= $_item['awb_code'] ?>" data-toggle="modal" data-target="#consolidateParcel">
                            Add main parcel & Confirm
                        </button>
                        <a href="<?php echo $this->getUrl('wms/orders/order', ['order_id'=> $_item['entity_id']]); ?>" name="<?= $_item['webshop_tracking_number'] ?>" >
                            <button class="btn btn-secondary btn-small mr-20 btn-modal" >
                                Details
                            </button>
                        </a>
                    </td>

                </tr>
            <?php
                    endif;

            endforeach; ?>




<?php else : ?>
    <!--<div class="message info empty"><span><?/*= $viewModel->getEmptyOrdersMessage(); */?></span></div>-->
<?php endif ?>


<script>
    require(["jquery", "Eos_Base/js/bootstrap.bundle.min", 'Eos_Base/js/packageDetails','mage/url'], function ($, bootstrap,packageDetails,urlBuilder) {

        $('#tooltip-noparcels').on("hover", function (){
            $(this).tooltip('toggle')
        });

        $('.btn-modal-confirm').on("click", function() {
           $('.modal').remove();

           var url = urlBuilder.build('wms/orders/save');

           var modal = '<div class="modal fade" id="confirmParcel" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">\n' +
               '    <div class="modal-dialog modal-dialog-centered" role="document">\n' +
               '        <div class="modal-content">\n' +
               '            <div class="modal-header">\n' +
               '                <h5 class="modal-title" id="exampleModalLongTitle">Confirm Shipment</h5>\n' +
               '                <button type="button" class="close" data-dismiss="modal" aria-label="Close">\n' +
               '                    <span aria-hidden="true">&times;</span>\n' +
               '                </button>\n' +
               '            </div>\n' +
               '            <div class="modal-body">\n' +
               '                <p>Are you sure you want to confirm: ' + $(this).attr('name') + '</p>' +
               '            </div>\n' +
               '            <div class="modal-footer">\n' +
               '                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>\n' +
               '                <a href="'+ url + '/outbound_tracking_number/' + $(this).attr('name') + '" type="button" class="btn btn-primary">Save changes</a>\n' +
               '            </div>\n' +
               '        </div>\n' +
               '    </div>\n' +
               '</div>\n';

          $('body').append(modal);
       });


        $('.btn-modal-consolidate').on("click", function() {
            $('.modal').remove();

            var url = urlBuilder.build('wms/orders/save');

            var modal = '<div class="modal fade" id="consolidateParcel" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">\n' +
                '    <div class="modal-dialog modal-dialog-centered" role="document">\n' +
                '        <div class="modal-content">\n' +
                '            <div class="modal-header">\n' +
                '                <h5 class="modal-title" id="exampleModalLongTitle">Consolidated parcel & confirm</h5>\n' +
                '                <button type="button" class="close" data-dismiss="modal" aria-label="Close">\n' +
                '                    <span aria-hidden="true">&times;</span>\n' +
                '                </button>\n' +
                '            </div>' +
                '            <form class="createOrderForm needs-validation" novalidate method="post" action="/wms/orders/save">' +
                '               <input type="hidden" name="outbound_tracking_number" value="' + $(this).attr('name') + '" />' +
                '               <div class="modal-body mb-40">' +
                '                    <label class="input-label" for="totalweight">Fill in total weight of consolidated parcel.</label>' +
                '                    <input id="totalweight" class="input-text form-control" required name="total_weight" type="number" placeholder="Total weight (KG)" onpaste="return false;" ondrop="return false;" autocomplete="off"/> ' +
                '<div class="row col-12">';

            <?php
            $templates = $viewModel->getParcelTemplates();

            foreach($templates as $template) {

                ?>

            modal += '<div class="col-4 btn-check-holder px-4">' +
                    '<input name="parcelTemplate-<?=$template['entity_id']?>" type="checkbox" class="btn-check-input" id="btn-check-input-<?=$template['entity_id'];?>" autocomplete="off">' +
                    '<label class="btn btn-full btn-check-label" for="btn-check-input-<?=$template['entity_id'];?>"><?= $template['title']?></label>' +
                '</div>';

            <?php

            }
            ?>

            modal += '</div>                    <div class="invalid-feedback">Please provide a weight in KG.</div> ' +
                '                </div>' +
                '               <div class="modal-footer">\n' +
                '                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>\n' +
                '                    <button type="submit" class="btn btn-primary">Save changes</button>\n' +
                '            </form> ' +
                '           </div>\n' +
                '        </div>\n' +
                '    </div>\n' +
                '</div>\n';

            $('body').append(modal);
        });

        $(document).on('click', '.btn-check-label', function() {
            $('.btn-check-holder').removeClass('btn-check-holder-active');
            $('.btn-check-holder .btn-check-input').removeAttr('checked');
            $(this).closest('.btn-check-holder').find('.btn-check-input').attr('checked');
            $(this).closest('.btn-check-holder').addClass('btn-check-holder-active');
        });
    });


</script>
<!-- Modal -->
