<ul class="nav nav-pills py-10 px-20">
    <li class="nav-item">
        <a class="nav-link active" data-target="orderlist-open-orders" aria-current="page" href="#">Incoming parcels</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-target="orderlist-booked-parcels" href="#">Booked parcels</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-target="orderlist-onhold-parcels" href="#">Onhold parcels</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-target="orderlist-not-ready-for-payment" href="#">Not confirmed</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-target="orderlist-ready-for-payment" href="#">Ready for payment</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-target="orderlist-awaiting-payment" href="#">Awaiting payment</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-target="orderlist-ready-for-batch" >Ready for batch</a>
    </li>
<!--    <li class="nav-item">
        <a class="nav-link" data-target="orderlist-in-batch" >In batch</a>
    </li>-->
    <li class="nav-item">
        <a class="nav-link" data-target="orderlist-archive" >Archive</a>
    </li>
</ul>

<script>
    require(["jquery", "Eos_Base/js/bootstrap.bundle.min"], function ($, bootstrap) {
        $('.nav-link').on('click' , function() {
            $('.nav-link').removeClass('active');
            $(this).addClass('active');

            $('.orderlist').removeClass('orderlist-active')
            $('.' + $(this).attr('data-target')).addClass('orderlist-active');

        });
        $('.nav-link').each(function(){

            $(this).append('<div class="item-counter"><span>' + $('.' + $(this).attr('data-target') + '-count').attr('value') + '</span></div>');
        });


    });


</script>
<!-- Modal -->

<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?= __('Orders') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col date"><?= __('Date') ?></th>
            <th scope="col" class="col status"><?= __('Inbound tracking Nr.') ?></th>
            <th scope="col" class="col status"><?= __('Shipment ID') ?></th>
            <th scope="col" class="col status"><?= __('AWB Code') ?></th>
            <th scope="col" class="col status"><?= __('Shipment Status') ?></th>
            <th scope="col" class="col status"><?= __('Order Status') ?></th>
            <th scope="col" class="col status"><?= __('Webshop') ?></th>
            <th scope="col" class="col status"><?= __('Action') ?></th>

        </tr>
        </thead>
        <tbody>
