<div class="pb-100">
    <div class="container step">
        <div class="row col-12">
            <div class="col-12 col-lg-6 text-center mb-40 mb-lg-0">
                <img style="max-width:350px;" src='<?php echo $this->getViewFileUrl('images/howitworks/01_register.svg'); ?>' alt="">
            </div>
            <div class="col-12 col-lg-6 px-20">
                <h1 class="text-center" style="color:#3B7580;">1</h1>
                <hr class="divider"/>
                <h2 style="font-weight: 200;color:#3B7580;">Sign up for free and create an account</h2>
                <!--<p class="description-short" >Sign up for free and receive your EU shipping address and member ID to send parcels to.</p>
                --><p id="description-long-1" class="d-lg-none description-long collapse mb-20" >
                    With our free online platform, you can simply start to create your shipments and right away send parcels by airplane to your address in Asia. Our fully automatic platform assists you in sending parcels safely.
                </p><p class="d-none d-lg-block mb-20" >
                    With our free online platform, you can simply start to create your shipments and right away send parcels by airplane to your address in Asia. Our fully automatic platform assists you in sending parcels safely.
                </p>
                <p>
                    <a class="btn text-center btn-readmore d-block d-lg-none" data-toggle="collapse" href="#description-long-1" role="button" aria-expanded="false" aria-controls="description-long-1">
                        <span class="btn-readmore-line"></span>
                        <span class="btn-readmore-text">
                            <span>Read more</span> <br>
                             <svg class="more-arrows">
                              <polygon class="arrow-top" points="37.6,27.9 1.8,1.3 3.3,0 37.6,25.3 71.9,0 73.7,1.3 "/>
                              <polygon class="arrow-middle" points="37.6,45.8 0.8,18.7 4.4,16.4 37.6,41.2 71.2,16.4 74.5,18.7 "/>
                              <polygon class="arrow-bottom" points="37.6,64 0,36.1 5.1,32.8 37.6,56.8 70.4,32.8 75.5,36.1 "/>
                            </svg>
                        </span>
                    </a>

                </p>

            </div>
        </div>
    </div>
</div>
<div style="box-shadow: 0 0px 5px 3px rgba(0,0,0,0.1); background:#fafafa;" class="py-100">
    <div class="container step">
        <div class="row col-12">
            <div class="col-12 col-lg-6 order-2 order-lg-1 px-20">
                <h1 class="text-center" style="color:#3B7580;">2</h1>
                <hr class="divider"/>
                <h2 style="font-weight: 200;color:#3B7580;">Start shopping in Europe</h2>

               <!-- <p class="description-short" >Sign up for free and receive your EU shipping address and member ID to send parcels to.</p>
                --><p id="description-long-2" class="d-lg-none description-long collapse mb-20" >
                    Add your EU shipping address and member ID on the purchase order at an online shop. Your EU shipping address is linked to one of our warehouse locations where we will store, secure and prepare your parcels for shipment and delivery.
                </p>
                <p class="d-none d-lg-block mb-20" >
                    Add your EU shipping address and member ID on the purchase order at an online shop. Your EU shipping address is linked to one of our warehouse locations where we will store, secure and prepare your parcels for shipment and delivery.
                </p>
                <p>
                    <a class="btn text-center btn-readmore d-lg-none" data-toggle="collapse" href="#description-long-2" role="button" aria-expanded="false" aria-controls="description-long-2">
                        <span class="btn-readmore-line"></span>
                        <span class="btn-readmore-text"  style="background:#fafafa;border-color:#fafafa;">
                            <span>Read more</span> <br>
                             <svg class="more-arrows">
                              <polygon class="arrow-top" points="37.6,27.9 1.8,1.3 3.3,0 37.6,25.3 71.9,0 73.7,1.3 "/>
                              <polygon class="arrow-middle" points="37.6,45.8 0.8,18.7 4.4,16.4 37.6,41.2 71.2,16.4 74.5,18.7 "/>
                              <polygon class="arrow-bottom" points="37.6,64 0,36.1 5.1,32.8 37.6,56.8 70.4,32.8 75.5,36.1 "/>
                            </svg>
                        </span>
                    </a>

                </p>

            </div>
            <div class="col-12 col-lg-6 order-1 order-lg-2 mb-40 mb-lg-0 text-center">
                <img style="max-width:350px;" src='<?php echo $this->getViewFileUrl('images/howitworks/02_shopping.svg'); ?>' alt="">
            </div>

        </div>
    </div>
</div>
<div  class="py-100">
    <div class="container step">
        <div class="row col-12">
            <div class="col-12 col-lg-6 text-center mb-40 mb-lg-0">
                <img style="max-width:350px;" src='<?php echo $this->getViewFileUrl('images/howitworks/03_parcel_upload.svg'); ?>' alt="">
            </div>
            <div class="col-12 col-lg-6 px-20">
                <h1 class="text-center" style="color:#3B7580;">3</h1>
                <hr class="divider"/>
                <h2 style="font-weight: 200;color:#3B7580;">Upload the parcel information in your Europe Online Services account</h2>
                <!--<p class="description-short" >Sign up for free and receive your EU shipping address and member ID to send parcels to.</p>
                --><p id="description-long-3" class="description-long collapse mb-20 d-lg-none" >
                    Simply upload your parcel information in your Europe Online Services account to automate all the documentation processes. Our platform automatically takes care of all the documentation, so you don't have to worry about the paperwork, customs clearances, and shipping difficulties.
                </p>
                <p class="d-none d-lg-block mb-20" >
                    Add your EU shipping address and member ID on the purchase order at an online shop. Your EU shipping address is linked to one of our warehouse locations where we will store, secure and prepare your parcels for shipment and delivery.
                </p>
                <p>
                    <a class="btn text-center btn-readmore d-lg-none" data-toggle="collapse" href="#description-long-3" role="button" aria-expanded="false" aria-controls="description-long-3">
                        <span class="btn-readmore-line"></span>
                        <span class="btn-readmore-text">
                            <span>Read more</span> <br>
                             <svg class="more-arrows">
                              <polygon class="arrow-top" points="37.6,27.9 1.8,1.3 3.3,0 37.6,25.3 71.9,0 73.7,1.3 "/>
                              <polygon class="arrow-middle" points="37.6,45.8 0.8,18.7 4.4,16.4 37.6,41.2 71.2,16.4 74.5,18.7 "/>
                              <polygon class="arrow-bottom" points="37.6,64 0,36.1 5.1,32.8 37.6,56.8 70.4,32.8 75.5,36.1 "/>
                            </svg>
                        </span>
                    </a>

                </p>

            </div>
        </div>
    </div>

</div>
<div style="box-shadow: 0 0px 5px 3px rgba(0,0,0,0.1); background:#fafafa;" class="py-100">
    <div class="container step">
        <div class="row col-12">
            <div class="col-12 col-lg-6 order-2 order-lg-1 px-20">
                <h1 class="text-center" style="color:#3B7580;">4</h1>
                <hr class="divider"/>
                <h2 style="font-weight: 200;color:#3B7580;">When your parcels arrive at our warehouse, transportation is calculated and prepared</h2>
                <!--<p class="description-short" >Sign up for free and receive your EU shipping address and member ID to send parcels to.</p>
                --><p id="description-long-4" class="description-long collapse mb-20 d-lg-none" >
                    We use specialized warehouse software to calculate the lowest shipping price for you. Based on weight, size, volume and repackaging after the parcels arrive at one of our warehouses.
                </p>
                <p class="d-none d-lg-block mb-20" >
                    We use specialized warehouse software to calculate the lowest shipping price for you. Based on weight, size, volume and repackaging after the parcels arrive at one of our warehouses.
                </p>
                <p>
                    <a class="btn text-center btn-readmore d-lg-none" data-toggle="collapse" href="#description-long-4" role="button" aria-expanded="false" aria-controls="description-long-4">
                        <span class="btn-readmore-line"></span>
                        <span class="btn-readmore-text"  style="background:#fafafa;border-color:#fafafa;">
                            <span>Read more</span> <br>
                             <svg class="more-arrows">
                              <polygon class="arrow-top" points="37.6,27.9 1.8,1.3 3.3,0 37.6,25.3 71.9,0 73.7,1.3 "/>
                              <polygon class="arrow-middle" points="37.6,45.8 0.8,18.7 4.4,16.4 37.6,41.2 71.2,16.4 74.5,18.7 "/>
                              <polygon class="arrow-bottom" points="37.6,64 0,36.1 5.1,32.8 37.6,56.8 70.4,32.8 75.5,36.1 "/>
                            </svg>
                        </span>
                    </a>

                </p>

            </div>
            <div class="col-12 col-lg-6 order-1 order-lg-2 mb-40 mb-lg-0 text-center">
                <img style="max-width:400px;width: 100%;" src='<?php echo $this->getViewFileUrl('images/howitworks/04_parcel_arrival.svg'); ?>' alt="">
            </div>

        </div>
    </div>
</div>
<div  class="py-100">
    <div class="container step">
        <div class="row col-12">
            <div class="col-12 col-lg-6 text-center mb-40 mb-lg-0">
                <img style="max-width:350px;" src='<?php echo $this->getViewFileUrl('images/howitworks/05_payment.svg'); ?>' alt="">
            </div>
            <div class="col-12 col-lg-6 px-20">
                <h1 class="text-center" style="color:#3B7580;">5</h1>
                <hr class="divider"/>
                <h2 style="font-weight: 200;color:#3B7580;">Confirm shipment and perform the payment</h2>
                <p id="description-long-5" class="description-long collapse mb-20 d-lg-none" >
                    Our platform will send you a payment request according to our pricing tables and calculation software. After that, Europe Online Services will ensure that your parcel is delivered as quickly, efficiently and reliably as possible.
                </p>
                <p class="d-none d-lg-block mb-20" >
                    Our platform will send you a payment request according to our pricing tables and calculation software. After that, Europe Online Services will ensure that your parcel is delivered as quickly, efficiently and reliably as possible.
                </p>
                <p>
                    <a class="btn text-center btn-readmore d-lg-none" data-toggle="collapse" href="#description-long-5" role="button" aria-expanded="false" aria-controls="description-long-5">
                        <span class="btn-readmore-line"></span>
                        <span class="btn-readmore-text">
                            <span>Read more</span> <br>
                             <svg class="more-arrows">
                              <polygon class="arrow-top" points="37.6,27.9 1.8,1.3 3.3,0 37.6,25.3 71.9,0 73.7,1.3 "/>
                              <polygon class="arrow-middle" points="37.6,45.8 0.8,18.7 4.4,16.4 37.6,41.2 71.2,16.4 74.5,18.7 "/>
                              <polygon class="arrow-bottom" points="37.6,64 0,36.1 5.1,32.8 37.6,56.8 70.4,32.8 75.5,36.1 "/>
                            </svg>
                        </span>
                    </a>

                </p>

            </div>
        </div>
    </div>

</div>
<div style="box-shadow: 0 0px 5px 3px rgba(0,0,0,0.1); background:#fafafa;" class="py-100">
    <div class="container step">
        <div class="row col-12">
            <div class="col-12 col-lg-6 order-2 order-lg-1 px-20">
                <h1 class="text-center" style="color:#3B7580;">6</h1>
                <hr class="divider"/>
                <h2 style="font-weight: 200;color:#3B7580;">Receive your parcel and enjoy!</h2>
                <p id="description-long-6" class="description-long collapse mb-20 d-lg-none" >
                    Use our track and trace code to follow your parcel anywhere and enjoy the simplicity of our services.
                </p>
                <p class="d-none d-lg-block mb-20" >
                    Use our track and trace code to follow your parcel anywhere and enjoy the simplicity of our services.
                </p>
                <p>
                    <a class="btn text-center btn-readmore d-lg-none" data-toggle="collapse" href="#description-long-6" role="button" aria-expanded="false" aria-controls="description-long-6">
                        <span class="btn-readmore-line"></span>
                        <span class="btn-readmore-text"  style="background:#fafafa;border-color:#fafafa;">
                            <span>Read more</span> <br>
                             <svg class="more-arrows">
                              <polygon class="arrow-top" points="37.6,27.9 1.8,1.3 3.3,0 37.6,25.3 71.9,0 73.7,1.3 "/>
                              <polygon class="arrow-middle" points="37.6,45.8 0.8,18.7 4.4,16.4 37.6,41.2 71.2,16.4 74.5,18.7 "/>
                              <polygon class="arrow-bottom" points="37.6,64 0,36.1 5.1,32.8 37.6,56.8 70.4,32.8 75.5,36.1 "/>
                            </svg>
                        </span>
                    </a>

                </p>

            </div>
            <div class="col-12 col-lg-6 order-1 order-lg-2 mb-40 mb-lg-0 text-center">
                <img style="max-width:400px;width:100%;" src='<?php echo $this->getViewFileUrl('images/howitworks/06_parcel_delivery.svg'); ?>' alt="">
            </div>

        </div>
    </div>
</div>
<div  class="py-100">
    <div class="container step">
        <div class="row col-12 text-center">
            <h3 style="margin:auto; margin-bottom:20px;">Are you ready to start sending parcels from Europe to Asia?</h3>
            <p style="margin:0 auto;margin-bottom:25px;">Join us, and experience the simplicity of parcel transportation with Europe Online Services!</p>
            <p class="text-center" style="width: 100%;">
                <a href="<?php echo $this->getUrl('customer/account/create'); ?>" class="btn btn-primary text-center" style="width: 250px;">Sign up for free</a>
            </p>
        </div>
    </div>

</div>


<script>

require(["jquery", "Eos_Base/js/bootstrap.bundle.min"], function ($) {

$('.btn-readmore').on('mouseenter', function () {
   $('.arrow-top').attr('style', 'transform: translateY(18px)');
   $('.arrow-bottom').attr('style', 'transform: translateY(-18px)');
}).on('mouseleave', function () {
    $('.arrow-top').attr('style', 'transform: translateY(-5px)');
    $('.arrow-bottom').attr('style', 'transform: translateY(5px)');
}).on('click', function () {
    if(!$(this).closest('.step').find('.description-long').hasClass('show')) {
        $(this).find('.more-arrows').attr('opacity', 0);
        $(this).find('span:first-child').text('Read less');
    } else {
        $(this).find('.more-arrows').attr('opacity', 1);
        $(this).find('span:first-child').text('Read more');
    }

});


});
</script>
