<div class="howitworks-summary text-center">
    <div class="text-center">
        <h1 class="text-center">How Europe Online Services works</h1>
        <p class="mb-60">Europe Online Services <strong>enables</strong> you to transport European products to <strong>your address in Asia</strong>. With the use of our fully automatic <strong>platform</strong> and our asian partner <strong>SF Express</strong>, shopping in Europe has never been <strong>easier</strong>.  </p>

    </div>

    <div class="row col-12 mb-40 howitworks-summary-steps">

        <div class="col-4 col-lg-2 step">
            <h4 class="">Step 1</h4>
            <div class="step-circle">
                <img src="<?php echo $this->getViewFileUrl('images/howitworks/icon-step-1.svg'); ?>"  class="mb-10" />
            </div>


            <p class="mb-4">Sign-up for <br>free</p>
        </div>
        <div class="col-4 col-lg-2 step">
            <h4 class="">Step 2</h4>
            <div class="step-circle">
                <img src="<?php echo $this->getViewFileUrl('images/howitworks/icon-step-2.svg'); ?>"  class="mb-10" />
            </div>

            <p class="mb-4">Start shopping in Europe</p>
        </div>
        <div class="col-4 col-lg-2 step">
            <h4 class="">Step 3</h4>
            <div class="step-circle">
                <img src="<?php echo $this->getViewFileUrl('images/howitworks/icon-step-3.svg'); ?>"  class="mb-10" />
            </div>

            <p class="mb-4">Upload parcel <br>information</p>
        </div>
        <div class="col-4 col-lg-2 step">
            <h4 class="">Step 4</h4>
            <div class="step-circle step-circle-warehouse">
                <img src="<?php echo $this->getViewFileUrl('images/howitworks/icon-step-4.svg'); ?>"  class="mb-10" />
            </div>

            <p class="mb-4">We prepare the <br>transportation</p>
        </div>
        <div class="col-4 col-lg-2 step">

            <h4 class="">Step 5</h4>
            <div class="step-circle">
                <img src="<?php echo $this->getViewFileUrl('images/howitworks/icon-step-5.svg'); ?>"  class="mb-10" />
            </div>

            <p class="mb-4">Confirm and perform <br>payment</p>
        </div>
        <div class="col-4 col-lg-2 step">
            <h4 class="">Step 6</h4>
            <div class="step-circle">
                <img src="<?php echo $this->getViewFileUrl('images/howitworks/icon-step-6.png'); ?>"  class="mb-10" />
            </div>

            <p class="mb-4">Delivery to your <br>home</p>
        </div>
        <hr class="hr hr-top" />
        <hr class="hr hr-bottom d-block d-lg-none" />
    </div>

    <h3 style="font-weight:200;font-size:18px;" class="mb-20">Are you ready to experience the simplicity of parcel shipping from Europe to Asia?</h3>
    <a href="<?php echo $this->getUrl('customer/account/create'); ?>" class="btn btn-primary" style="width:250px;">Sign up for free</a>

</div>
