<div style="box-shadow: 0 0px 5px 3px rgba(0,0,0,0.1); background:#fafafa;" class="my-100">
    <div class="container py-100">
        <div class="row col-12">
            <div class="col-12 col-lg-5 mb-60 mb-lg-0 px-20 mt-lg-160 text-center">
                <img style="max-width:350px;" src='<?php echo $this->getViewFileUrl('images/pricing/pricing-benefits.png'); ?>' alt="">
            </div>
            <div class="col-12 col-lg-7 px-20">

                <div class="row col-12">
                    <div class="col-3 col-xs-4 col-sm-3 col-md-2 col-lg-2">
                        <img style="max-width: 80px;" class="mt-10 pr-4" src='<?php echo $this->getViewFileUrl('images/pricing/icon-custom-clearance.png'); ?>' alt="">
                    </div>
                    <div class="col-8 col-xs-8 col-sm-9 col-md-9 col-lg-10">
                        <h3>No surprising custom clearance costs</h3>
                        <p>Using our system, you will have comfort in receiving all the correct customs clearance documentation. Therefore you will not be surprised by any additional costs.</p>
                    </div>
                </div>
                <div class="row col-12">
                    <div class="col-3 col-xs-4 col-sm-3 col-md-2 col-lg-2">
                        <img style="max-width: 80px;" class="mt-10 pr-4" src='<?php echo $this->getViewFileUrl('images/pricing/icon-consolidation.png'); ?>' alt="">
                    </div>
                    <div class="col-8 col-xs-8 col-sm-9 col-md-9 col-lg-10">
                        <h3>Free consilidation and repackaging</h3>
                        <p>Automatic repacking and consolidation are included in our process. Reducing the parcel size is a great way to decrease the shipping costs and to avoid unexpected costs during delivery.</p>
                    </div>
                </div>
                <div class="row col-12">
                    <div class="col-3 col-xs-4 col-sm-3 col-md-2 col-lg-2">
                        <img style="max-width: 80px;" class="pr-4"  src='<?php echo $this->getViewFileUrl('images/pricing/icon-transportation.png'); ?>' alt="">
                    </div>
                    <div class="col-8 col-xs-8 col-sm-9 col-md-9 col-lg-10">
                        <h3>Fast air transportation</h3>
                        <p>All parcels are shipped by air so we can deliver your products fast and safely.</p>
                    </div>
                </div>
                <div class="row col-12">
                    <div class="col-3 col-xs-4 col-sm-3 col-md-2 col-lg-2">
                        <img style="max-width: 80px;" class="mt-10 pr-4" src='<?php echo $this->getViewFileUrl('images/pricing/icon-membership.png'); ?>' alt="">
                    </div>
                    <div class="col-8 col-xs-8 col-sm-9 col-md-9 col-lg-10">
                        <h3>Free membership</h3>
                        <p>As a customer, you don’t want to be tied to a costly subscription, therefore we offer free membership to all our customers so you can enjoy the simplicity of parcel shipping.</p>
                    </div>
                </div>
                <div class="row col-12">
                    <div class="col-3 col-xs-4 col-sm-3 col-md-2 col-lg-2">
                        <img style="max-width: 80px;" class="mt-10 pr-4" src='<?php echo $this->getViewFileUrl('images/pricing/icon-transparancy.png'); ?>' alt="">
                    </div>
                    <div class="col-8 col-xs-8 col-sm-9 col-md-9 col-lg-10">
                        <h3>Transparency in pricing and service</h3>
                        <p>We are completely transparent in our prices and services. As a customer, you want to know what to expect from the platform of Europe Online Services.</p>
                    </div>
                </div>
                <div class="row col-12">
                    <div class="col-3 col-xs-4 col-sm-3 col-md-2 col-lg-2">
                        <img style="max-width: 80px;" class="mt-10 pr-4" src='<?php echo $this->getViewFileUrl('images/pricing/icon-no-fuel-charge.png'); ?>' alt="">
                    </div>
                    <div class="col-8 col-xs-8 col-sm-9 col-md-9 col-lg-10">
                        <h3>No fuel charge</h3>
                        <p>Compared to other providers, Europe Online Services does not charge you for expensive transportation fuel fees.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<div  class="py-60">
    <div class="container step">
        <div class="row col-12 text-center">
            <h3 style="margin:auto; margin-bottom:20px;">Are you ready to start sending parcels from Europe to Asia?</h3>
            <p style="margin:0 auto;margin-bottom:25px;">Join us, and experience the simplicity of parcel transportation with Europe Online Services!</p>
            <p class="text-center" style="width: 100%;">
                <a href="<?php echo $this->getUrl('customer/account/create'); ?>" class="btn btn-primary text-center" style="width: 250px;">Sign up for free</a>
            </p>
        </div>
    </div>

</div>
