<h2 class="text-center">Pricing</h2>
<div class="row col-12">
    <div class="col-12 col-lg-6 mb-40 order-2 order-lg-1 px-lg-20">
        <div class="text-center">
            <img style="max-width:350px;margin-left:-20px;" src='<?php echo $this->getViewFileUrl('images/pricing/pricing-box.png'); ?>' alt="">
        </div>
        <hr class="d-block d-lg-none mb-40" style="border-color:#efefef;"/>
        <h3 class="d-block d-lg-none">Try it</h3>
        <form
            class="createOrderForm needs-validation" novalidate
            method="post"
            autocomplete="off"
            enctype="multipart/form-data">
            <p class="mb-10">Dimensions (cm)</p>
            <div class="row col-12">

                <div class="col-3 pr-6">
                    <input id="calc_length"
                           class="input-number"
                           type="number"
                           placeholder="Length"
                           onpaste="return false;"
                           ondrop="return false;"
                           autocomplete="off"
                    />
                </div>
                <div class="col-3 px-6">
                    <input id="calc_width"
                           class="input-number"
                           type="number"
                           placeholder="Width"
                           onpaste="return false;"
                           ondrop="return false;"
                           autocomplete="off"
                    />
                </div>
                <div class="col-3 pl-6">
                    <input id="calc_height"
                           class="input-number"
                           type="number"
                           placeholder="Height"
                           onpaste="return false;"
                           ondrop="return false;"
                           autocomplete="off"
                    />
                </div>
                <div class="col-3 pl-10">
                    <p style="font-size:12px; line-height:20px;">Results:<br> <strong class="calculator-weight">0.0 kg</strong></p>
                </div>
            </div>

            <div class="row">
                <div class="col-3 pr-6">
                    <p class="mb-10">Weight (kg)</p>
                    <input id="calc_weight"
                           class="input-number"
                           type="number"
                           placeholder="Weight"
                           onpaste="return false;"
                           ondrop="return false;"
                           autocomplete="off"
                    />
                </div>
                <div class="col-6 pl-20 pl-lg-60 calculator-result" style="padding-top:50px;">
                    <h3>&euro;0,00</h3>
                </div>

            </div>




        </form>

    </div>
    <div class="col-12 col-lg-6 mb-0 mb-lg-40 order-1 order-lg-2">
        <div class="text-center mt-40 mb-60 d-none d-lg-block">
            <img style="max-width:350px;" src='<?php echo $this->getViewFileUrl('images/pricing/pricing-scale.png'); ?>' alt="">
        </div>
        <p>At Europe Online Services you know where you pay for. Our shipping calculator estimates the <strong>best price</strong> for you based on your parcel specifications. The <strong>balance</strong> between weight (kg) and volumetric weight (size) determines your optimum shipping price.</p>
        <p>Our warehouse system automatically checks whether your parcel <strong>can be consolidated and repacked</strong>. This allows us to decrease the size and therefore is a great way to <strong>reduce the shipping costs for you</strong>.</p>
    </div>
    <div class="col-12 order-3 text-center">
        <p style="font-size:24px;" class="mb-20">Are you looking for the best price for shipping your parcels? </p>
        <button class="btn btn-primary" style="width:300px;">Start now</button>
    </div>

</div>
<script>

require(["jquery", "Eos_Base/js/bootstrap.bundle.min", 'Eos_Base/js/packageDetails', 'Eos_Base/node_modules/bootstrap4-toggle/js/bootstrap4-toggle.min'], function ($) {

    $('.input-number').on('keyup', function() {

        const length = parseInt($('#calc_length').attr('value'));
        const width = parseInt($('#calc_width').attr('value'));
        const height = parseInt($('#calc_height').attr('value'));
        const weight = parseFloat($('#calc_weight').attr('value'));

        const unitPrice = 2.7;

        const formula = ((length*width*height) / 5000);
        const priceFormula = 15 + formula * unitPrice;
        const priceWeight = 15 + (weight < 2 ? 2 : weight) * unitPrice;
        let price = "";

        console.log('price weight: ' + priceWeight)
        console.log('price forumula: ' + priceFormula)

/*        if( $('#calc_weight').attr('value').length < 1 ) {

        } else {
            $('.calculator-result').html('<h3>&euro;' + priceWeight.toFixed(2) + '</h3>');
            if (weight > formula) {

            }
        }*/

        if($(this).attr('id') === "calc_weight") {

            if($(this).attr("value").length < 1) {
                if( $('#calc_length').attr('value').length < 1 ||
                    $('#calc_width').attr('value').length < 1 ||
                    $('#calc_height').attr('value').length < 1) {

                    $('.calculator-result').html('<h3>&euro;0.00</h3>');

                } else {
                    // Do nothing
                }
            }
            if( ( $('#calc_length').attr('value').length < 1 ||
                $('#calc_width').attr('value').length < 1 ||
                $('#calc_height').attr('value').length < 1) || weight > formula) {
                price = weight > 2 ? priceWeight.toFixed(2) : 20.40;

                $('.calculator-result').html('<h3>&euro;' + price.toString() + '</h3>');
            } else {
                price = formula > 2 ? priceFormula.toFixed(2) : 20.40.toFixed(2);
                $('.calculator-result').html('<h3>&euro;' + price.toString() + '</h3>');
            }

        } else {
            if( $('#calc_length').attr('value').length < 1 ||
                $('#calc_width').attr('value').length < 1 ||
                $('#calc_height').attr('value').length < 1) {

                // Do nothing

            } else {
                $('.calculator-weight').html(formula.toFixed(1) + 'kg')

                if( $('#calc_weight').attr('value').length < 1 || formula > weight) {
                    price = formula > 2 ? priceFormula.toFixed(2) : 20.40.toFixed(2);
                    $('.calculator-result').html('<h3>&euro;' + price.toString() + '</h3>');
                } else {
                    price = weight > 2 ? priceWeight.toFixed(2) : 20.40.toFixed(2);
                    $('.calculator-result').html('<h3>&euro;' + price.toString() + '</h3>');
                }

            }
        }





    })
});
</script>
