<div class="container">
    <div class="row col-12">
        <div class="col-12 col-lg-6 px-20">
            <h3>Shipping rates</h3>
            <p>Do you want to experience the benefits of the <strong>best shipping rates and fastest parcel delivery by air</strong>? Select Europe Online Services and take <strong>advantage</strong> of our shipping rates and high quality services.</p>
            <p>At Europe Online Services we <strong>care</strong> about you. We make sure that our shipping rates are <strong>fully transparent</strong>. We take pride in providing you with parcel services that are <strong>simple, safe and affordable</strong>.</p>
            <p>Our innovative technology and partners allow us to keep the price of our beloved services <strong>lower</strong> than our competitors so you can <strong>benefit</strong> from this.</p>
        </div>
        <div class="col-12 col-lg-6 px-20">
            <table>
                <div class="orders-history">
                    <table class="data table table-order-items history" id="my-orders-table">
                        <caption class="table-caption">Hello</caption>
                        <thead>
                        <tr>
                            <th scope="col" class="col weight">Weight</th>
                            <th scope="col" class="col price">Price</th>

                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td class="col">2</td>
                            <td class="col">&euro;20,40</td>
                        </tr>
                        <tr>
                            <td class="col">2,5</td>
                            <td class="col">&euro;21,75</td>
                        </tr>
                        <tr>
                            <td class="col">3</td>
                            <td class="col">&euro;23,10</td>
                        </tr>
                        <tr>
                            <td class="col">3,5</td>
                            <td class="col">&euro;24,45</td>
                        </tr>
                        <tr>
                            <td class="col">4</td>
                            <td class="col">&euro;25,80</td>
                        </tr>
                        <tr>
                            <td class="col">4,5</td>
                            <td class="col">&euro;27,15</td>
                        </tr>
                        <tr>
                            <td class="col">5</td>
                            <td class="col">&euro;28,50</td>
                        </tr>
                        <tr>
                            <td class="col">10</td>
                            <td class="col">&euro;42,00</td>
                        </tr>
                        </tbody>
                    </table>
            </table>
        </div>
    </div>
</div>


