<?php
/**
 * @author Sunflowerbiz Team
 * @copyright Copyright (c) 2019 Sunflowerbiz (https://www.sunflowerbiz.com)
 * @package Sunflowerbiz_Base
 */
?>
<?php
/** @var \Sunflowerbiz\Base\Block\Adminhtml\Messages $block */
$extraJs = $block->getExtraJs();
?>
<script>
require(['jquery', 'mage/storage'],function(jQuery,storage){
   jQuery(document).ready(function(){ 
   		<?php echo $extraJs;?>
   });
});

</script>