<?php
/** @var \Magento\Framework\View\Element\Template $block */
/**@var Eos\Base\ViewModel\Orders $viewModel*/
$viewModel = $block->getData('view_model');

?>
<div class="table-wrapper orders-history parcelList parcelList-archive">
<?php $_items = $viewModel->getParcels($_GET); ?>
<input type="hidden" class="parcelList-archive-count" value="<?= count($_items)  ?>"/>
<?php if ($_items && count($_items)) : ?>

    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?= __('Orders') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col date"><?= __('ID') ?></th>
            <th scope="col" class="col date"><?= __('Date') ?></th>
            <th scope="col" class="col status"><?= __('Tracking Nr.') ?></th>
            <th scope="col" class="col status"><?= __('Weight') ?></th>
            <th scope="col" class="col status"><?= __('Length') ?></th>
            <th scope="col" class="col status"><?= __('Height') ?></th>
            <th scope="col" class="col status"><?= __('Width') ?></th>
            <th scope="col" class="col actions"><?= __('Action') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($_items as $_item) : ?>

            <tr>
                <td data-th="<?= __('ID') ?>" class="col date"><?= /* @noEscape */ $_item['entity_id'] ?></td>
                <td data-th="<?= __('Date') ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_item['created_at']) ?></td>
                <td data-th="<?= __('Tracking Nr.') ?>" class="col status"><?= /* @noEscape */ $_item['tracking_number'] ?></td>
                <td data-th="<?= __('Weight') ?>" class="col status"><?= /* @noEscape */ $_item['weight'] ?></td>
                <td data-th="<?= __('Length') ?>" class="col status"><?= /* @noEscape */ $_item['length'] ?></td>
                <td data-th="<?= __('Height') ?>" class="col status"><?= /* @noEscape */ $_item['height'] ?></td>
                <td data-th="<?= __('Width') ?>" class="col status"><?= /* @noEscape */ $_item['width'] ?></td>
                <td data-th="<?= __('Actions') ?>" class="col actions">
                    <!-- Button trigger modal -->
                    <button type="button" name="<?= $_item['entity_id'] . '_' . $_item['tracking_number'] ?>" class="btn btn-small btn-danger rounded btn-modal-delete" data-toggle="modal" data-target="#deleteParcel">
                        Delete
                    </button>

                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>



<?php else : ?>
<div class="message info empty"><span><?= $viewModel->getEmptyItemsMessage(); ?></span></div>
<?php endif ?>
</div>
<script>
    require(["jquery", "Eos_Base/js/bootstrap.bundle.min", 'Eos_Base/js/packageDetails','mage/url'], function ($, bootstrap,packageDetails,urlBuilder) {
        $('.btn-modal-delete').on("click", function () {
            $('.modal').remove();

            var item_id = $(this).attr('name').split('_')[0];
            var item_trackingNr = $(this).attr('name').split('_')[1];

            var myUrl = urlBuilder.build('wms/parcels/delete');

            var modal = '<div class="modal fade" id="deleteParcel" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">\n' +
                '    <div class="modal-dialog modal-dialog-centered" role="document">\n' +
                '        <div class="modal-content">\n' +
                '            <div class="modal-header">\n' +
                '                <h5 class="modal-title" id="exampleModalLongTitle">Parcel ID: ' + item_id + '</h5>\n' +
                '                <button type="button" class="close" data-dismiss="modal" aria-label="Close">\n' +
                '                    <span aria-hidden="true">&times;</span>\n' +
                '                </button>\n' +
                '            </div>\n' +
                '            <div class="modal-body">\n' +
                '                <p>Are you sure you want to remove: <strong>' + item_trackingNr + '</strong></p>' +
                '            </div>\n' +
                '            <div class="modal-footer">\n' +
                '                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>\n' +
                '                <a href="' + myUrl + '/tracking_number/' +item_trackingNr + '/entity_id/' + item_id + '" type="button" class="btn btn-primary">Save changes</a>\n' +
                '            </div>\n' +
                '        </div>\n' +
                '    </div>\n' +
                '</div>\n';

            $('body').append(modal);
        });
    });
</script>

