<?php
/** @var \Magento\Framework\View\Element\Template $block */
$parcelViewModel = $block->getData('parcel_view_model');

?>
<div class="table-wrapper orders-history parcelList parcelList-active-parcels parcelList-active">
    <?php $parcels = $parcelViewModel->getParcels()->getItems(); ?>
    <input type="hidden" class="parcelList-active-parcels-count" value="<?= count($parcels) ?>" />
    <?php if ($parcels && count($parcels)): ?>

        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption">
                <?= __('Orders') ?>
            </caption>
            <thead>
                <tr>
                    <th scope="col" class="col date">
                        <?= __('ID') ?>
                    </th>
                    <th scope="col" class="col date">
                        <?= __('Date') ?>
                    </th>
                    <th scope="col" class="col status">
                        <?= __('Tracking Nr.') ?>
                    </th>
                    <th scope="col" class="col status">
                        <?= __('Weight') ?>
                    </th>
                    <th scope="col" class="col status">
                        <?= __('Length') ?>
                    </th>
                    <th scope="col" class="col status">
                        <?= __('Height') ?>
                    </th>
                    <th scope="col" class="col status">
                        <?= __('Width') ?>
                    </th>
                    <th scope="col" class="col actions">
                        <?= __('Action') ?>
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($parcels as $parcel): ?>

                    <tr>
                        <td data-th="<?= __('ID') ?>" class="col date"><?= /* @noEscape */$parcel['entity_id'] ?></td>
                        <td data-th="<?= __('Date') ?>" class="col date"><?= /* @noEscape */$block->formatDate($parcel['created_at']) ?></td>
                        <td data-th="<?= __('Tracking Nr.') ?>" class="col status"><?= /* @noEscape */$parcel['tracking_number'] ?></td>
                        <td data-th="<?= __('Weight') ?>" class="col status"><?= /* @noEscape */$parcel['weight'] ?></td>
                        <td data-th="<?= __('Length') ?>" class="col status"><?= /* @noEscape */$parcel['length'] ?></td>
                        <td data-th="<?= __('Height') ?>" class="col status"><?= /* @noEscape */$parcel['height'] ?></td>
                        <td data-th="<?= __('Width') ?>" class="col status"><?= /* @noEscape */$parcel['width'] ?></td>
                        <td data-th="<?= __('Actions') ?>" class="col actions">
                            <!-- Button trigger modal -->
                            <button type="button" name="<?= $parcel['entity_id'] . '_' . $parcel['tracking_number'] ?>"
                                class="btn btn-small btn-danger rounded btn-modal-delete" data-toggle="modal"
                                data-target="#deleteParcel">
                                Delete
                            </button>

                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>



    <?php else: ?>
        <div class="message info empty"><span>
                <?= $parcelViewModel->getEmptyItemsMessage(); ?>
            </span></div>
    <?php endif ?>
    <a href="<?php echo $this->getUrl('wms/parcels/create'); ?>" class="btn btn-secondary my-20">
        <svg height="15" style="fill: white; margin:0 15px 0 -15px;" viewBox="0 0 448 448" width="15"
            xmlns="http://www.w3.org/2000/svg">
            <path
                d="m408 184h-136c-4.417969 0-8-3.582031-8-8v-136c0-22.089844-17.910156-40-40-40s-40 17.910156-40 40v136c0 4.417969-3.582031 8-8 8h-136c-22.089844 0-40 17.910156-40 40s17.910156 40 40 40h136c4.417969 0 8 3.582031 8 8v136c0 22.089844 17.910156 40 40 40s40-17.910156 40-40v-136c0-4.417969 3.582031-8 8-8h136c22.089844 0 40-17.910156 40-40s-17.910156-40-40-40zm0 0" />
        </svg>
        <span>
            <?= __('Add parcel') ?>
        </span>
    </a>
</div>
<script>
    require(["jquery", "Eos_Base/js/bootstrap.bundle.min", 'Eos_Base/js/packageDetails', 'mage/url'], function ($, bootstrap, packageDetails, urlBuilder) {
        $('.btn-modal-delete').on("click", function () {
            $('.modal').remove();

            var item_id = $(this).attr('name').split('_')[0];
            var item_trackingNr = $(this).attr('name').split('_')[1];

            var myUrl = urlBuilder.build('wms/parcels/delete');

            var modal = '<div class="modal fade" id="deleteParcel" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">\n' +
                '    <div class="modal-dialog modal-dialog-centered" role="document">\n' +
                '        <div class="modal-content">\n' +
                '            <div class="modal-header">\n' +
                '                <h5 class="modal-title" id="exampleModalLongTitle">Parcel ID: ' + item_id + '</h5>\n' +
                '                <button type="button" class="close" data-dismiss="modal" aria-label="Close">\n' +
                '                    <span aria-hidden="true">&times;</span>\n' +
                '                </button>\n' +
                '            </div>\n' +
                '            <div class="modal-body">\n' +
                '                <p>Are you sure you want to remove: <strong>' + item_trackingNr + '</strong></p>' +
                '            </div>\n' +
                '            <div class="modal-footer">\n' +
                '                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>\n' +
                '                <a href="' + myUrl + '/tracking_number/' + item_trackingNr + '/entity_id/' + item_id + '" type="button" class="btn btn-primary">Save changes</a>\n' +
                '            </div>\n' +
                '        </div>\n' +
                '    </div>\n' +
                '</div>\n';

            $('body').append(modal);
        });
    });
</script>