<header class="navbar navbar-top navbar-expand-lg navbar-eos">
    <div class="container">
        <a class="navbar-brand" href="/">
            <img width="90" src='<?php echo $this->getViewFileUrl('images/Eos_logo.svg'); ?>' alt="">
        </a>
        <a class="navbar-toggle" href="#navbar-mobile-style-2" data-fancybox="" data-base-class="fancybox-navbar" data-keyboard="false" data-auto-focus="false" data-touch="false" data-close-existing="true" data-small-btn="false" data-toolbar="false">
            <span></span>
            <span></span>
            <span></span>
        </a>
        <?php
        $ObjectManager= \Magento\Framework\App\ObjectManager::getInstance();
        $context = $ObjectManager->get('Magento\Framework\App\Http\Context');
        $isLoggedIn = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
        if ($isLoggedIn) {

        ?>

            <ul class="nav navbar-nav">
                <li class="nav-item">
                    <a href="<?php echo $this->getUrl('/'); ?>" class="nav-link">
                        <span class="nav-link-name">Home</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="<?php echo $this->getUrl('frontportal/howdoesitwork'); ?>" class="nav-link">
                        <span class="nav-link-name">How it works</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="<?php echo $this->getUrl('frontportal/Pricing'); ?>" class="nav-link">
                        <span class="nav-link-name">Pricing</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="<?php echo $this->getUrl('customer/account/logout'); ?>" class="nav-link">
                        <span class="nav-link-name"><?php echo __('Log out')?></span>
                    </a>
                </li>
                <li class="nav-item navbar-dropdown">
                    <a href="#" class="nav-link">
                        <span class="nav-link-name">Langdsuage</span>
                        <svg width="6" height="10" viewBox="0 0 6 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M1 9L5 5L1 1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                        </svg>
                    </a>
                    <div class="dropdown-menu">
                        <ul class="nav navbar-nav">
                            <li class="nav-item">
                                <a href="portfolio-col-1-style-1.html" class="nav-link">
                                    <span class="nav-link-name">English</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="portfolio-col-1-style-2.html" class="nav-link">
                                    <span class="nav-link-name">Chinese</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>

        <?php

        } else {

            ?>
            <ul class="nav navbar-nav">
                <li class="nav-item">
                    <a href="<?php echo $this->getUrl('/'); ?>" class="nav-link">
                        <span class="nav-link-name">Pricing</span>
                    </a>
                </li>" class="nav-link">
                        <span class="nav-link-name">home</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="<?php echo $this->getUrl('frontportal/howitworks'); ?>" class="nav-link">
                        <span class="nav-link-name">How it works</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="<?php echo $this->getUrl('frontportal/pricing'); ?>" class="nav-link">
                        <span class="nav-link-name">Pricing</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="<?php echo $this->getUrl('customer/account/login') ?>" class="nav-link">
                        <span class="nav-link-name">Login</span>
                    </a>
                </li>
                <li class="nav-item navbar-dropdown">
                    <a href="#" class="nav-link">
                        <span class="nav-link-name">Language</span>
                        <svg width="6" height="10" viewBox="0 0 6 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M1 9L5 5L1 1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                        </svg>
                    </a>
                    <div class="dropdown-menu">
                        <ul class="nav navbar-nav">
                            <li class="nav-item">
                                <a href="portfolio-col-1-style-1.html" class="nav-link">
                                    <span class="nav-link-name">English</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="portfolio-col-1-style-2.html" class="nav-link">
                                    <span class="nav-link-name">Chinese</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>


        <?php

        }

        ?>
        <ul class="nav nav-gap-sm navbar-nav nav-social align-items-center">
            <li class="nav-item">
                <a href="#" class="nav-link">
                </a>
            </li>
        </ul>
    </div>
</header>


<div class="navbar navbar-mobile navbar-mobile-style-2" id="navbar-mobile-style-2">
    <div class="shape justify-content-end">
        <svg data-rellax-speed="0" width="544" height="362" viewBox="0 0 544 362" fill="none" xmlns="http://www.w3.org/2000/svg" style="transform: translate3d(0px, 0px, 0px);">
            <circle cx="320.5" cy="41.5" r="320.5" fill="#ececec"></circle>
        </svg>
    </div>
    <div class="navbar-head">
        <div class="container">
            <a class="navbar-brand" href="home.html">
                <img width="107" src="assets/images/Eos_logo.png" alt="">
            </a>
            <a class="navbar-toggle" href="#" data-fancybox-close="">
                <span></span>
                <span></span>
                <span></span>
            </a>
        </div>
    </div>
    <div class="container">
        <div class="row gh-1 justify-content-center">
            <div class="col-12 col-md-7 col-lg-5 col-xl-4">
                <div class="navbar-body">
                    <ul class="nav navbar-nav navbar-nav-collapse">
                        <li class="nav-item">
                            <a href="/" class="nav-link">
                                <span class="nav-link-name">Home</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<?php echo $this->getUrl('frontportal/howdoesitwork'); ?>" class="nav-link">
                                <span class="nav-link-name">How it works</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<?php echo $this->getUrl('frontportal/pricing'); ?>" class="nav-link">
                                <span class="nav-link-name">Pricing</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<?php echo $this->getUrl('customer/account/login'); ?>" class="nav-link">
                                <span class="nav-link-name">Login</span>
                            </a>
                        </li>
                        <li class="nav-item navbar-collapse">
                            <a href="#navbarCollapseLanguage" class="nav-link collapsed" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="navbarCollapseLanguage">
                                <span class="nav-link-name">Language</span>
                                <svg class="collapse-icon" width="7" height="12" viewBox="0 0 7 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M1 11L6 6L1 1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                </svg>
                            </a>
                            <div class="navbar-collapse-menu collapse" id="navbarCollapseLanguage">
                                <ul class="nav navbar-nav">
                                    <li class="nav-item">
                                        <a href="portfolio-col-1-style-1.html" class="nav-link">
                                            <span class="nav-link-name">English</span>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="portfolio-col-1-style-2.html" class="nav-link">
                                            <span class="nav-link-name">Chinese</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-1 d-none d-md-block"></div>
            <div class="col-12 col-md-4 col-lg-4 col-xl-3">
                <div class="navbar-footer">
                    <div class="mb-60">
                        <p class="lead mb-17 font-weight-medium">Contact info:</p>
                        <ul class="list-group borderless font-size-17">
                            <li class="list-group-item">Email: <a href="#">info@europeonlineservices.com</a></li>
                            <li class="list-group-item">Phone: <a href="#">+31 6 12 34 56 78</a></li>
                        </ul>
                    </div>
                    <div class="mb-60">
                        <p class="lead mb-17 font-weight-medium">Warehouse NL Address:</p>
                        <ul class="list-group borderless font-size-17">
                            <li class="list-group-item">Delftweg 71</li>
                            <li class="list-group-item">2289 BA Rijswijk</li>
                            <li class="list-group-item">The Netherlands</li>
                        </ul>
                    </div>
                    <div class="mb-60">
                        <p class="lead mb-17 font-weight-medium">Warehouse DE Address:</p>
                        <ul class="list-group borderless font-size-17">
                            <li class="list-group-item">Andreas-Meyer-Str 45-47</li>
                            <li class="list-group-item">22113 Hamburg</li>
                            <li class="list-group-item">Germany</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
