<div class="col-12 col-lg-4 mb-60">
    <ul class="nav flex-column text-white">
        <li class="nav-item mb-20"><a class="text-white h4" href="<?php echo $this->getUrl('frontportal/contact'); ?>">Contact</a></li>
        <li class="nav-item"><a class="nav-link" href="mailto:info@europeonlineservices.com">info@europeonlineservices.com</a></li>
        <li class="nav-item">
            <p class="">Dennenlaan 9<br>5271 RE Sint-Michielsgestel<br>The Netherlands</p>
        </li>
    </ul>
</div>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-32TBWY4MKT"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-32TBWY4MKT');
</script>
