<div class="shape align-items-end justify-content-end">&nbsp;</div>
<div class="shape shape-footer">&nbsp;</div>
<div class="col-12 col-lg-4 mb-60">
    <ul class="nav flex-column text-white">
        <li class="nav-item mb-20"><a class="text-white h4" href="#">Europe Online Services</a></li>
        <li class="nav-item"><a class="nav-link" href="<?php echo $this->getUrl('frontportal/aboutus'); ?>">About us</a></li>
        <li class="nav-item"><a class="nav-link" href="<?php echo $this->getUrl('frontportal/contact'); ?>#faq">FAQ</a></li>
        <li class="nav-item"><a class="nav-link" href="<?php echo $this->getUrl('privacy-policy-cookie-restriction-mode'); ?>">Privacy</a></li>
        <li class="nav-item"><a class="nav-link" href="<?php echo $this->getUrl('general-terms-and-conditions'); ?>">Terms &amp; Conditions</a></li>
        <li class="nav-item"><a class="nav-link" href="<?php echo $this->getUrl('frontportal/contact'); ?>">Contact us</a></li>
    </ul>
</div>
