<div class="shape align-items-end justify-content-end">
    <svg style="top:-50px;right:-20px;" data-rellax-speed="-1" class="mb-n130" width="300" height="300" viewBox="0 0 525 641" fill="none" xmlns="http://www.w3.org/2000/svg">
        <circle cx="320.5" cy="320.5" r="320.5" fill="#4FA5B5" />
    </svg>
    <svg style="top:150px;right:-60px;" data-rellax-speed="-1" class="mb-n130" width="175" height="175" viewBox="0 0 525 641" fill="none" xmlns="http://www.w3.org/2000/svg">
        <circle cx="320.5" cy="320.5" r="320.5" fill="#4FA5B5" />
    </svg>
</div>
<div class="shape shape-footer">
    <svg style="top:-50px;left:-20px;" data-rellax-speed="-1" class="mb-n130" width="800" height="800" viewBox="0 0 525 641" fill="none" xmlns="http://www.w3.org/2000/svg">
        <circle cx="100.5" cy="320.5" r="320.5" fill="#4FA5B5" />
    </svg>
    <svg style="left:150px;bottom:-200px;" data-rellax-speed="-1" class="mb-n130" width="500" height="500" viewBox="0 0 525 641" fill="none" xmlns="http://www.w3.org/2000/svg">
        <circle cx="260.5" cy="320.5" r="320.5" fill="#4FA5B5" />
    </svg>
</div>
