<?php
/** @var \Magento\Framework\View\Element\Template $block */
/**@var Eos\Base\ViewModel\Orders $viewModel*/
$viewModel = $block->getData('view_model');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey');

$order = $viewModel->getOrder($block->getRequest()->getParam('order_id'));
$orderDetails = $viewModel->getOrderDetailsWithHs($block->getRequest()->getParam('order_id'));
$parcels = $viewModel->getParcels($order['webshop_tracking_number']);
$shipment = $viewModel->getShipments(null, $order['shipment_id']);

?>

<h1><?= __('Order information'); ?></h1>
<a href="<?php echo $this->getUrl('wms/orders/index'); ?>" class="btn btn-back" >
    <div class="button-arrow-container">
        <div class='button-arrow' >
            <span style=""><?= __('Go back'); ?></span>
        </div>
    </div>
</a>

<div class="container mb-40" style="max-width:100%;">
    <div class="row">
        <div class="col">
           <h3>Shipment Information</h3>
        </div>
        <div class="col">
            <h3>General Order Information</h3>
        </div>
    </div>
    <div class="row">
        <div class="col pr-6">

            <div class="table-wrapper orders-history">
                <table class="data table table-order-items history" id="my-orders-table">
                    <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
                    <thead>
                    <tr>
                        <th scope="col" class="col date"><?= __('Shipment Code') ?></th>
                        <th scope="col" class="col webshop"><?= (isset($shipment['f_shipment_id']) ? $shipment['f_shipment_id'] : "") ?></th>

                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="col">Status</td>
                        <td class="col"><?= (isset($shipment['status']) ? $shipment['status'] : "") ?></td>
                    </tr>
                    <tr>
                        <td class="col">awb_code</td>
                        <td class="col"><?= (isset($shipment['awb_code']) ? $shipment['awb_code'] : "") ?></td>
                    </tr>
                    <tr>
                        <td class="col">originCode</td>
                        <td class="col"><?= (isset($shipment['originCode']) ? $shipment['originCode'] : "") ?></td>
                    </tr>
                    <tr>
                        <td class="col">DestCode</td>
                        <td class="col"><?= (isset($shipment['destCode']) ? $shipment['destCode'] : "") ?></td>
                    </tr>
                    <tr>
                        <td class="col">printUrl</td>
                        <td class="col"><?= (isset($shipment['awb_code']) ? $shipment['printUrl'] : "") ?></td>
                    </tr>
                    <tr>
                        <td class="col">invoiceUrl</td>
                        <td class="col"><?= (isset($shipment['invoiceUrl']) ? $shipment['invoiceUrl'] : "") ?></td>
                    </tr>
                    <tr>
                        <td class="col">Date Created</td>
                        <td class="col"><?= (isset($shipment['created_at']) ? $shipment['created_at'] : "") ?></td>
                    </tr>
                    <tr>
                        <td class="col">Last updated</td>
                        <td class="col"><?= (isset($shipment['updated_at']) ? $shipment['updated_at'] : "") ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col pl-6">
            <div class="table-wrapper orders-history">
                <table class="data table table-order-items history" id="my-orders-table">
                    <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
                    <thead>
                    <tr>
                        <th scope="col" class="col date"><?= __('Inbound Tracking Nr.') ?></th>
                        <th scope="col" class="col webshop"><?= $order['webshop_tracking_number'] ?></th>

                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="col">Status</td>
                        <td class="col"><?= $order['status'] ?></td>
                    </tr>
                    <tr>
                        <td class="col">Webhop - Title</td>
                        <td class="col"><?= $order['webshop_title'] ?></td>
                    </tr>
                    <tr>
                        <td class="col">Webhop - Invoice Nr.</td>
                        <td class="col"><?= $order['webshop_order_nr'] ?></td>
                    </tr>

                    <tr>
                        <td class="col">Date Created</td>
                        <td class="col"><?= $order['created_at'] ?></td>
                    </tr>
                    <tr>
                        <td class="col">Last updated</td>
                        <td class="col"><?= $order['updated_at'] ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="mb-40">
    <h3>Order Details</h3>
    <form class="form form-table">
        <div class="table-wrapper orders-history">
            <table class="data table table-order-items history" id="my-orders-table">
                <caption class="table-caption"><?= __('Orders') ?></caption>
                <thead>
                <tr>
                    <th scope="col" class="col status"><?= __('Product tax nr.') ?></th>
                    <th scope="col" class="col status"><?= __('HS Code') ?></th>
                    <th scope="col" class="col status"><?= __('Product Description') ?></th>
                    <th scope="col" class="col status"><?= __('Price gross') ?></th>
                    <th scope="col" class="col status"><?= __('Price net') ?></th>
                    <th scope="col" class="col status"><?= __('Amount') ?></th>
                    <th scope="col" class="col status" style="min-width:200px;"><?= __('Action') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($orderDetails as $orderDetail) : ?>

                    <tr>
                        <td style="display:none;"><input name="entity_id" value="<?= $orderDetail['entity_id'] ?>" placeholder="<?= $orderDetail['entity_id'] ?>" /></td>
                        <td data-th="<?= __('Product Tax Nr') ?>" class="col status"><input class="input-text" name="product_tax_nr" value="<?= $orderDetail['product_tax_nr'] ?>" placeholder="<?= $orderDetail['product_tax_nr'] ?>" disabled/></td>
                        <td data-th="<?= __('HS Code') ?>" class="col status"><input class="input-text" name="product_tax_nr" value="<?= $orderDetail['hs_code'] ?>" placeholder="<?= $orderDetail['hs_code'] ?>" disabled /></td>
                        <td data-th="<?= __('HS Code') ?>" class="col status"><input class="input-text" name="product_tax_nr" value="<?= $orderDetail['product_title'] ?>" placeholder="<?= $orderDetail['product_title'] ?>" disabled /></td>
                        <td data-th="<?= __('Price Gross') ?>" class="col status"><input class="input-text" name="product_tax_nr" value="<?= $orderDetail['product_price_gross'] ?>" placeholder="<?= $orderDetail['product_price_gross'] ?>" disabled /></td>
                        <td data-th="<?= __('Price Net') ?>" class="col status"><input class="input-text" name="product_tax_nr" value="<?= $orderDetail['product_price_net'] ?>" placeholder="<?= $orderDetail['product_price_net'] ?>" disabled /></td>
                        <td data-th="<?= __('Order Status') ?>" class="col status"><input class="input-text" name="product_tax_nr" value="<?= $orderDetail['product_amount'] ?>" placeholder="<?= $orderDetail['product_amount'] ?>" disabled /></td>
                        <td data-th="<?= __('Order Status') ?>" class="col status"><button class="btn-edit btn-tertiary">Edit</button><button class="btn-remove btn-danger btn-small ml-10">Remove</button><button class="btn-save btn-secondary">Save</button><button class="btn-discard btn-tertiary ml-10">Discard</button></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </form>
</div>


<h3>Parcel Information</h3>

<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?= __('Orders') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col status"><?= __('Tracking Nr.') ?></th>
            <th scope="col" class="col status"><?= __('Weight') ?></th>
            <th scope="col" class="col status"><?= __('Width') ?></th>
            <th scope="col" class="col status"><?= __('Length') ?></th>
            <th scope="col" class="col status"><?= __('Height') ?></th>
            <th scope="col" class="col status"><?= __('Created At') ?></th>

        </tr>
        </thead>
        <tbody>
        <?php foreach ($parcels as $parcel) : ?>

            <tr>
                <td data-th="<?= __('Tracking Nr.') ?>" class="col status"><?= /* @noEscape */ $parcel['tracking_number'] ?></td>
                <td data-th="<?= __('Weight') ?>" class="col status"><?= /* @noEscape */ $parcel['weight'] ?></td>
                <td data-th="<?= __('Width') ?>" class="col status"><?= $parcel['width'] ?></td>
                <td data-th="<?= __('Length') ?>" class="col status"><?= $parcel['length'];  ?></td>
                <td data-th="<?= __('Height') ?>" class="col status"><?= /* @noEscape */ $parcel['height'] ?></td>
                <td data-th="<?= __('Created at') ?>" class="col status"><?= /* @noEscape */ $parcel['created_at'] ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<script>
    require(["jquery", "Eos_Base/js/bootstrap.bundle.min"], function ($, bootstrap) {

        $('.btn-edit').on('click', function (e) {
            e.preventDefault();
            $(this).closest('tr').find('input').attr('disabled', false).addClass('input-active');
            $(this).hide();
            $(this).parent().find('.btn-danger').hide();
            $(this).parent().find('.btn-save').css('display', 'inline-block');
            $(this).parent().find('.btn-discard').css('display', 'inline-block');

        });

        $('.btn-discard').on('click', function (e) {
            e.preventDefault();
            $(this).closest('.form').find('input').attr('disabled', true).removeClass('input-active');
            $(this).hide();
            $(this).parent().find('.btn-save').hide();
            $(this).parent().find('.btn-danger').css('display', 'inline-block');
            $(this).parent().find('.btn-edit').css('display', 'inline-block');

            $(this).closest('tr').find('input').each(function() {
                $(this).attr('value', $(this).attr('placeholder'));
            });

        });

    });


</script>
<!-- Modal -->
