<?php
/** @var \Magento\Framework\View\Element\Template $block */
/**@var Eos\Base\ViewModel\Orders $viewModel*/
$viewModel = $block->getData('view_model');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey');

$order = $viewModel->getOrder($block->getRequest()->getParam('order_id'));
$orderDetails = $viewModel->getOrderDetailsWithHs($block->getRequest()->getParam('order_id'));
$parcels = $viewModel->getParcels($order['webshop_tracking_number']);
$shipment = $viewModel->getShipments(null, $order['shipment_id']);

?>

<h1><?= __('Order information'); ?></h1>
<a href="<?php echo $this->getUrl('wms/orders/index'); ?>" class="btn btn-back" >
    <div class="button-arrow-container">
        <div class='button-arrow' >
            <span style=""><?= __('Go back'); ?></span>
        </div>
    </div>
</a>

<div class="container mb-40" style="max-width:100%;">
    <div class="row">
        <div class="col">
           <h3>Shipment Information</h3>
        </div>
        <div class="col">
            <h3>General Order Information</h3>
        </div>
    </div>
    <div class="row">
        <div class="col pr-6">

            <div class="table-wrapper orders-history">
                <table class="data table table-order-items history" id="my-orders-table">
                    <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
                    <thead>
                    <tr>
                        <th scope="col" class="col date"><?= __('Shipment Code') ?></th>
                        <th scope="col" class="col webshop"><?= (isset($shipment['f_shipment_id']) ? $shipment['f_shipment_id'] : "") ?></th>

                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="col">Status</td>
                        <td class="col"><?= (isset($shipment['status']) ? $shipment['status'] : "") ?></td>
                    </tr>
                    <tr>
                        <td class="col">awb_code</td>
                        <td class="col"><?= (isset($shipment['awb_code']) ? $shipment['awb_code'] : "") ?></td>
                    </tr>
                    <tr>
                        <td class="col">originCode</td>
                        <td class="col"><?= (isset($shipment['originCode']) ? $shipment['originCode'] : "") ?></td>
                    </tr>
                    <tr>
                        <td class="col">DestCode</td>
                        <td class="col"><?= (isset($shipment['destCode']) ? $shipment['destCode'] : "") ?></td>
                    </tr>
                    <tr>
                        <td class="col">printUrl</td>
                        <td class="col"><?= (isset($shipment['awb_code']) ? $shipment['printUrl'] : "") ?></td>
                    </tr>
                    <tr>
                        <td class="col">invoiceUrl</td>
                        <td class="col"><?= (isset($shipment['invoiceUrl']) ? $shipment['invoiceUrl'] : "") ?></td>
                    </tr>
                    <tr>
                        <td class="col">Date Created</td>
                        <td class="col"><?= (isset($shipment['created_at']) ? $shipment['created_at'] : "") ?></td>
                    </tr>
                    <tr>
                        <td class="col">Last updated</td>
                        <td class="col"><?= (isset($shipment['updated_at']) ? $shipment['updated_at'] : "") ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col pl-6">
            <div class="table-wrapper orders-history">
                <table class="data table table-order-items history" id="my-orders-table">
                    <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
                    <thead>
                    <tr>
                        <th scope="col" class="col date"><?= __('Inbound Tracking Nr.') ?></th>
                        <th scope="col" class="col webshop"><?= $order['webshop_tracking_number'] ?></th>

                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="col">Status</td>
                        <td class="col"><?= $order['status'] ?></td>
                    </tr>
                    <tr>
                        <td class="col">Webhop - Title</td>
                        <td class="col"><?= $order['webshop_title'] ?></td>
                    </tr>
                    <tr>
                        <td class="col">Webhop - Invoice Nr.</td>
                        <td class="col"><?= $order['webshop_order_nr'] ?></td>
                    </tr>

                    <tr>
                        <td class="col">Date Created</td>
                        <td class="col"><?= $order['created_at'] ?></td>
                    </tr>
                    <tr>
                        <td class="col">Last updated</td>
                        <td class="col"><?= $order['updated_at'] ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="mb-40">
    <h3>Order Details</h3>

    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= __('Orders') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col status"><?= __('Product tax nr.') ?></th>
                <th scope="col" class="col status"><?= __('HS Code') ?></th>
                <th scope="col" class="col status"><?= __('Product Description') ?></th>
                <th scope="col" class="col status"><?= __('Price gross') ?></th>
                <th scope="col" class="col status"><?= __('Price net') ?></th>
                <th scope="col" class="col status"><?= __('Amount') ?></th>

            </tr>
            </thead>
            <tbody>
            <?php foreach ($orderDetails as $orderDetail) : ?>

                <tr>
                    <td data-th="<?= __('Product Tax Nr') ?>" class="col status"><?= /* @noEscape */ $orderDetail['product_tax_nr'] ?></td>
                    <td data-th="<?= __('HS Code') ?>" class="col status"><?= /* @noEscape */ $orderDetail['hs_code'] ?></td>
                    <td data-th="<?= __('HS Code') ?>" class="col status"><?= $orderDetail['category_title'] . ' : ' . $orderDetail['subcategory_title'] . ' : ' . $orderDetail['product_title'] ?></td>
                    <td data-th="<?= __('Price Gross') ?>" class="col status"><?= $orderDetail['product_price_gross'];  ?></td>
                    <td data-th="<?= __('Price Net') ?>" class="col status"><?= $orderDetail['product_price_net'];  ?></td>
                    <td data-th="<?= __('Order Status') ?>" class="col status"><?= /* @noEscape */ $orderDetail['product_amount'] ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>


<h3>Parcel Information</h3>

<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?= __('Orders') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col status"><?= __('Tracking Nr.') ?></th>
            <th scope="col" class="col status"><?= __('Weight') ?></th>
            <th scope="col" class="col status"><?= __('Width') ?></th>
            <th scope="col" class="col status"><?= __('Length') ?></th>
            <th scope="col" class="col status"><?= __('Height') ?></th>
            <th scope="col" class="col status"><?= __('Created At') ?></th>

        </tr>
        </thead>
        <tbody>
        <?php foreach ($parcels as $parcel) : ?>

            <tr>
                <td data-th="<?= __('Tracking Nr.') ?>" class="col status"><?= /* @noEscape */ $parcel['tracking_number'] ?></td>
                <td data-th="<?= __('Weight') ?>" class="col status"><?= /* @noEscape */ $parcel['weight'] ?></td>
                <td data-th="<?= __('Width') ?>" class="col status"><?= $parcel['width'] ?></td>
                <td data-th="<?= __('Length') ?>" class="col status"><?= $parcel['length'];  ?></td>
                <td data-th="<?= __('Height') ?>" class="col status"><?= /* @noEscape */ $parcel['height'] ?></td>
                <td data-th="<?= __('Created at') ?>" class="col status"><?= /* @noEscape */ $parcel['created_at'] ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
