<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<div class="login-container">
    <div class="block">
        <div class="block-title">
            <strong id="" role="heading"><?= $block->escapeHtml(__('Forgot password')) ?></strong>
        </div>
        <form class="form password forget createOrderForm"
              action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
              method="post"
              id="form-validate"
              data-mage-init='{"validation":{}}'>

            <fieldset class="fieldset mb-0" data-hasrequired="">
                <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
                <div class="field email required">
                    <div class="control">
                        <input placeholder="E-mailaddress" type="email" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>

            <div class="field">
                <div class="control mb-10">
                    <button type="submit" class="btn btn-full btn-secondary btn-submit"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
                </div>
                <div class="control">
                    <a class="btn btn-full btn-tertiary" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
                </div>
            </div>
            </fieldset>
        </form>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate"
            }
        }
    }
</script>
