<?php
/** @var \Magento\Framework\View\Element\Template $block */
$viewModel = $block->getData('view_model');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey');
$webshop_tracking_number = $block->getRequest()->getParam('webshop_tracking_number');
?>

<h1>
    <?= __('Add Parcel'); ?>
</h1>
<a href="<?php echo $this->getUrl('wms/orders/index'); ?>" class="btn btn-back">
    <div class="button-arrow-container">
        <div class='button-arrow'>
            <span style="">
                <?= __('Go back'); ?>
            </span>
        </div>
    </div>
</a>


<form class="form createOrderForm" method="post"
    action="<?php echo $block->getBaseUrl() . 'wms/parceltemplates/save'; ?>">
    <input name="form_key" type="hidden" value="<?php echo $FormKey->getFormKey(); ?>">
    <input type="hidden" name="redirect" value="wms/parcels" />


    <div class="row col-12 my-20">

        <div class="row col-12 col-lg-6 dimensions">
            <input class="input-text" name="title" type="text" placeholder="Template Title">
            <div class="col-4 pr-6">
                <input id="width_placeholder" class="input-text" name="width" type="number" placeholder="Width (cm)">
            </div>
            <div class="col-4 px-6">
                <input id="height_placeholder" class="input-text" name="height" type="number" placeholder="Height (cm)">
            </div>
            <div class="col-4 px-6">
                <input id="length_placeholder" class="input-text" name="length" type="number" placeholder="Length (cm)">
            </div>

        </div>
    </div>
    <input class="btn btn-primary mt-10" type="submit" value="Submit" placeholder="Webshop Name">
</form>