<?php
/** @var \Magento\Framework\View\Element\Template $block */
/**@var Eos\Base\ViewModel\Orders $viewModel*/
$viewModel = $block->getData('view_model');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$customer = $viewModel->getCustomer();
$address = $viewModel->getCustomerAddress();
$bytes = random_bytes(3);

    ?>

    <div class="container mb-40 general-info">
        <div class="row col-12">
            <div class="col-6 pr-lg-10 account-information">
                <div class="card px-10 pt-5" style="height:310px">
                    <div class="card-body">
                        <h5>Account Information</h5>

                        <div class="row col-12 mb-60">
                            <div class="col-12 col-lg-6">
                                <p class="mb-0"><strong>Personal information</strong></p>
                                <p>
                                    <?= $customer->getName(); ?><br/>
                                    <?= $customer->getEmail(); ?><br/>
                                    <?= $address->getData('telephone') ; ?>
                                </p>
                                <p class="mb-0"><strong>Personal Member ID</strong></p>
                                <p>#<?= bin2hex($bytes) ?></p>
                            </div>
                            <div class="col-12 col-lg-6">
                                <p class="mb-0"><strong>My shipping address</strong></p>
                                <p>
                                    <?= $address->getData('street') ; ?><br/>
                                    <?= $address->getData('city') ; ?> , <?= $address->getData('region') ; ?> , <?= $address->getData('country_id') ; ?><br/>
                                    <?= $address->getData('postcode'); ?><br/>
                                </p>

                            </div>
                        </div>
                        <div class="row">
                            <div class="text-center col-12">
                                <p><a href="#" class="btn btn-primary btn-small px-40" style="font-size:10px;">Edit</a></p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="col-6 pl-lg-10 shipping-instructions">
                <div class="card px-10 pt-5" style="height:310px">
                    <div class="card-body">
                        <h5>Shipping instructions</h5>
                        <p><strong>What to do when sending an order form a European webshop to our warehouse?</strong></p>
                        <p>1. Always mention your personal customer ID behind your name when sending a parcel. In your case: <strong>Gijs Ankone #<?= bin2hex($bytes) ?></strong></p>
                        <p class="mb-20">2. Ship the parcel to one of our warehouses. Click on your prefered warehouse location to reveal the address.</p>

                        <div class="text-center">
                            <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist" style="display: inline-flex">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true"
                                            style="border-top-left-radius: 4px;border-bottom-left-radius: 4px;">The Netherlands</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false"
                                            style="border-top-right-radius: 4px;border-bottom-right-radius: 4px;padding:2px 40px;">Germany</button>
                                </li>

                            </ul>
                            <div class="tab-content" id="pills-tabContent">
                                <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                                    <p>
                                        Delftweg 71 , 2289 BA Rijswijk
                                    </p>
                                </div>
                                <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                                    <p>
                                        Andreas-Meyer-Str 45-47 , 22113 Hamburg
                                    </p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>


<script>

    require(["jquery", "Eos_Base/js/bootstrap.bundle.min"], function ($) {


        $('.nav-link').on('click' , function() {
            if(!$(this).hasClass('active')) {
                $('.nav-link').removeClass('active');
                $(this).addClass('active');
                $('.tab-pane').removeClass('show active');
                $($(this).attr('data-bs-target')).addClass('show active');
            }

        });
    });
</script>
