<?php
/** @var \Magento\Framework\View\Element\Template $block */
$fullUrl = $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);

?>

<div class="item <?= (strpos($fullUrl, 'wms/index') !== false ? "item-active" : "" ) ?> col-12 p-10">
    <a href="<?php echo $this->getUrl('wms/index'); ?>" class="p-20" style="display: contents">
        <div class="p-10">
            <span>Home</span>
        </div>
    </a>
</div>
<div class="item <?= (strpos($fullUrl, 'wms/orders') !== false ? "item-active" : "" ) ?> col-12 p-10">
    <a href="<?php echo $this->getUrl('wms/orders'); ?>" class="p-20" style="display: contents">
        <div class="p-10">
            <span>Orders</span>
        </div>
    </a>
</div>
<div class="item <?= (strpos($fullUrl, 'wms/parcels') !== false ? "item-active" : "" ) ?> col-12 p-10">
    <a href="<?php echo $this->getUrl('wms/parcels'); ?>" class="p-20" style="display: contents">
        <div class="p-10">
            <span>Parcels</span>
        </div>
    </a>
</div>
<div class="item <?= (strpos($fullUrl, 'wms/batches') !== false ? "item-active" : "" ) ?> col-12 p-10">
    <a href="<?php echo $this->getUrl('wms/batches'); ?>" class="p-20" style="display: contents">
        <div class="p-10">
            <span>Batches</span>
        </div>
    </a>
</div>
<div class="item col-12 p-10">
    <a href="<?php echo $this->getUrl('customer/account/logout'); ?>" class="p-20" style="display: contents">
        <div class="p-10">
            <span>Log-out</span>
        </div>
    </a>
</div>
