<?php
/** @var \Magento\Framework\View\Element\Template $block */
/**@var Eos\Base\ViewModel\Batches $viewModel*/
$viewModel = $block->getData('view_model');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey');
$batchId = $block->getRequest()->getParam('batch_id');

$batch = $viewModel->getBatches($batchId);

?>

<h1><?= __('Edit batch'); ?></h1>
<a href="<?php echo $this->getUrl('wms/batches'); ?>" class="btn btn-back" >
    <div class="button-arrow-container">
        <div class='button-arrow' >
            <span style=""><?= __('Go back'); ?></span>
        </div>
    </div>
</a>


<form class="form createOrderForm"
      method="post"
      action="<?php echo $block->getBaseUrl() . 'wms/batch/save'; ?>"
>
    <input name="form_key" type="hidden" value="<?php echo $FormKey->getFormKey();?>">
    <input name="batch_id" type="hidden" value="<?php echo $batchId; ?>">
    <input type="hidden" name="redirect" value="wms/warehouse/editbatch/batch_id/<?php echo $batchId; ?>" />

    <div class="row col-12 my-20">
        <div class="col-6 pr-10" >
            <div class="col-12 dropdown">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <input id="warehouse_placeholder" class="dropdown-placeholder input-text" name="warehouse_placeholder" value="<?php echo $viewModel->getWarehouses($batch['warehouse_id'])['title'];?>" type="text" placeholder="Warehouse" onpaste="return false;" ondrop="return false;" autocomplete="off">
                </a>

                <div class="dropdown-menu menu-warehouse" aria-labelledby="dropdownMenuLink">
                    <?php $_warehouses = $viewModel->getWarehouses();?>
                    <?php

                    foreach ($_warehouses as $warehouse) {
                        echo '<a class="dropdown-item" href="#" name="warehouse_' . $warehouse['entity_id'] . '">' . $warehouse['title'] . '</a>';
                    }
                    ?>


                </div>
            </div>
            <div class="col-12">
                <input class="input-text" name="vehicle_tag" type="text" placeholder="Vehicle tag" value="<?= $batch['vehicle_tag']; ?>">

            </div>
            <div class="col-12 dropdown">

                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <input id="status_placeholder" class="dropdown-placeholder input-text" name="status_placeholder" type="text" value="<?= $batch['status']; ?>" placeholder="Status" onpaste="return false;" ondrop="return false;" autocomplete="off">
                </a>

                <div class="dropdown-menu menu-status" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="#" name="status_newEntry">New Entry</a>
                    <a class="dropdown-item" href="#" name="status_Preparing">Preparing</a>
                    <a class="dropdown-item" href="#" name="status_Preparing">Awaiting MAWB</a>
                    <?php
                        if(isset($batch['mawb_code'])) {
                            ?>
                            <a class="dropdown-item" href="#" name="status_readyDispatched">Ready to dispatch</a>
                            <a class="dropdown-item" href="#" name="status_Dispatched">Dispatched</a>
                    <?php
                        }
                    ?>
                </div>
            </div>
            <div class="col-12">
                <input class="input-text" name="mawb_code" type="text" placeholder="MAWB Code" value="<?= $batch['mawb_code']; ?>">

            </div>
            <div class="col-12">
                <input class="input-text" name="flight_code" type="text" placeholder="Flight Code" value="<?= $batch['flight_code']; ?>">

            </div>
        </div>


        <div class="col-6 pl-10 shown-holder">
            <div class="table-wrapper">
                <table class="data table table-order-items history" id="my-orders-table">
                    <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
                    <thead>
                    <tr>
                        <th scope="col" class="col date"><?= __('AWB Code') ?></th>
                        <th scope="col" class="col date"><?= __('Timestamp') ?></th>
                        <th scope="col" class="col webshop"><?= __('Parcels') ?></th>
                        <th scope="col" class="col amount"><?= __('Pallet No.') ?></th>

                    </tr>
                    </thead>
                    <tbody>
                        <?php $_items = $viewModel->getBatchPallets($batchId);?>

                        <?php if ($_items && count($_items)) : ?>
                            <?php foreach ($_items as $_item) : ?>
                                <tr>
                                    <td scope="col" class="col awbCode"><?= $_item['awb_code']; ?></td>
                                    <td scope="col" class="col awbCode"><?= $_item['created_at']; ?></td>
                                    <td scope="col" class="col awbCode"><?= $viewModel->getParcelAmount($batchId, $_item['awb_code']); ?></td>
                                    <td scope="col" class="col awbCode"><input type="text" class="input-text" name="awb_<?php echo $_item['awb_code']; ?>" value="<?= $_item['pallet_code']; ?>" style="margin: 0;height:20px;padding:0;font-size:10px;" /></td>
                                </tr>


                            <?php endforeach; ?>
                        <?php else : ?>
                            <div class="message info empty"><span><?= $viewModel->getEmptyOrdersMessage(); ?></span></div>
                        <?php endif ?>
                    </tbody>
                </table>
            </div>

        </div>
        <div class="hidden-holder">
            <input type="hidden" name="warehouse" value="<?php echo $viewModel->getWarehouses($batch['warehouse_id'])['entity_id'];?>"/>
        </div>


    </div>



    <input class="btn btn-secondary mt-10" type="submit" value="Submit" placeholder="Webshop Name">

    <a href="<?php echo $this->getUrl('wms/batches/delete' , ['batch_id' => $batchId]); ?>" class="btn btn-danger mt-10 ml-20">Delete batch</a>

    <script>

        require(["jquery", "Eos_Base/js/bootstrap.bundle.min", 'Eos_Base/js/packageDetails'], function ($, bootstrap) {

            $('input').attr('autocomplete','off');

            $('.menu-warehouse .dropdown-item').on('click', function(e) {
                e.preventDefault();
                $('input[name="warehouse"]').attr("value", $(this).attr('name').split('_')[1]);


            });

            });
    </script>
