<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<div class="block mb-10">

    <div class="row col-12">
        <div class="col-12 col-lg-6 pr-lg-6 mb-20">
            <div class="card" style="background: #fafafa;">
                <div class="card-body">
                    <h5 class="text-center mb-20">Contact us</h5>

                    <div class="row col-12">
                        <div class="col-2 text-center">
                            <i class="bi bi-envelope-fill" style="font-size:30px;"></i>
                        </div>
                        <div class="col-10 pt-10">
                            <p class="mb-0">info@europeonlineservices.com</p>
                        </div>
                    </div>
                    <hr style="border-color:#ccc;" />
                    <div class="row col-12 mb-10">
                        <div class="col-2 text-center">
                            <i class="bi bi-telephone-fill" style="font-size:30px;"></i>
                        </div>
                        <div class="col-10 pt-10">
                            <p class="mb-0">+31 6 82 27 41 51</p>
                        </div>
                    </div>

                </div>

            </div>
        </div>
        <div class="col-12 col-lg-6 pl-lg-6 mb-10">
            <div class="card" style="background: #fafafa;">
                <div class="card-body">
                    <h5 class="text-center mb-20">How can we help?</h5>
                    <div class="row col-12">
                        <div class="col-2 text-center">
                            <i class="bi bi-question-circle-fill" style="font-size:30px;"></i>
                        </div>
                        <div class="col-10 pt-10">
                            <a href="#faq" class="mb-0">FAQ</a>
                        </div>
                    </div>
                    <hr style="border-color:#ccc;" />
                    <div class="row col-12 mb-10">
                        <div class="col-2 text-center">
                            <i class="bi bi-telephone-fill" style="font-size:30px;"></i>
                        </div>
                        <div class="col-10 pt-10">
                            <a href="<?php echo $this->getUrl('frontportal/aboutus'); ?>#for-business"
                                class="mb-0">Contact for businesses</a>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>

</div>