<div id="faq">
    <div class="title">
        <h2 class="text-center mb-8">Frequently Asked Questions</h2>
        <p class="text-center" style="font-size: 18px;">The most common asked questions when using our services.</p>
    </div>

    <div class="container mb-100">
        <div class="row col-12">

            <div id="accordion" class="col-12">
                <div class="mb-10 collapse-holder">
                    <div class="collapsed" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                        <div class="row col-12">
                            <div class="col-11">
                                <h3 class="">How much does an account at Europe Online Services costs?</h3>
                            </div>
                            <div class="col-1" style="margin-top:-15px;">
                                <i class="bi bi-plus-lg" style="font-size: 36px;"></i>
                            </div>
                        </div>

                    </div>

                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                        <div class="pr-lg-60">
                            <p>It is completely Free!</p>
                            <p>At Europe Online Services we care about you. We take pride in providing you with simple, safe, and affordable parcel shipping services. Therefore an account is free and you don’t have to pay for any membership type of action. We are happy to have you as a customer!
                            </p>
                        </div>
                    </div>
                </div>
                <div class="mb-10 collapse-holder">
                    <div class="collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        <div class="row col-12">
                            <div class="col-11">
                                <h3 class="">Can Europe Online Services ship my products?</h3>
                            </div>
                            <div class="col-1" style="margin-top:-15px;">
                                <i class="bi bi-plus-lg" style="font-size: 36px;"></i>
                            </div>
                        </div>
                    </div>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                        <div class="pr-lg-60">
                            <p>We can ship just about every item for you, including clothing, cosmetics, toys, cell phones, laptops, and much more.</p>
                            <p>The types of items that we cannot ship are restricted by the United States government and/or prohibited from import into your country. For example, we cannot ship any items that require a license to export or require a license exception to be filed.</p>
                            <p>Please check with your local customs services if your product is allowed to be imported into your country.  If you are not sure you also contact us to review the item you wish to ship, We need  the following information:</p>
                            <ul class="mb-40">
                                <li>Link to the item you wish to purchase</li>
                                <li>Address you are shipping to</li>
                                <li>Weight and dimensions of the product</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="mb-10 collapse-holder">
                    <div class="collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                        <div class="row col-12">
                            <div class="col-11">
                                <h3 class="">How do I create an account? & How can I register on Europe Online Services?</h3>
                            </div>
                            <div class="col-1" style="margin-top:-15px;">
                                <i class="bi bi-plus-lg" style="font-size: 36px;"></i>
                            </div>
                        </div>
                    </div>
                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
                        <div class="pr-lg-60">
                            <p>When you want to use our services you have to register yourself for free at <a href="https://www.europeonlineservices.com/customer/account/create">here</a>. When you have created an account, you immediately receive your Member ID and European shipping address. You can now start shopping in Europe and send parcels to your European shipping address. Please also mention your Europe Online Services Member ID in the name of the purchase order at an online webshop.</p>
                        </div>
                    </div>
                </div>

                <div class="mb-10 collapse-holder">
                    <div class="collapsed" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                        <div class="row col-12">
                            <div class="col-11">
                                <h3 class="">Can Europe Online Services ship dangerous goods/merchandise?</h3>
                            </div>
                            <div class="col-1" style="margin-top:-15px;">
                                <i class="bi bi-plus-lg" style="font-size: 36px;"></i>
                            </div>
                        </div>

                    </div>

                    <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordion">
                        <div class="pr-lg-60">
                            <p>Yes we can, can ship Dangerous Goods to certain countries. Europe Online Services ships Class 9 Dangerous Goods, including perfume, nail polish, hairspray, spray-on sunscreen, and spray-on tan. We may also be able to ship lithium-ion batteries, depending on your country and our carrier’s ability to courier these goods to your area.</p>
                        </div>
                    </div>
                </div>


                <div class="mb-10 collapse-holder">
                    <div class="collapsed" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                        <div class="row col-12">
                            <div class="col-11">
                                <h3 class="">What is included in the price if I want to send a package?</h3>
                            </div>
                            <div class="col-1" style="margin-top:-15px;">
                                <i class="bi bi-plus-lg" style="font-size: 36px;"></i>
                            </div>
                        </div>

                    </div>

                    <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordion">
                        <div class="pr-lg-60">
                            <p>At Europe Online Services you know where you pay for. The price is fully based on your product specifications in order to provide the most optimum shipping price for you. We make sure that our shipping rates are fully transparent.</p>
                            <p>Our shipping calculator estimates the shipping price in weight (kg) and volumetric weight (size) based on your product specifications. Our system automatically checks the consolidation and repack possibilities in order to reduce the size and shipping price. Our platform automatically calculates the best shipping price for your product and prevents you from unnecessary and surprising costs during delivery.</p>
                            <p>We take pride in providing customers with simple, safe, and affordable parcel shipping services. As a result of our innovative technology and partners, we can keep our shipping rates lower than our competitors so you can benefit from this.</p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<script>

    require(["jquery", "Eos_Base/js/bootstrap.bundle.min"], function ($) {
        $('#accordion').on('hidden.bs.collapse', function () {

            $('.collapse-holder').each(function() {
                if(!$(this).children().hasClass('collapse')) {
                    $(this).find('i').removeClass('bi-plus-lg')
                    $(this).find('i').addClass('bi-dash-lg')

                }else {
                    $(this).find('i').removeClass('bi-dash-lg')
                    $(this).find('i').addClass('bi-plus-lg')
                }
            });
            // console.log($(this).find('.collapse[aria-expanded="true"]').find('h3').text())
        })
    });
</script>
