<h3 class="text-center mb-40">Europe Online Services</h3>

<div class="row col-12">
    <div class="col-2 text-center">
        <i class="bi bi-envelope-fill" style="font-size:30px;"></i>
    </div>
    <div class="col-10 pt-10">
        <p class="mb-0">info@europeonlineservices.com</p>
    </div>
</div>
<hr style="border-color:#ccc;" />
<div class="row col-12">
    <div class="col-2 text-center">
        <i class="bi bi-telephone-fill" style="font-size:30px;"></i>
    </div>
    <div class="col-10 pt-10">
        <p class="mb-0">+31 6 82 27 41 51</p>
    </div>
</div>
<hr style="border-color:#ccc;" />
<div class="row col-12">
    <div class="col-2 text-center pt-10">
        <i class="bi bi-geo-alt-fill" style="font-size:30px;"></i>
    </div>
    <div class="col-10 pt-10">
        <p class="mb-0">Dennenlaan 9<br>5271 RE Sint-Michielsgestel<br>The Netherlands</p>
    </div>
</div>

