<div class="my-100" style="position: relative;">
    <div class="mb-60 py-lg-100 block-quote" style="background-image:url('<?php echo $this->getViewFileUrl('images/contact/contact-1.png'); ?>'); background-size:cover;">
        <div style="position:absolute;top:0;left:0; width:100%;height:100%;background: rgba(0,0,0,0.67);"></div>
        <div class="container py-100">
            <div class="row col-12 text-center">
                <h2 style="color:white;margin:0 auto;">“Whether you’re curious about features, your account, or even press we’re ready to answer any and all questions.”</h2>

            </div>
        </div>
    </div>

</div>
