<h3 class="text-center mb-40">How can we help?</h3>
<div class="row col-12">
    <div class="col-2 text-center">
        <i class="bi bi-question-circle-fill" style="font-size:30px;"></i>
    </div>
    <div class="col-10 pt-10">
        <a href="#faq" class="mb-0">FAQ</a>
    </div>
</div>
<hr style="border-color:#ccc;" />
<div class="row col-12">
    <div class="col-2 text-center">
        <i class="bi bi-telephone-fill" style="font-size:30px;"></i>
    </div>
    <div class="col-10 pt-10">
        <a href="<?php echo $this->getUrl('frontportal/aboutus'); ?>#for-business" class="mb-0">For businesses</a>
    </div>
</div>
<hr style="border-color:#ccc;" />
