<div class="shape align-items-end mb-n160 shape-home-hero">
    <svg class="mb-n160" data-rellax-speed="-1" width="518" height="641" viewBox="0 0 518 641" fill="none" xmlns="http://www.w3.org/2000/svg">
        <circle cx="400.5" cy="320.5" r="320.5" fill="#3B7580" />
    </svg>
</div>
<div class="swiper swiper-portfolio swiper-portfolio-banner container text-white mt-sm-60" data-swiper-slides="1" data-swiper-speed="700" data-swiper-parallax="true" data-swiper-loop="true">
    <div class="swiper-container show-on-scroll" data-show-duration="800">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <a class="card card-portfolio card-overlay card-image-sm card-portfolio-banner text-white" href="#">
                    <span class="card-img swiper-image" data-swiper-parallax-x="20%">
                        <img src="<?php echo $this->getViewFileUrl('images/Stock_bg.png'); ?>" alt="">
                        <span class="background-color" style="background-color: rgba(14, 14, 14, .2);"></span>
                    </span>
                    <span class="card-img-overlay">
                        <span class="card-title h2"><span class="card-title-decoration"></span>Shopping in Europe has never been easier.</span>
                    </span>
                </a>
            </div>
            <div class="swiper-slide">
                <a class="card card-portfolio card-overlay card-image-sm card-portfolio-banner text-white" href="#">
                    <span class="card-img swiper-image" data-swiper-parallax-x="20%">
                        <img src="<?php echo $this->getViewFileUrl('images/bg_Boss.png'); ?>" alt="">
                        <span class="background-color" style="background-color: rgba(14, 14, 14, .2);"></span>
                    </span>
                    <span class="card-img-overlay">
                        <span class="card-title h2"><span class="card-title-decoration"></span>Some other text</span>
                    </span>
                </a>
            </div>
        </div>
    </div>
    <div class="swiper-button-prev d-none d-sm-flex">
        <svg width='26' height='11' viewBox='0 0 26 11' fill='none' xmlns='http://www.w3.org/2000/svg'>
            <path d='M5.5 1L1 5.5L5.5 10' stroke='currentColor' stroke-width='1.3' stroke-linecap='round' stroke-linejoin='round' />
            <path d='M19 5.5H1' stroke='currentColor' stroke-width='1.3' stroke-linecap='round' stroke-linejoin='round' />
        </svg>
    </div>
    <div class="swiper-button-next d-none d-sm-flex">
        <svg width='26' height='11' viewBox='0 0 26 11' fill='none' xmlns='http://www.w3.org/2000/svg'>
            <path d='M20.5 1L25 5.5L20.5 10' stroke='currentColor' stroke-width='1.3' stroke-linecap='round' stroke-linejoin='round' />
            <path d='M7 5.5H25' stroke='currentColor' stroke-width='1.3' stroke-linecap='round' stroke-linejoin='round' />
        </svg>
    </div>
    <div class="swiper-pagination"></div>
</div>
