<?php
/** @var \Magento\Framework\View\Element\Template $block */


?>
<div class="home">
    <div class="hero banner shape-parent mb-60 overflow-initial"
         style="background-image:url('<?php echo $this->getViewFileUrl('images/home/home-4.png'); ?>');">
        <div style="position:absolute;top:0;left:0; width:100%;height:100%;background: rgb(0,0,0);
background: linear-gradient(119deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0.6) 60%);
"></div>
        <div class="container" style="">
            <div class="row col-12 text-right">
                <div class="col-12 col-lg-5 offset-lg-7">
                    <h1 class="text-white">Shopping in Europe has never been easier</h1>
                    <h3 class="text-white" style="font-weight:200">We enable you to transport European products anywhere in Asia</h3>
                    <a href="<?php echo $this->getUrl('customer/account/create'); ?>" class="btn btn-primary text-center" style="width: 250px;">Sign up for free</a>
                </div>

            </div>
        </div>
    </div>

    <h2 class="text-center">Track & Trace</h2>

    <div class="banner-track-trace py-60 mb-100" style="
    width:100%;
    background: rgb(0,17,45);
    background: linear-gradient(150deg, rgba(0,17,45,1) 0%, rgba(18,57,95,1) 100%);
    box-shadow: 0 0 10px 5px rgba(0,0,0,0.25);
">
        <div class="container ">
            <div class="createOrderForm">
                <label style="color:#fff; font-size:16px; font-weight: 300;" class="mb-10">Your tracking number</label>
                <div class="row col-12">
                    <div class="col-6 pr-20">

                        <input type="text" name="awb-code" placeholder="SFXXXXXXXXXX" class="input-text"  style="background: #fff;"/>
                    </div>
                    <div class="col-6 col-lg-3">
                        <button id="searchAwbcode" class="btn btn-primary" style="width: 100%;"data-toggle="modal" data-target="#searchAwbcodeModel">Search</button>
                    </div>
                </div>

                <div id="awbSteps" style="display:none;">
                    <div class="awb-tracing position-relative">


                    </div>
                </div>
            </div>

        </div>


    </div>

    <div class="container mb-60 mb-lg-100">
        <div class="row col-12 mb-lg-100">
            <div class="col-12 col-lg-6 p-60">
                <img src="<?php echo $this->getViewFileUrl('images/home/home-1.png'); ?>" />
            </div>
            <div class="col-12 col-lg-6">
                <h3 class="">Transportation from Europe to Asia</h3>
                <p class="">With the Europe Online Services platform, you can easily <strong>transport your favourite European products to your address in Asia </strong>. With the use of our fully automatic platform and services, shopping in Europe has never been easier. We use air transportation in order to deliver your parcel fast and safely.</p>
                <h3 class="">Our professional and trustful shipping services</h3>
                <p class="">Our professional teams will proceed your parcel as quickly as possible. At Europe Online Services all the expertise is available so we can provide you with the best service. Together with our Asian <strong>partner SF Express</strong>, we keep parcel transportation <strong>simple, safe, fast and affordable</strong>.</p>
        </div>

        <div class="row col-12">
            <div class="col-12 col-lg-6 order-2 order-lg-1">
                <h3 class="">The benefits of our carefully designed platform</h3>
                <p class="">Our fully automatic platform is designed for simplicity and assists you in sending parcels. Due to our technology, we can offer the <strong>best shipping prices</strong> so you can benefit. Use our <strong>track and trace</strong> code to follow your parcel anywhere and enjoy the simplicity of our services.</p>
                <h3 class="">Avoid difficult custom clearances and paperwork</h3>
                <p class="">Avoid all the difficult logistic processes and customs declaration paperwork by simply uploading your parcel information to our platform. Complete the tasks in your free account on the platform and we will deliver the products to your address in Asia.</p>
            </div>
            <div class="col-12 col-lg-6 p-60 order-1 order-lg-2">
                <img src="<?php echo $this->getViewFileUrl('images/home/home-2.png'); ?>" />
            </div>
        </div>
    </div>
    </div>
    <div class="mb-60 py-lg-40"
         style="position:relative;height:450px;background:url('<?php echo $this->getViewFileUrl('images/home/home-3.jpg'); ?>') no-repeat 20% 0%; background-size:cover;box-shadow: 0 0 10px 5px rgba(0,0,0,0.25);">
        <div style="position:absolute;top:0;left:0; width:100%;height:100%;background: linear-gradient(308deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0.6) 60%);"></div>
        <div class="container py-60">
            <div class="row col-12 text-left">
                <div class="col-12 col-lg-6">
                    <h2 class="text-white">Europe Online Services enables you to transport European products to Asia</h2>
                    <h3 class="text-white" style="font-weight:200;font-size:18px;">With the use of our fully automatic platform and shipment
                        by plane, shopping in Europe has never been easier.<br><br>We keep parcel transportation simple, safe, fast and affordable.</h3>
                    <a href="<?php echo $this->getUrl('customer/account/create'); ?>" class="btn btn-primary text-center" style="width: 250px;">Explore the possibilities</a>
                </div>

            </div>
        </div>
    </div>

    <div class="container">
        <h2 class="text-center">How it works</h2>
        <div class="row col-12">

            <div class="col-6 col-lg-3 text-center p-20">
                <h2>1</h2>
                <div class="card p-20 mb-10" style="
                    height:225px;
                    background-image:url('<?php echo $this->getViewFileUrl('images/home/howitworks-1.png'); ?>');
                    background-size: 70%;
                    background-repeat: no-repeat;
                    background-position: center;" >
                </div>
                <p style="font-size: 16px;"><strong>Sign up</strong> for free and receive your <strong>EU shipping address</strong> to send your parcels to.</p>
            </div>
            <div class="col-6 col-lg-3 text-center p-20">
                <h2>2</h2>
                <div class="card p-20 mb-10" style="
                    height:225px;
                    background-image:url('<?php echo $this->getViewFileUrl('images/home/howitworks-2.png'); ?>');
                    background-size: 70%;
                    background-repeat: no-repeat;
                    background-position: center;">
                </div>
                <p style="font-size: 16px;"><strong>Shop your favourite EU products</strong> and send them to your EU shipping address.</p>
            </div>
            <div class="col-6 col-lg-3 text-center p-20">
                <h2>3</h2>
                <div class="card p-20 mb-10" style="
                    height:225px;
                    background-image:url('<?php echo $this->getViewFileUrl('images/home/howitworks-3.png'); ?>');
                    background-size: 90%;
                    background-repeat: no-repeat;
                    background-position: center;">
                </div>
                <p style="font-size: 16px;">Simply upload your <strong>parcel information</strong> to our platform. We take <strong>care</strong> of the rest.</p>
            </div>
            <div class="col-6 col-lg-3 text-center p-20">
                <h2>4</h2>
                <div class="card p-20 mb-10" style="
                    height:225px;
                    background-image:url('<?php echo $this->getViewFileUrl('images/home/howitworks-4.png'); ?>');
                    background-size: 90%;
                    background-repeat: no-repeat;
                    background-position: center;">
                </div>
                <p style="font-size: 16px;">We will ship your parcel by <strong>air</strong> anywhere in <strong>Asia</strong>.</p>
            </div>
        </div>
        <div class="row col-12 text-center mb-100" style="width: 100%;">
            <p style="margin:0 auto;"><a href="<?php echo $this->getUrl('customer/account/create'); ?>" class="btn btn-primary text-center" style="width: 250px;">Explore the possibilities</a></p>

        </div>

    </div>

</div>
<script>

    require(["jquery", "Eos_Base/js/bootstrap.bundle.min"], function ($) {


        $('#searchAwbcode').on("click", function(e){
            e.preventDefault();

            $('#searchAwbcodeModel').remove();
            $('.awb-tracing').empty();


            var modal = '<div class="modal fade" id="searchAwbcodeModel" tabindex="-1" role="dialog" aria-labelledby="searchAwbcodeModel" aria-hidden="true">\n' +
                '    <div class="modal-dialog modal-dialog-centered" role="document">\n' +
                '        <div class="modal-content">\n' +
                '            <div class="modal-header">\n' +
                '                <h5 class="modal-title" id="exampleModalLongTitle">Status of your parcel:</h5>\n' +
                '                <button type="button" class="close" data-dismiss="modal" aria-label="Close">\n' +
                '                    <span aria-hidden="true">&times;</span>\n' +
                '                </button>\n' +
                '            </div>\n' +
                '            <div class="modal-body">';

            var awb = [];
  /*          var general = [];
            general.push({
                'order_id' : $('#hiddenForm input[name="order_id"]').val()
            });*/
            awb.push({
                'awb_code'       : 'SF1347035323275'
            });
            $.post(
                "<?php echo $block->getBaseUrl() . 'frontportal/home/getawbstatus/awb_code/'; ?>" + $('input[name="awb-code"]').attr('value'),
                {  },
                function(data){
                    data = $.parseJSON( data );
                    let steps = [];
                    let step = '';

                    for(let i=0; i<data.length; i++) {

                        if( data[i] !== undefined)
                            if(i === data.length -1) {
                              step = '<div class="awb-tracing-item awb-tracing-item-active mb-20"><div class="">' +
                                    '<span class="awb-tracing-item-circle"></span>' +
                                    '<p class="mb-0"><span class="mb-4 awb-tracing-item-time ml-20">' + data[i]['@attributes']['accept_time'].slice(0,-3) + '</span>' +
                                    '<span class="mb-4 awb-tracing-item-address ml-10">' + data[i]['@attributes']['accept_address'] + '</span></p>' +
                                    '<p class="awb-tracing-item-remark mb-0 ml-20">' + data[i]['@attributes']['remark'].replace('【', '<strong>').replace('】', '</strong>') + '</p>' +
                                    '</div></div>'
                                ;
                            } else {
                                step = '<div class="awb-tracing-item mb-20"><div class="">' +
                                    '<span class="awb-tracing-item-circle"></span>' +
                                    '<p class="mb-0"><span class="mb-4 awb-tracing-item-time ml-20">' + data[i]['@attributes']['accept_time'].slice(0,-3) + '</span>' +
                                    '<span class="mb-4 awb-tracing-item-address ml-10">' + data[i]['@attributes']['accept_address'] + '</span></p>' +
                                    '<p class="awb-tracing-item-remark mb-0 ml-20">' + data[i]['@attributes']['remark'].replace('【', '<strong>').replace('】', '</strong>') + '</p>' +
                                    '</div></div></div>'
                                ;
                            }

                            steps.push(step);


                    }
                    steps.reverse();
                    $('.awb-tracing').prepend('<div class="awb-tracing-path"></div>');

                    for (let i = 0; i < steps.length; ++i) {
                        $(".awb-tracing").append(steps[i]);
                    }

                    test();

/*

                    const newHeight = $('.awb-tracing-path').height() - $('.awb-tracing-item:last-child').height();
                    $('.awb-tracing-path').attr('style','height:' + newHeight + 'px;');
                    console.log($('.awb-tracing-item:last-child').height());*/

                }
            );
            modal += $('#awbSteps').html();

            modal +=
                '            </div>\n' +
                '            <div class="modal-footer">\n' +
                '                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>\n' +
                '            </div>\n' +
                '        </div>\n' +
                '    </div>\n' +
                '</div>\n';

            $('body').append(modal);
        });

        function test() {
            const newHeight = $('.awb-tracing-path').height() - $('.awb-tracing-item:last-child').height();
            $('.awb-tracing-path').attr('style','height:' + newHeight + 'px;');
            console.log($('.awb-tracing-item:last-child').height());
        }


        $('.awb-tracing-path').on('change', function() {
            const newHeight = $(this).height() - $('.awb-tracing-item:last-child').height();
            $(this).attr('style','height:' + newHeight + 'px;');

            console.log(newHeight);
        });


    });
</script>
