<div class="py-40 mt-n8 shape-parent bg-white overflow-hidden" id="how-does-it-work">
    <div class="container">
        <h2 class="text-dark mb-100 mt-n10">How does it work</h2>
        <div class="row gh-1 gv-5">
            <div class="col-12 col-lg-5">
                <ul class="nav nav-opacity nav-tabs nav-gap-md flex-column text-dark" id="workTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active font-size-18" id="idea-tab" data-toggle="tab" href="#idea" role="tab" aria-controls="idea" aria-selected="true">Shop at your favourite brand</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-size-18" id="design-tab" data-toggle="tab" href="#design" role="tab" aria-controls="design" aria-selected="false">Register your order</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-size-18" id="development-tab" data-toggle="tab" href="#development" role="tab" aria-controls="development" aria-selected="false">Payment</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-size-18" id="release-tab" data-toggle="tab" href="#release" role="tab" aria-controls="release" aria-selected="false">Receive and enjoy!</a>
                    </li>
                </ul>
            </div>
            <div class="col-12 col-lg-7">
                <div class="tab-content text-dark mr-n30" id="workTabContent">
                    <div class="tab-pane fade show active" id="idea" role="tabpanel" aria-labelledby="idea-tab">
                        <div class="row gh-5 gv-5">
                            <div class="col-md pr-60">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco </p>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="design" role="tabpanel" aria-labelledby="design-tab">
                        <div class="row gh-5 gv-5">
                            <div class="col-md pr-60">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea </p>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="development" role="tabpanel" aria-labelledby="development-tab">
                        <div class="row gh-5 gv-5">
                            <div class="col-md pr-60">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu</p>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="release" role="tabpanel" aria-labelledby="release-tab">
                        <div class="row gh-5 gv-5">
                            <div class="col-lg pr-60">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr class="mt-100 mb-40 pb-7" style="border-top-color:#aaa">
    </div>
</div>
