<div class="">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-5 text-center text-lg-left show-on-scroll" data-show-delay="100" data-show-duration="800">
                <h1 class="h2 mb-lg-0 text-gray-400 ">Premium parcel shipping from EU to China.</h1>
            </div>
            <div class="col-12 col-lg-5 ml-lg-100 justify-content-right-0 mt-5 box-shadow p-40 eos-home-register bg-white" data-show-delay="200" data-show-duration="100">
                <form action="#" class="createOrderForm">
                    <div class="col-12 text-center">
                        <h4 class="text-grey-dark mb-40 mt-n10">Register</h4>

                    </div>
                    <div class="row gh-1 gv-2">

                        <div class="col-12 show-on-scroll pt-10" data-show-duration="400" data-show-distance="10" data-show-delay="470">
                            <button class="btn w-full btn-primary btn-full" type="button" name="button">Create an account</button>
                        </div>

                        <div class="col-12 row show-on-scroll" data-show-duration="400" data-show-distance="10" data-show-delay="600">


                            <div class="col-1">
                                <img src="<?php echo $this->getViewFileUrl('images/Check.png'); ?>" width="20" />
                            </div>
                            <div class="col-11 pl-6 pt-2 font-italic font-size-16">
                                <span>Official partner of SF Express</span>
                            </div>
                        </div>
                        <div class="col-12 row show-on-scroll pt-10" data-show-duration="400" data-show-distance="10" data-show-delay="650">
                            <div class="col-1">
                                <img src="<?php echo $this->getViewFileUrl('images/Check.png'); ?>" width="20" />
                            </div>
                            <div class="col-11 pl-6 pt-2 font-italic font-size-16">
                                <span>Affortable shipping</span>
                            </div>
                        </div>
                        <div class="col-12 row show-on-scroll pt-10" data-show-duration="400" data-show-distance="10" data-show-delay="700">
                            <div class="col-1">
                                <img src="<?php echo $this->getViewFileUrl('images/Check.png'); ?>" width="20" />
                            </div>
                            <div class="col-11 pl-6 pt-2 font-italic font-size-16">
                                <span>WeChat payment</span>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
