<div class="row col-12 card-option-holder mb-40">
    <div class="col-12">
        <div class="card card-option card-option-active">
            <div class="card-header">
                <div class="row col-12 p-4">
                    <div class="col-8 text-left">
                        <span>
                            <?= $header ?>
                        </span>
                    </div>
                    <div class="col-4 text-right">
                        <a href="<?= $url ?>" class="btn btn-tertiary btn-small text-dark">
                            <?= $buttonText ?>
                            <svg width='26' height='11' viewBox='0 0 26 11' fill='none'
                                xmlns='http://www.w3.org/2000/svg'>
                                <path d='M20.5 1L25 5.5L20.5 10' stroke='currentColor' stroke-width='1.3'
                                    stroke-linecap='round' stroke-linejoin='round' />
                                <path d='M7 5.5H25' stroke='currentColor' stroke-width='1.3' stroke-linecap='round'
                                    stroke-linejoin='round' />
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <span>
                    <?= $body ?>
                </span>
            </div>
        </div>
    </div>
</div>