<?php
/** @var \Magento\Framework\View\Element\Template $block */

$shipmentViewModel = $block->getData('shipment_view_model');
$orderViewModel = $block->getData('order_view_model');

$shipments = $shipmentViewModel->getShipments()->filterByCustomer();
$orders = $orderViewModel->getOrders()->filterByCustomer();

?>
<div class="block">
    <div class="block-title">
        <strong>To-do list</strong>
    </div>
    <?php
    // Check if customer is new
    if ($orders->getSize() < 1) {
        echo $this->getLayout()
            ->createBlock("Magento\Framework\View\Element\Template")
            ->setTemplate("Eos_Base::ToDo/card.phtml")
            ->setData([
                'header' => "Your first shipment!",
                'buttonText' => "Let's start",
                'url' => $this->getUrl('portal/shipment/create'),
                'body' => "Thank you for trusting us handling your recently bought product(s) in Europe. In order to do a proper shipment, we need some information about your recent order.
                        Please click on the \"Let's start\" to begin!",
            ])
            ->toHtml();
    } else {

        foreach ($shipments->getItems() as $shipment) {
            if ($shipment['status'] === 'Ready for payment' || $shipment['status'] === 'During payment') {
                echo $this->getLayout()
                    ->createBlock("Magento\Framework\View\Element\Template")
                    ->setTemplate("Eos_Base::ToDo/card.phtml")
                    ->setData([
                        'header' => "Shipment is ready for payment",
                        'buttonText' => "Go to shipment",
                        'url' => $this->getUrl('portal/shipment/status'),
                        'body' => "Your parcels have arrived and been measured. It is now ready to confirm.",
                    ])
                    ->toHtml();

            }
        }


    }


    ?>



</div>