<?php
/** @var \Magento\Framework\View\Element\Template $block */

if ($block->getRequest()->getParam('shipment')): ?>

    <div class="block">
        <div class="block-title"><strong>Shipment Confirmed!</strong></div>
        <p></p>
        <p>When the parcels are arrived to our warehouse, we will notice you by E-mail. </p>

    </div>

<?php else: ?>
    <div class="message info empty"><span>Oops, There is no shipment created...</span></div>
<?php endif ?>