<?php
/** @var \Magento\Framework\View\Element\Template $block */
/**@var Eos\Base\ViewModel\Orders $viewModel*/
$viewModel = $block->getData('view_model');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey');
$address = $viewModel->getCustomerAddress();

$country = $viewModel->getCountry(null, $address['country_id']);

?>

<?php $_items = $viewModel->getOrders(['open:pricing'], false,true); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_items && count($_items)) :
    foreach ($_items as $order) {

        ?>
        <div class="row col-12 card-option-holder mb-40 card-order" id="order_<?= $order['entity_id']; ?>">
            <div class="col-12">
                <div class="card card-option card-option-active">
                    <div class="card-header">
                        <div class="row col-12 p-4">

                            <div class="col-6 text-left">
                                <span> <?= $order['webshop_title'] ?></span>
                            </div>
                            <div class="col-6 text-right">
                                <a href="<?php echo $block->getBaseUrl() . 'portal/order/create/order/' . $order['entity_id']; ?>" class="btn btn-tertiary btn-small text-dark mr-10">Edit information

                                </a>

                                <button class="btn btn-tertiary btn-small text-dark bg-white mr-20 btn-modal" data-toggle="modal" data-target="#exampleModalCenter">Create shipment
                                    <svg width='26' height='11' viewBox='0 0 26 11' fill='none' xmlns='http://www.w3.org/2000/svg'>
                                        <path d='M20.5 1L25 5.5L20.5 10' stroke='currentColor' stroke-width='1.3' stroke-linecap='round' stroke-linejoin='round' />
                                        <path d='M7 5.5H25' stroke='currentColor' stroke-width='1.3' stroke-linecap='round' stroke-linejoin='round' />
                                    </svg>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="card-body bg-white" style="white-space: nowrap;">
                        <div class="row col-flex">
                            <div class="col">
                                <p><strong>Webshop Information</strong></p>
                            </div>
                            <div class="col">
                                <p><strong>Address Information</strong></p>
                            </div>

                        </div>
                        <div class="row col-flex mb-20">
                            <div class="row col-flex col">
                                <div class="col text-left">
                                    <p>Webshop:</p>
                                    <p>Invoice No.:</p>
                                    <p>Tracking No.:</p>
                                    <p>EOS Warehouse:</p>
                                </div>
                                <div class="col text-left">
                                    <p> <?= $order['webshop_title'] ?></p>
                                    <p> <?= $order['webshop_order_nr'] ?></p>
                                    <p> <?= $order['webshop_tracking_number'] ?></p>
                                    <p> <?= $viewModel->getWarehouse(intval($order['warehouse_id']))['country_title'] ?></p>
                                </div>
                            </div>
                            <div class="row col-flex col">
                                <div class="col text-left">
                                    <p>Name:</p>
                                    <p>Street:</p>
                                    <p>City:</p>
                                    <p>Postal code:</p>
                                    <p>Country:</p>
                                </div>
                                <div class="col text-left">
                                    <p> <?= $viewModel->getCustomer()->getName() ?></p>
                                    <p><?= str_replace("\n", " ", $address['street']); ?></p>
                                    <p><?= $address['city']; ?></p>
                                    <p><?= $address['postcode']; ?></p>
                                    <p><?= $country['country_title']; ?></p>
                                </div>
                            </div>
                        </div>
                        <p><strong>Product Information</strong></p>
                        <table class="data table table-order-items history" id="my-orders-table">
                            <caption class="table-caption"><?= __('Orders') ?></caption>
                            <thead>
                            <tr>
                                <th scope="col" class="col date"><?= __('Brand') ?></th>
                                <th scope="col" class="col date"><?= __('Product type') ?></th>
                                <th scope="col" class="col date"><?= __('Units') ?></th>
                                <th scope="col" class="col date"><?= __('Net Price') ?></th>
                                <th scope="col" class="col date"><?= __('Gross Price') ?></th>
                                <th scope="col" class="col date"><?= __('Tax Price') ?></th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php
                            $orderDetails = $viewModel->getOrderDetails($order['entity_id']);

                            foreach ($orderDetails as $orderDetail) {
                                ?>
                                <tr>
                                    <td class="col"><?= $orderDetail['product_brand'] ?></td>
                                    <td class="col"><?= $orderDetail['product_title'] ?></td>
                                    <td class="col"><?= $orderDetail['product_amount'] ?></td>
                                    <td class="col"><?= number_format((float)($orderDetail['product_price_net']), 2, '.', ''); ?></td>
                                    <td class="col"><?= number_format((float)($orderDetail['product_price_gross']), 2, '.', ''); ?></td>
                                    <td class="col"><?= number_format((float)($orderDetail['product_price_net']- $orderDetail['product_price_gross']),2, '.', ''); ?></td>
                                </tr>
                                <?php
                            }

                            ?>

                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>

        <?php
    }

    ?>





<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($viewModel->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>



<script>
    require(["jquery", "Eos_Base/js/bootstrap.bundle.min", 'Eos_Base/js/packageDetails','mage/url'], function ($, bootstrap,packageDetails,urlBuilder) {

        $('.btn-modal').on("click", function() {
            $('.modal').remove();
            const order_id = $(this).closest('.card-order').attr('id').split('_')[1];
            const myUrl = urlBuilder.build('portal/shipment/save');

            let modal = '<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">\n' +
                '    <div class="modal-dialog modal-dialog-centered" role="document">\n' +
                '        <div class="modal-content">\n' +
                '            <div class="modal-header">\n' +
                '                <h5 class="modal-title" id="exampleModalLongTitle">Consolidate Orders</h5>\n' +
                '                <button type="button" class="close" data-dismiss="modal" aria-label="Close">\n' +
                '                    <span aria-hidden="true">&times;</span>\n' +
                '                </button>\n' +
                '            </div>\n' +
                '            <form method="post" action="' + myUrl + '">\n' +
                '              <div class="modal-body">';

            modal += '<div class="table-wrapper orders-history">' +
                '      <table class="data table table-order-items history" id="table-order_' + order_id + '">' +
                '          <caption class="table-caption"><?= __('Orders') ?></caption>' +
                '          <thead>' +
                '              <tr>' +
                '                  <th scope="col" class="col webshop-title"><?= __('Webshop') ?></th> ' +
                '                  <th scope="col" class="col gross-price"><?= __('Gross Price') ?></th> ' +
                '                  <th scope="col" class="col checkbox"><?= __('Include') ?></th> ' +
                '              </tr> '+
                '          </thead>' +
                '          <tbody> ' ;

            <?php

            $i = 0;
            if ($_items && count($_items)) :
                foreach ($_items as $order) {
               ?>

            modal +=
                 '              <tr> '+
                 '                  <td><?= $order['webshop_title']; ?></td>' +
                 '                  <td class="webshop-order-price"><?= $order['webshop_order_total_price_gross']; ?></td>' +
                 '                  <td><input type="checkbox" class="order-checkbox" name="order_<?= $order['entity_id'] ?>"></td>' +
                 '              </tr> ';
            <?php
            $i++;
                }
            endif
            ?>

            modal +=
                '              <tr> '+
                '                  <td><strong>Total</strong></td>' +
                '                  <td class="order-totalprice" id="order_' + order_id + '-totalprice"><strong>0,00</strong></td>' +
                '                  <td>&nbsp;</td>' +
                '              </tr> ';

            modal +=
                 '          </tbody>' +
                 '      </table>' +
                 '  </div>';

            modal +=
                '                <p></p>' +
                '            </div>\n' +
                '            <div class="modal-footer">\n' +
                '                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>\n' +
                '                <button type="submit" class="btn btn-primary">Save changes</button>\n' +
                '            </div>\n' +
                '        </div>\n' +
                '    </div>' +
                '  </form>\n' +
                '</div>\n';

            $('body').append(modal);

            $('input[name="order_' + order_id +'"').attr('checked', 'checked');
            $('#order_' + order_id + '-totalprice').html('<strong>' + $('input[name="order_' + order_id + '"]').closest('tr').find('.webshop-order-price').text() + '</strong>');


            $('#table-order_' + order_id + ' .order-checkbox').each(function() {
                checkboxChecked(this, order_id);

            });
        });
        $(document).on( "change", ".order-checkbox", function() {
            const order_id = $(this).closest('.table-order-items').attr('id').split('_')[1];

            let totalPrice = parseFloat($('#order_' + order_id + '-totalprice').text());
            let newTotalPrice = 0.00;
            $('#table-order_' + order_id + ' .order-checkbox').each(function() {

                let itemPrice = parseFloat($(this).closest('tr').find('.webshop-order-price').text());
                if($(this).attr('checked') === 'checked') {

                    newTotalPrice += itemPrice

                    $('#order_' + order_id + '-totalprice').html('<strong>' + newTotalPrice.toFixed(2) + '</strong>');
                }
            });
            $('#table-order_' + order_id + ' .order-checkbox').each(function() {
                checkboxChecked(this, order_id);

            });

        });

        function checkboxChecked(item, order_id) {
            let totalPrice = parseFloat($('#order_' + order_id + '-totalprice').text());
            if($(item).attr('checked') !== 'checked') {

                const itemPrice = parseFloat($(item).closest('tr').find('.webshop-order-price').text());
                const newTotalPrice = totalPrice + itemPrice;
                if(newTotalPrice > 130) {
                    $(item).prop('disabled', true);
                }else {
                    $(item).prop('disabled', false);
                }

            }
        }
    });


</script>
<!-- Modal -->
