<?php
/** @var \Magento\Framework\View\Element\Template $block */
/**@var Eos\Base\ViewModel\Orders $viewModel*/
$viewModel = $block->getData('view_model');
$categories = $viewModel->getCategories();
$subcategories = $viewModel->getSubCategories();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey');

$orderParam = $block->getRequest()->getParam('order');
$edit = $block->getRequest()->getParam('new') < 1;
if((!$block->getRequest()->getParam('new') && !$orderParam) || $block->getRequest()->getParam('new') > 0){
    $edit = false;
}
$order = $orderParam ? $viewModel->getOrder($orderParam) : false;
$openOrders = $viewModel->getOrdersAmount(['open:init', 'open:webshop' , 'open:warehouse', 'open:product'],true);

?>

<div class="card order-step mb-20 appendProduct-holder">
        <div class="card-header">
            <div class="col-12 row">

                <div class="row col-12">
                    <div class="col-9">
                        3. Product information (<span id="product_counter"><?= ($edit ? $viewModel->getOrderDetailsAmount($orderParam) : 0) ?></span>)
                    </div>
                    <div class="col-3 text-right">
                        <button type="button" class="btn-edit" <?php
                        if(!$edit || $order['status'] === 'open:init' || $order['status'] === 'open:webshop' || $order['status'] === 'open:warehouse') {
                            echo 'style="display: none;"';
                        }
                        ?>>Edit</button>
                    </div>
                </div>

            </div>
        </div>
        <div id="collapseThree" class="collapse" data-parent="#accordion">
            <div class="card-body p-20">
                <p class="mb-20">Please fill out the form and click on the button: Add another product to add all the products you purchased at the store to the list.</p>
                <form id="addSingleProduct"
                      class="createOrderForm needs-validation" novalidate
                      method="post"
                      autocomplete="off"
                      enctype="multipart/form-data"
                >
                    <div class="hidden-holder">
                        <?php
           /*             if($edit) {
                            $i=1;
                            foreach($viewModel->getOrderDetailsWithHs($orderParam) as $orderDetail){
                                echo
                                    '<input type="hidden" name="counter_'       . $i .'" value="'   . $i .'">' .
                                    '<input type="hidden" name="brand_'         . $i .'" value="'   . $orderDetail['brand']             .'">' .
                                    '<input type="hidden" name="productGroup_'  . $i .'" value="'   . $orderDetail['product_tax_nr']    .'">' .
                                    '<input type="hidden" name="count_'         . $i .'" value="'   . $orderDetail['count']             .'">' .
                                    '<input type="hidden" name="price_'         . $i .'" value="'   . $orderDetail['price']             .'">' .
                                    '<input type="hidden" name="amount_'        . $i .'" value="'   . $orderDetail['amount']            .'">' .
                                    '<input type="hidden" name="volumeType_'    . $i .'" value="'   . $orderDetail['brand']             .'">';
                            }
                        }*/

                        ?>

                    </div>
                    <h3 style="
    font-size: 16px;
    font-weight: bold;
    margin-bottom:40px;
">Add product</h3>
                    <div class="product-info">
                        <div class="row col-12 product-info-labels" style="font-size:12px;">

                            <div class="col-12 col-md-6 col-lg-4 pr-md-6">
                                <label class="input-label" for="brand_placeholder">1. Brand <i class="bi-info-lg" data-toggle="tooltip" data-placement="top" title="The name of the product brand."></i></label>
                                <input id="brand_placeholder" class="input-text form-control" required name="brand_placeholder" type="text" placeholder="Any brand" onpaste="return false;" ondrop="return false;" autocomplete="off">
                                <div class="invalid-feedback">
                                    Please provide a brand.
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-lg-4 pl-md-6 px-lg-6">
                                <label class="input-label mb-md-7" for="productCode_placeholder">2. Product custom No. <i class="bi-info-lg" data-toggle="tooltip" data-placement="top" title="Please use the product category library to generate a product custom number. The shown number is based on your selection, which is important for the custom clearance."></i></label>
                                <a href="#0" id="addProduct-button" data-toggle="modal" data-target="#addProducts">
                                    <input id="productCode_placeholder" class="input-text form-control" required name="productCode_placeholder" placeholder="Choose..." required type="text" onpaste="return false;" ondrop="return false;" autocomplete="off">
                                    <div class="invalid-feedback">
                                        Please provide a product code.
                                    </div>
                                </a>

                            </div>
                            <div class="col-12 col-md-6 col-lg-4 pr-md-6 pr-lg-0 pl-lg-6">
                                <label class="input-label" for="productTitle_placeholder">3. Product title <i class="bi-info-lg" data-toggle="tooltip" data-placement="top" title="The name of the product"></i></label>
                                <input id="productTitle_placeholder" class="input-text form-control" required name="productTitle_placeholder" placeholder="Productname on invoice" type="text" onpaste="return false;" ondrop="return false;" autocomplete="off">
                                <div class="invalid-feedback">
                                    Please provide a title.
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-lg-4 pl-md-6 pl-lg-0 pr-lg-6">
                                <label class="input-label" for="productAmount_placeholder">4. Units <i class="bi-info-lg" data-toggle="tooltip" data-placement="top" title="The amount of purchased products."></i></label>
                                <input id="productAmount_placeholder" class="input-text form-control" required name="productAmount_placeholder" type="number" placeholder="1" onpaste="return false;" ondrop="return false;" autocomplete="off">
                                <div class="invalid-feedback">
                                    Please provide the units.
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-lg-4 pr-md-6 pl-lg-6">
                                <label class="input-label" for="productPrice_placeholder">5. Price/unit (&euro;) <i class="bi-info-lg" data-toggle="tooltip" data-placement="top" title="The price paid per unit (please be aware that order(s) above 1000 RMB......)"></i></label>
                                <input id="productPrice_placeholder" class="input-text form-control input-numeric" required name="priceproduct_placeholder" type='text' placeholder="10.00" onpaste="return false;" ondrop="return false;" autocomplete="off">
                                <div class="invalid-feedback">
                                    Please provide the price.
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-lg-4 pl-md-6 mb-20">
                                <label class="input-label">6. Gross / Net <i class="bi-info-lg" data-toggle="tooltip" data-placement="top" title="The price per unit paid: before taxes (Net) or after taxes (Gross)"></i></label>
                                <div class="col-12 row calculate-group calculate-singleProduct">
                                    <div class="col-6">
                                        <div class="card card-toggle card-toggle-left card-toggle-active">
                                            <div class="card-header">
                                                <span>Net</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="card card-toggle card-toggle-right">
                                            <div class="card-header">
                                                <span>Gross</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-lg-4 pr-md-6 dropdown">
                      <!--          <label class="input-label" for="productType_placeholder">7. Type of unit <i class="bi-info-lg" data-toggle="tooltip" data-placement="top" title="The price per unit paid: before taxes (Gross) or after taxes (Net)"></i></label>
                                <input id="productType_placeholder" class="input-text form-control" required name="productType_placeholder" type="text" placeholder="pcs, box, pair, etc."  onpaste="return false;" ondrop="return false;" autocomplete="off">
                                <div class="invalid-feedback">
                                    Please provide the type of unit.
                                </div>
-->
                                <label class="input-label" for="productType_placeholder">7. Type of unit <i class="bi-info-lg" data-toggle="tooltip" data-placement="top" title="The type of measure for instance: shoes in pairs, parts in pieces"></i></label>
                                <a class="dropdown-toggle" href="#" role="button" id="dropdownTypeProduct" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <input id="productType_placeholder" class="dropdown-placeholder input-text form-control" name="productType_placeholder" type="text" placeholder="Choose..." required onpaste="return false;" ondrop="return false;" autocomplete="off"  <?= ($edit ? 'value="' . $order['product_type'] . '"' : '') ?>>
                                    <div class="invalid-feedback">
                                        Please provide the type of unit.
                                    </div>
                                </a>

                                <div class="dropdown-menu menu-product-type" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" href="#" name="product_type_pieces">Pieces</a>
                                    <a class="dropdown-item" href="#" name="product_type_pair">Pair</a>
                                    <a class="dropdown-item" href="#" name="product_type_box">Box</a>
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-lg-4 pl-md-6 px-lg-6">
                                <label class="input-label" for="productTax_placeholder">8. Tax (%) <i class="bi-info-lg" data-toggle="tooltip" data-placement="top" title="The tax rate visible on the invoice of the store."></i></label>
                                <input id="productTax_placeholder" class="input-text form-control input-numeric" required name="productTax_placeholder" type='text' placeholder="21" onpaste="return false;" ondrop="return false;" autocomplete="off">
                                <div class="invalid-feedback">
                                    Please provide the tax.
                                </div>
                            </div>
                            <div class="col-12 col-lg-4 pl-6 pt-lg-0 mt-lg-0 mb-20">
                                <label class="d-none d-lg-block">9. Check in</label>
                                <button id="add-product" type="submit" class="btn btn-secondary btn-small" style="width:100%; height:45px;" >
                                    Add product
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="modal fade" id="addProducts" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header" style="border:0">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Add product</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <div class="row col-12">
                                        <div class="col-12 container-category">
                                            <label class="input-label">1: Category</label>
                                            <div class="dropdown show">
                                                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuCategories" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <input id="category_placeholder" class="dropdown-placeholder input-text" name="category_placeholder" type="text" placeholder="Choose category" onpaste="return false;" ondrop="return false;" autocomplete="off">
                                                </a>

                                                <div class="dropdown-menu menu-category" aria-labelledby="dropdownMenuCategories">
                                                    <?php

                                                    $i = 1;
                                                    foreach ($viewModel->getCategories() as $_item) {
                                                        echo '<a class="dropdown-item" href="#" name="category_' . $_item['category_id'] . '">' . $_item['category_title'] . "</a>";
                                                        $i++;
                                                    }

                                                    ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12 container-subcategory" style="display: none;">
                                            <label class="input-label">2: Subcategory</label>
                                            <div class="dropdown show">
                                                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuSubCategories" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <input id="subcategory_placeholder" class="dropdown-placeholder input-text" name="subcategory_placeholder" type="text" placeholder="Choose subcategory" onpaste="return false;" ondrop="return false;" autocomplete="off">
                                                </a>

                                                <div class="dropdown-menu menu-subcategory" aria-labelledby="dropdownMenuSubCategories">
                                                    <?php

                                                    $i = 1;
                                                    foreach ($viewModel->getSubCategories() as $_item) {
                                                        echo '<a class="dropdown-item" href="#" name="cat_' . $_item['category_id'] . '_' . $_item['subcategory_id'] . '">' . $_item['subcategory_title'] . "</a>";
                                                        $i++;
                                                    }

                                                    ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12 container-product mb-20" style="display: none;">
                                            <label class="input-label">3: Product</label>
                                            <div class="dropdown show">
                                                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <input id="product_placeholder" class="dropdown-placeholder input-text" name="product_placeholder" type="text" placeholder="Choose product" onpaste="return false;" ondrop="return false;" autocomplete="off">
                                                </a>

                                                <div class="dropdown-menu menu-product" aria-labelledby="dropdownMenuLink">
                                                    <?php

                                                    $i = 1;
                                                    foreach ($viewModel->getProductGroup() as $_item) {
                                                        echo '<a class="dropdown-item" href="#" name="cat_' . $_item['category_id'] . '_' . $_item['subcategory_id'] . '_' . $_item['product_tax_nr'] . '">' . $_item['product_title'] . '</a>';
                                                        $i++;
                                                    }

                                                    ?>
                                                </div>
                                            </div>

                                        </div>


                                    </div>

                                </div>
                                <div class="modal-footer container-action" style="display:none;border:0">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Discard</button>
                                    <button type="button" class="btn btn-primary" data-dismiss="modal" id="add-productCode">Save changes</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <h3 style="
    font-size: 16px;
    font-weight: bold;
">Product check-in list</h3>
                <div class="shown-holder">
                    <?php
                    if($edit) {
                        $i=1;
                        foreach($viewModel->getOrderDetailsWithHs($orderParam) as $orderDetail){ ?>
                            <div class='card p-10 row_" + (countRows+1) +"' style='background:#fafafa;'>
                                <div class='row col-12'>
                                    <div class='col-6'>Brand</div><div class='col-6'><?= $orderDetail['product_brand'];?></div>
                                </div>
                                <div class='row col-12'>
                                    <div class='col-6'>Product</div><div class='col-6'><?= $orderDetail['product_title'];?></div>
                                </div>
                                <div class='row col-12'>
                                    <div class='col-6'>Amount</div><div class='col-6'><?= $orderDetail['product_amount'];?></div>
                                </div>
                                <div class='row col-12'>
                                    <div class='col-6'>Price (net)</div><div class='col-6'>&euro;<?= $orderDetail['product_price_net'];?></div>
                                </div>
                                <div class='row col-12'>
                                    <div class='col-6'>Tax</div><div class='col-6'><?= $orderDetail['product_tax'];?></div>
                                </div>
                                <div class='row col-12 mt-10'>
                                    <div class='col-12'><span onclick="document.getElementById('removeRow_<?= $i;?>').click()" class='btn btn-danger btn-small text-white rounded' style='width:100%;'>Remove</span></div>
                                </div></div>

                            <?php
                            $i++;    }
                    }
                    ?>
                </div>
                <div class="added-products d-none">

                    <div class="block">
                        <div class="table-wrapper">
                            <table class="data table table-order-items history" id="my-orders-table">
                                <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
                                <thead>
                                <tr>
                                    <th scope="col" class="col date"><?= __('Brand') ?></th>
                                    <th scope="col" class="col date"><?= __('Product title') ?></th>
                                    <th scope="col" class="col count"><?= __('products') ?></th>
                                    <th scope="col" class="col webshop"><?= __('Price / product') ?></th>
                                    <th scope="col" class="col amount"><?= __('product Type') ?></th>
                                    <th scope="col" class="col count"><?= __('Tax (%)') ?></th>
                                    <th scope="col" class="col actions"><?= __('Action') ?></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                if($edit) {
                                    $i=1;
                                    foreach($viewModel->getOrderDetailsWithHs($orderParam) as $orderDetail){ ?>
                                        <tr id="row_<?= $i;?>">
                                            <td class="col col-product_brand"><?= $orderDetail['product_brand'] ?></td>
                                            <td class="col col-product_title"><?= $orderDetail['product_title'] ?></td>
                                            <td class="col col-product_amount"><?= $orderDetail['product_amount'] ?></td>
                                            <td class="col col-product_price"><?= $orderDetail['product_price_net'] ?></td>
                                            <td class="col col-product_type"><?= $orderDetail['product_type'] ?></td>
                                            <td class="col col-product_tax"><?= $orderDetail['product_tax'] ?></td>
                                            <td class="col"><a href='#' id="removeRow_<?=$i;?>" class='removeRow btn btn-danger btn-small text-white rounded'>Remove</a></td>
                                        </tr>

                                        <?php
                                        $i++;    }
                                }
                                ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row col-12 mt-40">
                    <form id="appendProduct"
                          class="createOrderForm needs-validation" novalidate
                          method="post"
                          autocomplete="off"
                          enctype="multipart/form-data"
                    >
                        <input id="appendProductBtn" class="btn btn-secondary" type="submit" value="Save & continue" >
                    </form>
                </div>
            </div>
            <div id="results_products"></div>
        </div>

    </form>

</div>

<script>

    require(["jquery", "Eos_Base/js/bootstrap.bundle.min", 'Eos_Base/js/packageDetails', 'Eos_Base/node_modules/bootstrap4-toggle/js/bootstrap4-toggle.min'], function ($) {
        $(".input-numeric").keyup(function() {
            var $this = $(this);
            $this.val($this.val().replace(/[^\d.]/g, ''));
        });


        $('input').attr('autocomplete', 'off');

        $('#addSingleProduct').on("submit" , function(e){
            e.preventDefault();
            e.stopPropagation();

            if (this.checkValidity() !== false) {
                var _brand = $('#brand_placeholder').val();
                var _productTitle = $('#productTitle_placeholder').val();
                var _productCode = $('#productCode_placeholder').val();

                var _productPrice = $('#productPrice_placeholder').val();
                var _productAmount = $('#productAmount_placeholder').val();
                var _productType = $('#productType_placeholder').val();
                var _productTax = $('#productTax_placeholder').val();
                var _typePrice = $(this).find('.card-toggle-active span').text();

                addProducts(_brand,_productTitle,_productCode,_productAmount,_productPrice,_typePrice,_productType,_productTax);

                // Change have taken place, so hide the Edit button on product price
                $('#appendPricing').find('.btn-edit').hide();

                $('#addSingleProduct').trigger("reset");
                setTimeout(() => {$('#addSingleProduct').attr('class',"createOrderForm needs-validation")},1); //timeout allows for 'was-validated' to be added then removed.

                $('#product_placeholder').attr("placeholder", "Product Group");

                var totalOrderLinePrice = 0;
                $('#my-orders-table tbody tr').each(function(){

                   const price = parseInt($(this).find('.col-product_price').text());
                   const amount = parseInt($(this).find('.col-product_amount').text());
                   totalOrderLinePrice = totalOrderLinePrice + (price * amount);

                    if( (price * amount) > 136) {
                        $('#results_price').append('<div class="message info empty"><span>Note! Please be aware that your parcel has exceeded the 1.000 RMB which could lead to custom control.</span></div>')
                    }
                });
                if( totalOrderLinePrice > 136) {
                    $('#results_price').append('<div class="message info empty"><span>Note! Due to customs regulations, we have to split your shipment into two separate parcels.</span></div>')
                }

                $('#add-product').text('Add another product');
            }

        });

        function addProducts(_brand,_productTitle,_productCode,_productAmount,_productPrice,_typePrice,_productType,_productTax) {
           // $('.shown-holder').show();
            $('.container-subcategory').hide();
            $('.container-product').hide();
            $('.container-details').hide();
            $('.container-action').hide();
            $('#category_placeholder').val('');

            var countRows = $(".added-products tbody").children().length;

            $('#product_counter').text(countRows+1);

            $(".added-products tbody").append(
                "<tr id='row_"          + (countRows+1)     + "'>"      +
                "<td class=\"col col-product_brand\">"    + _brand            + "</td>"   +
                "<td class=\"col col-product_title\">"    + _productTitle     + "</td>"   +
                "<td class=\"col col-product_code\" style='display:none;'>"    + _productCode     + "</td>"   +
                "<td class=\"col col-product_amount\">"    + _productAmount       + "</td>"   +
                "<td class=\"col col-product_price\">"    + _productPrice        + "</td>"   +
                "<td class=\"col col-product_type\">"    + _productType         + "</td>"   +
                "<td class=\"col col-product_tax \">"    + _productTax          + "</td>"   +
                "<td class=\"col\"><a href='#' id='removeRow_" + (countRows+1) + "' class='removeRow btn btn-danger btn-small text-white rounded'>Remove</a></td>" +
                "</tr>"
            );
            $(".shown-holder").append(
                "<div class='card p-10 row_" + (countRows+1) +"' style='background:#fafafa;'>" +
                "<div class='row col-12'>"      +
                "   <div class='col-6'>Brand</div><div class='col-6'>"    + _brand            + "</div>"   +
                "</div>" +
                "<div class='row col-12'>"      +
                "   <div class='col-6'>Product</div><div class='col-6'>"    + _productTitle            + "</div>"   +
                "</div>" +
                "<div class='row col-12'>"      +
                "   <div class='col-6'>Amount</div><div class='col-6'>"    + _productAmount            + "</div>"   +
                "</div>" +
                "<div class='row col-12'>"      +
                "   <div class='col-6'>Price</div><div class='col-6'>&euro;"    + parseFloat(_productPrice).toFixed(2)            + "</div>"   +
                "</div>" +
                "<div class='row col-12'>"      +
                "   <div class='col-6'>Tax</div><div class='col-6'>"    + parseFloat(_productTax).toFixed(2)       + "%</div>"   +
                "</div>" +
                "<div class='row col-12 mt-10'>"      +
                "   <div class='col-12'><span onclick=\"document.getElementById('removeRow_"+ (countRows+1) +"').click()\" class='btn btn-danger btn-small text-white rounded' style='width:100%;'>Remove</span></div>" +
                "</div></div>"
            );


            $('.calculate-group-product').append('<div class="row col-12">' +
                '                   <div class="col-5 text-right pr-20 pt-6">\n' +
                '                        <p style="font-size:12px;">' + _productTitle + '</p>\n' +
                '                    </div>\n' +
                '                    <div class="col-7 row">\n' +
                '                        <div class="col-4 pr-6">\n' +
                '                            <input readonly="readonly" id="calculate-product-' + (countRows+1) + '" value="' + (_productAmount * _productPrice).toFixed(2) + '" class="input-text calculate-product" name="product_placeholder" type="number" onpaste="return false;" ondrop="return false;" autocomplete="off" style="height:30px;">\n' +
                '                        </div>\n' +
                '                        <div class="col-4">\n' +
                '                            <div class="card card-toggle card-toggle-left '+ (_typePrice === "Gross" ? "card-toggle-active" : "") + '">\n' +
                '                                <div class="card-header">\n' +
                '                                    <span>Net</span>\n' +
                '                                </div>\n' +
                '                            </div>\n' +
                '                        </div>\n' +
                '                        <div class="col-4">\n' +
                '                            <div class="card card-toggle card-toggle-right '+ (_typePrice === "Net" ? "card-toggle-active" : "") + '">\n' +
                '                                <div class="card-header">\n' +
                '                                    <span>Gross</span>\n' +
                '                                </div>\n' +
                '                            </div>\n' +
                '                        </div>\n' +
                '                    </div>' +
                '                  </div>');

            $('#calculate-table tbody .calculate-discounts').before('<tr class="result-product-' + (countRows+1) + '">\n' +
                '                                <td class="col col-orderDetails-id" style="display:none;"></td>\n' +
                '                                <td class="col">' + _productTitle + '</td>\n' +
                '                                <td class="col col-gross">' + (_typePrice === "Gross" ? (_productPrice * _productAmount) : (_productPrice * _productAmount) / (1 + _productTax / 100)).toFixed(2) + '</td>\n' +
                '                                <td class="col col-net">' + (_typePrice === "Net" ? (_productPrice * _productAmount) : (_productPrice * _productAmount) * (1 + _productTax / 100)).toFixed(2) + '</td>\n' +
                '                            </tr>');
            let netPrice = 0;
            let grossPrice = 0;

            $('#tax_placeholder').val(_productTax);

            $('#calculate-table .col-net').each(function (){
                netPrice = netPrice + parseFloat($(this).text());
                $('.calculate-results-net').text(netPrice.toFixed(2));
            });
            $('#calculate-table .col-gross').each(function (){
                grossPrice = grossPrice + parseFloat($(this).text());
                $('.calculate-results-gross').text(grossPrice.toFixed(2));
            });
        }

        $('#appendProduct').on("submit", function(e){
            e.preventDefault();
            var product = [];
            var general = [];
            general.push({
                'order_id' : $('#hiddenForm input[name="order_id"]').val()
            });


            var c_row = 1;

            $('#my-orders-table tbody tr').each(function() {
                product.push({
                    'product_brand'       : $("#row_" + c_row + " .col-product_brand").text(),
                    'product_title'       : $("#row_" + c_row + " .col-product_title").text(),
                    'product_code'        : $("#row_" + c_row + " .col-product_code").text(),
                    'product_amount'      : $("#row_" + c_row + " .col-product_amount").text(),
                    'product_price_net'   : $(".result-product-" + c_row + " .col-net").text(),
                    'product_price_gross' : $(".result-product-" + c_row + " .col-gross").text(),
                    'product_type'        : $("#row_" + c_row + " .col-product_type").text(),
                    'product_tax'         : $("#row_" + c_row + " .col-product_tax").text()
                });

                c_row++;
            });
            $.post(
                  "<?php echo $block->getBaseUrl() . 'portal/order/appendorderproduct'; ?>",
                { general, product },
                function(data){
                    $("#results_products").html(data);
                      data = $.parseJSON( data );
                     for(let i=0; i<=data.length; i++) {
                          $('#calculate-table tbody .result-product-' + (i + 1)+ ' .col-orderDetails-id').text(data[i]);
                          $("#results_products").html(data[i]);
                      }

                    $('#collapseFour').collapse('toggle');
                    $('.appendProduct-holder').find('.btn-edit').show();
                    $("#results_products").html('');
                }
            );

        });

        $('.menu-category .dropdown-item').on('click', function(e) {
            e.preventDefault();

            // When category selected, then show subcategory input field.
            $('.container-subcategory').show();

            // When customer redo a category selection, reset subcategory & product input fields
            $('.container-product').hide();
            $('#subcategory_placeholder').attr({"value":'',"placeholder": 'Choose subcategory'});
            $('#product_placeholder').attr({"value":'',"placeholder": 'Choose product'});

            // Attribute name = cat_{category id}
            var cat_id = $(this).attr('name').split('_')[1];

            $('.menu-subcategory .dropdown-item').each(function(){
                $(this).show();
                if(cat_id !== $(this).attr('name').split('_')[1]) {
                    $(this).hide();
                }

            });
            $('.menu-product .dropdown-item').each(function(){
                $(this).show();
                if(cat_id !== $(this).attr('name').split('_')[1]) {
                    $(this).hide();
                }

            });
        });

        $('.menu-subcategory .dropdown-item').on('click', function(e) {
            e.preventDefault();

            // When subcategory selected, then show product input field
            $('.container-product').show();

            // Attribute name = cat_{category id}
            var cat_id = $(this).attr('name').split('_')[1];

            // Attribute name = cat_{category id}_{category id}
            var subcat_id = $(this).attr('name').split('_')[2];

            // First show every Product in list, then hide every product that is not in Category or not in Subcategory
            $('.menu-product .dropdown-item').each(function(){
                $(this).show();

                if(cat_id !== $(this).attr('name').split('_')[1] || subcat_id !== $(this).attr('name').split('_')[2]) {
                    $(this).hide();
                }
            });
        });

        $('.menu-product .dropdown-item').on('click', function(e) {
            e.preventDefault();

            // In order to pass the Product Tax Number, placeholder attribute is being used. $(this).attr('name') = 'cat_2_2_2020100' so that is why .split('_')[3] is used.
            $('#product_placeholder').attr("placeholder", $(this).attr('name').split('_')[3]);
            $('.container-action').show();

        });
        $('.menu-product-type .dropdown-item').on('click', function(e) {
            console.log('hello')
            e.preventDefault();
            $('#productType_placeholder').attr("value", $(this).attr('name').split('_')[2]);

        });

        $('#add-productCode').on('click', function() {
            $('#productCode_placeholder').val($('#product_placeholder').attr("placeholder"));
        });
    });
</script>
