<?php
/** @var \Magento\Framework\View\Element\Template $block */
/**@var Eos\Base\ViewModel\Orders $viewModel*/
$viewModel = $block->getData('view_model');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey');

$orderParam = $block->getRequest()->getParam('order');
$edit = $block->getRequest()->getParam('new') < 1;
if((!$block->getRequest()->getParam('new') && !$orderParam) || $block->getRequest()->getParam('new') > 0){
    $edit = false;
}
$order = $orderParam ? $viewModel->getOrder($orderParam) : false;
$openOrders = $viewModel->getOrdersAmount(['open:init', 'open:webshop' , 'open:warehouse', 'open:product'],true);

?>

<div class="card order-step mb-20">
    <form id="appendWebshop"
          class="createOrderForm needs-validation" novalidate
          method="post"
          autocomplete="off"
          enctype="multipart/form-data"
    >

        <input name="form_key" type="hidden" value="<?php echo $FormKey->getFormKey();?>">
        <input name="edit" type="hidden" value="0">
        <div class="card-header">
            <div class="row col-12">
                <div class="col-9">
                    1. Webshop information
                </div>
                <div class="col-3 text-right">
                    <button type="button" class="btn-edit"  <?php
                        if(!$edit || $order['status'] === 'open:init') {
                            echo 'style="display: none;"';
                        }
                        ?>>Edit</button>
                </div>
            </div>

        </div>
        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body p-20">

                <div class="row col-12">
                    <div class="col-12 col-lg-6 pr-lg-6">
                        <label class="input-label" for="validationCustom01">Company name <i class="bi-info-lg" data-toggle="tooltip" data-placement="top" title="The name of the store where you have purchased the products"></i></label>
                        <input class="input-text form-control" id="validationCustom01" name="webshop_title" type="text" placeholder="Example: Amazon" required onpaste="return false;" ondrop="return false;" autocomplete="off" <?= ($edit ? 'value="' . $order['webshop_title'] . '"' : '') ?>>
                        <div class="invalid-feedback">
                            Please provide a company name.
                        </div>
                    </div>
                    <div class="col-12 col-lg-6 pl-lg-6">
                        <label class="input-label" for="validationCustom02">Invoice Number <i class="bi-info-lg" data-toggle="tooltip" data-placement="top" title="When you have purchased products at a store, this is the unique number displayed on the bill or payment receipt."></i></label>
                        <input class="input-text form-control" id="validationCustom02" name="webshop_order_nr" type="text" placeholder="Example: 10001000" required onpaste="return false;" ondrop="return false;" autocomplete="off" <?= ($edit ? 'value="' . $order['webshop_order_nr'] . '"' : '') ?>>
                        <div class="invalid-feedback">
                            Please provide an invoice number.
                        </div>
                    </div>
                </div>
                <div class="row col-12">
                    <div class="col-12 col-lg-6 pr-lg-6">
                        <label class="input-label" for="validationCustom03" >Tracking Number <i class="bi-info-lg" data-toggle="tooltip" data-placement="top" title="The track and trace code received from the store."></i></label>
                        <input class="input-text form-control" id="validationCustom03" name="webshop_tracking_number" type="text" placeholder="Example: 3SMYPA472567104" required onpaste="return false;" ondrop="return false;" autocomplete="off" <?= ($edit ? 'value="' . $order['webshop_tracking_number'] . '"' : '') ?>>
                        <div class="invalid-feedback">
                            Please provide at least one tracking number.
                        </div>
                    </div>
                   <!-- <div class="col-12 col-lg-6 pl-lg-6 dropdown">
                        <label class="input-label" for="currency_placeholder">Used currency</label>
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownCurrency" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <input id="currency_placeholder" class="dropdown-placeholder input-text form-control" name="webshop_currency" type="text" placeholder="Choose..." required onpaste="return false;" ondrop="return false;" autocomplete="off"  <?/*= ($edit ? 'value="' . $order['webshop_currency'] . '"' : '') */?>>
                            <div class="invalid-feedback">
                                Please provide a currency related to the invoice.
                            </div>
                        </a>

                        <div class="dropdown-menu menu-warehouse" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="#" name="webshop_currency_EUR">EUR</a>
                        </div>

                    </div>-->
                    <div class="col-12 col-lg-6 pl-lg-6">
                        <label class="input-label" for="validationCustom04">Invoice date <i class="bi-info-lg" data-toggle="tooltip" data-placement="top" title="The date of purchase from the store. This is visible on the invoice / shipping receipt."></i></label>
                        <input class="input-text form-control datepicker" id="validationCustom04" name="webshop_order_date" type="date" required onpaste="return false;" ondrop="return false;" autocomplete="off" <?= ($edit ? 'value="' . date("d/m/Y", strtotime($order['webshop_order_date'])) . '"' : '') ?> style="padding-right:10px;">
                        <div class="invalid-feedback">
                            Please provide the date of invoice.
                        </div>
                    </div>

                </div>

                <hr style="border-color:#ddd;"/>

                <div class="box mb-40" >
                    <div class="box__input text-center">
                        <input class="box__file" type="file" name="file" id="file"  style="display: none;"/>
                        <label for="file"><span class="btn btn-secondary">Upload here your invoice (PDF only)</span></label>
                    </div>
                    <div id="results_upload" style="text-align: center; font-weight:bold;"></div>
                </div>
                <div class="row col-12">
                    <input id="initOrderBtn" class="btn btn-secondary" type="submit" value="Save & continue" >
                </div>
            </div>
        </div>
    </form>
</div>

<script>

    require(["jquery", "Eos_Base/js/bootstrap.bundle.min", 'Eos_Base/js/packageDetails', 'Eos_Base/node_modules/bootstrap4-toggle/js/bootstrap4-toggle.min'], function ($) {

        $('input').attr('autocomplete', 'off');

        $('.box__file').on("change", function(e) {
            if (this.files && this.files[0]) {
                if (this.files[0]['type'] === 'application/pdf') {
                    $('#results_upload').text(this.files[0]['name'])
                    //$('#initOrderBtn').attr('disabled', false);
                } else {
                    $('#results_upload').text('Please upload a PDF')
                    // $('#initOrderBtn').attr('disabled', true);
                }

            }
        });

        $(document).on("submit",'#appendWebshop', function(e){
            e.preventDefault();

            const formData = new FormData(this);
            formData.append('order_id', $('#hiddenForm input[name="order_id"]').val().toString());
            $.ajax({
                url: "<?php echo $block->getBaseUrl() . 'portal/order/appendorderwebshop'; ?>",
                type: "POST",
                data: formData,
                contentType: false,
                processData:false,
                statusCode: {
                    500: function() {
                        $("#results_upload").html('Please make sure the file is a .pdf');
                    }
                },
                success: function(data)
                {
                    if(data === "0") {
                        $("#results_upload").html('Please make sure the file is a .pdf');
                    } else {
                        $('input[name="order_id"]').val(data);
                        $('#collapseTwo').collapse('show');
                        $('#appendWebshop .btn-edit').show();
                        $("#results_upload").html('');
                    }

                }

            });
        });
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })

        window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                        $("html, body").animate({ scrollTop: 100 }, "slow");
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    });

</script>
