<?php
/** @var \Magento\Framework\View\Element\Template $block */
/**@var Eos\Base\ViewModel\Orders $viewModel*/
$viewModel = $block->getData('view_model');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey');

$orderParam = $block->getRequest()->getParam('order');
$edit = $block->getRequest()->getParam('new') < 1;
if((!$block->getRequest()->getParam('new') && !$orderParam) || $block->getRequest()->getParam('new') > 0){
    $edit = false;
}
$order = $orderParam ? $viewModel->getOrder($orderParam) : false;
$openOrders = $viewModel->getOrdersAmount(['open:init', 'open:webshop' , 'open:warehouse', 'open:product'],true);
?>

<div class="card order-step mb-40">
    <form id="appendPricing"
          class="createOrderForm needs-validation" novalidate
          method="post"
          autocomplete="off"
          enctype="multipart/form-data"
    >

        <div class="card-header">
            <div class="row col-12">
                <div class="col-9">
                    4. Product price
                </div>
                <div class="col-3 text-right">
                    <button type="button" class="btn-edit" <?php
                        echo 'style="display: none;"'; ?>
                    ?>Edit</button>
                </div>
            </div>
        </div>
        <div id="collapseFour" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body p-20">

                <p class="mb-20">The systems visualizes the price corresponding to the invoice at the store. Please manually add additional costs like transportation and discounts so the price on the invoice matches the price in the system.</p>

                <div class="row col-12">
                    <div class="col-12 col-lg-6 row calculate-group calculate-group-product text-center pr-lg-20 mb-20" style="border-right:1px solid #efefef;">
                        <div style="width:100%;text-align:center;">
                            <h3 class="font-size-14 font-weight-bold mb-0">Added products</h3>
                            <hr style="border-color:#efefef;margin:15px 0;" />
                            <?php
                            if($edit &&  $order['status'] !== 'open:init' && $order['status'] !== 'open:webshop' && $order['status'] !== 'open:warehouse') {

                                $i=1;
                                foreach($viewModel->getOrderDetailsWithHs($orderParam) as $orderDetail){
                                    $productTax = $orderDetail['product_tax'];
                                ?>
                                    <div class="row col-12">
                                        <div class="col-4 col-lg-5 text-right pr-20 pt-6">
                                            <p style="font-size:12px;"><?= $orderDetail['product_title'] ?></p>
                                        </div>
                                        <div class="col-8 col-lg-7 row">
                                            <div class="col-4 pr-6">
                                                <input readonly="readonly" id="calculate-product-<?= $i; ?>" value="<?= number_format((float)($orderDetail['product_amount'] * $orderDetail['product_price_net']), 2, '.', ''); ?>" class="input-text calculate-product" name="product_placeholder" type="number" onpaste="return false;" ondrop="return false;" autocomplete="off" style="height:30px;">
                                                </div>
                                            <div class="col-4">
                                                <div class="card card-toggle card-toggle-left  ">
                                                <div class="card-header">
                                                    <span>Net</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-4">
                                                <div class="card card-toggle card-toggle-right card-toggle-active">
                                                <div class="card-header">
                                                    <span>Gross</span>
                                                    </div>
                                                </div>
                                                </div>
                                        </div>
                                    </div>
                                <?php
                                $i++;
                                } ?>

                            <?php } ?>
                        </div>
                    </div>

                    <div class="col-12 col-lg-6 row pl-lg-20">
                        <div style="width:100%;text-align:center;">
                            <h3 class="font-size-14 font-weight-bold mb-0">Additional </h3>
                            <hr style="border-color:#efefef;margin:15px 0;" />
                        </div>
                        <div class="col-12 row">
                            <div class="col-4 col-lg-5 text-right pr-20 pt-6">
                                <p style="font-size:12px;">Overall tax (%)</p>
                            </div>
                            <div class="col-8 col-lg-7 row">
                                <div class="col-4 pr-6">
                                    <input id="tax_placeholder" class="input-text" name="tax_placeholder" type="number" onpaste="return false;" ondrop="return false;" autocomplete="off"
                                        <?php
                                            if($edit && ($order['status'] === 'open:product' || $order['status'] === 'open:pricing' )) {

                                                if($order['webshop_order_discount_price_net']>0) {
                                                    echo 'value="' . (($order['webshop_order_discount_price_net'] - $order['webshop_order_discount_price_gross']) / $order['webshop_order_discount_price_gross'] * 100) . '"';
                                                }
                                                elseif($order['webshop_order_costs_price_net']>0) {
                                                        echo 'value="' . (($order['webshop_order_costs_price_net'] - $order['webshop_order_costs_price_gross']) / $order['webshop_order_costs_price_gross'] * 100) . '"';

                                                } else {
                                                    if(isset($productTax)) {
                                                        echo 'value="' . $productTax . '"';
                                                    }

                                                }
                                            }


                                        ?> style="height:30px;">
                                </div>
                            </div>
                        </div>
                        <div class="col-12 row">
                            <div class="col-12 row calculate-group ">
                                <div class="col-4 col-lg-5 text-right pr-20 pt-6">
                                    <p style="font-size:12px;">Discounts (&euro;)</p>
                                </div>
                                <div class="col-8 col-lg-7 row">
                                    <div class="col-4 pr-6">
                                        <input id="discount_placeholder" class="input-text" name="product_placeholder" type="number" onpaste="return false;" ondrop="return false;" autocomplete="off" placeholder="0,00"
                                            <?php
                                                if($edit && ($order['status'] === 'open:product' || $order['status'] === 'open:pricing' )) {
                                                    if($order['webshop_order_discount_price_net']>0) {
                                                        echo 'value="' . $order['webshop_order_discount_price_gross'] * -1 . '"';
                                                    }
                                                }
                                                ?>
                                               style="height:30px;">
                                    </div>
                                    <div class="col-4">
                                        <div class="card card-toggle card-toggle-left card-toggle-active">
                                            <div class="card-header">
                                                <span>Net</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="card card-toggle card-toggle-right">
                                            <div class="card-header">
                                                <span>Gross</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 row calculate-group">
                                <div class="col-4 col-lg-5 text-right pr-20 pt-6">
                                    <p style="font-size:12px;">Additional costs (&euro;)</p>
                                </div>
                                <div class="col-8 col-lg-7 row">
                                    <div class="col-4 pr-6">
                                        <input id="costs_placeholder" class="input-text" name="costs_placeholder" type="number" onpaste="return false;" ondrop="return false;" autocomplete="off" style="height:30px;" placeholder="0,00"
                                            <?php
                                                if($edit && ($order['status'] === 'open:product' || $order['status'] === 'open:pricing' )) {
                                                    if($order['webshop_order_discount_price_net']>0) {
                                                        echo 'value="' . $order['webshop_order_costs_price_gross'] . '"';
                                                    }
                                                }
                                                ?>
                                        >
                                    </div>
                                    <div class="col-4">
                                        <div class="card card-toggle card-toggle-left card-toggle-active">
                                            <div class="card-header">
                                                <span>Net</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="card card-toggle card-toggle-right">
                                            <div class="card-header">
                                                <span>Gross</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>




                <div class="col-12 row table-wrapper mt-20">
                    <table class="data table table-order-items history" id="calculate-table">
                        <caption class="table-caption"><?= __('Orders') ?></caption>
                        <thead>
                        <tr>
                            <th scope="col" class="col date"></th>
                            <th scope="col" class="col">Net (&euro;)</th>
                            <th scope="col" class="col">Gross (&euro;)</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                            if($edit) {

                                $i=1;
                                foreach($viewModel->getOrderDetailsWithHs($orderParam) as $orderDetail){
                                ?>
                                <tr class="result-product-<?= $i; ?>">
                                    <td class="col col-orderDetails-id" style="display:none;"><?= $orderDetail['orderDetail_id']; ?></td>
                                    <td class="col"><?= $orderDetail['product_title']; ?></td>
                                    <td class="col col-net"><?= number_format((float)($orderDetail['product_amount'] * $orderDetail['product_price_gross']), 2, '.', '');?></td>
                                    <td class="col col-gross"><?= number_format((float)($orderDetail['product_amount'] * $orderDetail['product_price_net']), 2, '.', '');?></td>
                                </tr>

                        <?php
                                    $i++;
                                }
                            }
                            ?>

                        <tr class="calculate-discounts">
                            <td class="col">Discounts</td>
                            <td class="col col-net"><?php if($edit && ($order['status'] === 'open:product' || $order['status'] === 'open:pricing' )) { echo $order['webshop_order_discount_price_gross'];} else { echo '0.00';}  ?></td>
                            <td class="col col-gross"><?php if($edit && ($order['status'] === 'open:product' || $order['status'] === 'open:pricing' )) { echo $order['webshop_order_discount_price_net'];} else { echo '0.00';}  ?></td>
                        </tr>
                        <tr class="calculate-costs">
                            <td class="col">Additional Costs</td>
                            <td class="col col-net"><?php if($edit && ($order['status'] === 'open:product' || $order['status'] === 'open:pricing' )) { echo $order['webshop_order_costs_price_gross'];} else { echo '0.00';}  ?></td>
                            <td class="col col-gross"><?php if($edit && ($order['status'] === 'open:product' || $order['status'] === 'open:pricing' )) { echo $order['webshop_order_costs_price_net'];} else { echo '0.00';}  ?></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-12 row">
                    <div class="col-6 col-lg-3 pr-20 pt-6">
                        <p style="font-size:12px;">Total Net Price</p>
                    </div>
                    <div class="col-6 col-lg-3 row">
                        <h3 class="">&euro;<span class="calculate-results calculate-results-net">0,00</span></h3>
                    </div>
                    <div class="col-6 col-lg-3 pr-20 pt-6">
                        <p style="font-size:12px;">Total Gross Price</p>
                    </div>
                    <div class="col-6 col-lg-3 row">
                        <h3 class="">&euro;<span class="calculate-results calculate-results-gross">0,00</span></h3>
                    </div>
                </div>
                <div class="row col-12">
                    <button id="createOrderBtn" class="btn btn-primary btn-full btn-submit" type="submit">
                        <span class="btn-text">Save & finalize</span>
                    </button>
                    <p class="my-10">By sumbitting, you accept our <a href="<?php echo $this->getUrl('terms-conditions'); ?>">Terms & Conditions</a> and our <a href="<?php echo $this->getUrl('privacy-policy'); ?>">Privacy Policy</a>.</p>
                    <div id="results_price"></div>
                </div>
            </div>

        </div>
    </form>
</div>
<script>

    require(["jquery", "Eos_Base/js/bootstrap.bundle.min", 'Eos_Base/js/packageDetails', 'Eos_Base/node_modules/bootstrap4-toggle/js/bootstrap4-toggle.min'], function ($) {

        $('#appendPricing').on("submit", function(e){
            e.preventDefault();
            var general = [];
            var product = [];
            var totals = [];

            general.push({
                'order_id' : $('#hiddenForm input[name="order_id"]').val()
            });


            var c_row = 1;

            $('#my-orders-table tbody tr').each(function() {
                product.push({
                    'product_brand'       : $("#row_" + c_row + " .col-product_brand").text(),
                    'product_title'       : $("#row_" + c_row + " .col-product_title").text(),
                    'product_code'        : $("#row_" + c_row + " .col-product_code").text(),
                    'product_amount'      : $("#row_" + c_row + " .col-product_amount").text(),
                    'product_price_net'   : $(".result-product-" + c_row + " .col-net").text(),
                    'product_price_gross' : $(".result-product-" + c_row + " .col-gross").text(),
                    'product_type'        : $("#row_" + c_row + " .col-product_type").text(),
                    'product_tax'         : $("#row_" + c_row + " .col-product_tax").text(),
                    'orderDetails_id'     : $(".result-product-" + c_row + " .col-orderDetails-id").text()
                });

                c_row++;
            });
            totals.push({
                'webshop_order_total_price_net'     : $(".calculate-results-net").text(),
                'webshop_order_total_price_gross'   : $('.calculate-results-gross').text(),
                'webshop_order_discount_price_net'  : $('.calculate-discounts .col-net').text(),
                'webshop_order_discount_price_gross': $('.calculate-discounts .col-gross').text(),
                'webshop_order_costs_price_net'     : $('.calculate-costs .col-net').text(),
                'webshop_order_costs_price_gross'   : $('.calculate-costs .col-gross').text()
            });


            $.post(
                "<?php echo $block->getBaseUrl() . 'portal/order/appendorderpricing'; ?>",
                { general, product, totals },
                function(data){
                    if(data === 'done') {
                        window.location.href = "<?php echo $block->getBaseUrl() . 'portal/shipment/create'; ?>";
                    }
                }
            );

        });


        $('.added-products').on('click', '.removeRow', function(e){
            e.preventDefault();

            const rowParent = $(this).closest('tr');
            const rowNumber = $(this).closest('tr').attr('id').split('_')[1];

            $('input[type="hidden"][name$=' + "_" + rowNumber + ']').each( function() {
                $(this).remove();
            });
            rowParent.remove();
            $('.row_' + rowNumber).remove();
            // Change have taken place, so hide the Edit button on product price
            $('#appendPricing').find('.btn-edit').hide();

            $('#calculate-product-' + rowNumber).closest('.col-12').remove();
            $('.result-product-' + rowNumber).remove();
            updateCalculation();

            /*if(!$('input[type="hidden"][name^="counter_"]').attr('value')) {
                $('input.btn-primary[type="submit"]').attr('disabled',true);
            }*/
            $('#product_counter').text(rowNumber-1);
        });



        $(document).on('click', '.calculate-group .card-toggle', function(e) {
            e.preventDefault();
            if(!$(this).hasClass('card-toggle-active')){
                $(this).closest('.row').find('.card-toggle-active').removeClass('card-toggle-active');
                $(this).addClass('card-toggle-active');
                setTimeout(function(){ updateCalculation() }, 200);
            }
        });

        $('.calculate-group input').on("change keyup", function() {
            updateCalculation();
        });

        $('#calculate-table tbody tr td').on('change', function (e) {
            e.preventDefault();
            console.log($('.col-net').text());
        });

        <?php
            if($edit) {
                ?>
        $( document ).ready(function() {
            updateCalculation();
        });
        <?php
            }
        ?>

        function updateCalculation() {
            var i = 0;

            $('.calculate-group input').each(function() {

                if($(this).val() != "") {
                    const typePrice = $(this).closest('.row').find('.card-toggle-active span').text();
                    const tax = ($(this).hasClass('calculate-product') ? parseFloat($('#row_' + $(this).attr('id').split('-')[2] + ' .col-product_tax').text()) : $('#tax_placeholder').val() ) / 100;
                    const grossPrice = (typePrice == 'Gross' ? parseFloat($(this).val()) : parseFloat($(this).val()) / ( 1 + tax) );
                    const netPrice = (typePrice == 'Gross' ? parseFloat($(this).val()) * ( 1 + tax) : parseFloat($(this).val()))


                    if($(this).attr('id') =='discount_placeholder') {
                        $('.calculate-discounts td:nth-child(2)').text((grossPrice * -1).toFixed(2));
                        $('.calculate-discounts td:nth-child(3)').text((netPrice * -1).toFixed(2));
                        i = i - parseFloat($(this).val());
                    } else if ($(this).attr('id') =='costs_placeholder'){
                        $('.calculate-costs td:nth-child(2)').text(grossPrice.toFixed(2));
                        $('.calculate-costs td:nth-child(3)').text(netPrice.toFixed(2));
                        i = i + parseFloat($(this).val());
                    } else {
                        const productId = $(this).attr('id').split('-')[2];
                        console.log(grossPrice);
                        console.log(netPrice);
                        $('.result-product-' + productId + ' td:nth-child(3)').text(grossPrice.toFixed(2));
                        $('.result-product-' + productId + ' td:nth-child(4)').text(netPrice.toFixed(2));
                        i = i + parseFloat($(this).val());
                    }
                }
            });
            let netPrice = 0;
            let grossPrice = 0;

            $('#calculate-table .col-net').each(function (){
                netPrice = netPrice + parseFloat($(this).text());
                $('.calculate-results-net').text(netPrice.toFixed(2));
            });
            $('#calculate-table .col-gross').each(function (){
                grossPrice = grossPrice + parseFloat($(this).text());
                $('.calculate-results-gross').text(grossPrice.toFixed(2));
            });
        }

    });
</script>
