<?php
/** @var \Magento\Framework\View\Element\Template $block */
/**@var Eos\Base\ViewModel\GetProductGroup $viewModel*/
$viewModel = $block->getData('view_model');
$categories = $viewModel->getCategories();
$subcategories = $viewModel->getCategories();

$receiver_countries = $viewModel->getCountries('r');
$sender_countries = $viewModel->getCountries('s');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey');

?>


<div class="row col-12 mb-40 order-steps">
    <div class="col-3 step step-active">
        <p>Create order</p>
    </div>
    <div class="col-3 step">
        <p>Consolidate</p>
    </div>
    <div class="col-3 step">
        <p>Shipping</p>
    </div>
    <div class="col-3 step">
        <p>Review & Payment</p>
    </div>
</div>



<form class="createOrderForm"
      method="post"
      action="<?php echo $block->getBaseUrl() . 'portal/order/save'; ?>"
      autocomplete="off"
>
    <input name="form_key" type="hidden" value="<?php echo $FormKey->getFormKey();?>">
    <input name="senderCountry" type="hidden" />
    <input name="receiverCountry" type="hidden" />
    <input name="webshopCurrency" type="hidden" />

<div class="carousel slide mb-40" data-ride="carousel" data-interval="false" id="carouselExampleSlidesOnly">
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active createOrder-one">

            <div class="block mb-40">
                <div class="block-title"><strong>Country</strong></div>
                <div class="row col-12">
                    <div class="col-12 col-lg-6 pr-6 dropdown show">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <input id="senderCountry_placeholder" class="dropdown-placeholder input-text" name="countrySender_placeholder" type="text" placeholder="Country sender" onpaste="return false;" ondrop="return false;" autocomplete="off">
                        </a>

                        <div class="dropdown-menu menu-senderCountry" aria-labelledby="dropdownMenuLink">
                            <?php
                            foreach ($sender_countries as $_country) {
                                echo '<a class="dropdown-item" href="#" name="country_sender_' . $_country['country_code'] . '">' . $_country['country_title'] . '</a>';
                            }
                            ?>


                        </div>
                    </div>
                    <div class="col-12 col-lg-6 pl-6 dropdown show">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <input id="receiverCountry_placeholder" class="dropdown-placeholder input-text" name="countryReceiver_placeholder" type="text" placeholder="Country receiver" onpaste="return false;" ondrop="return false;" autocomplete="off">
                        </a>

                        <div class="dropdown-menu menu-receiverCountry" aria-labelledby="dropdownMenuLink">
                            <?php
                            foreach ($receiver_countries as $_country) {
                                echo '<a class="dropdown-item" href="#" name="country_sender_' . $_country['country_code'] . '">' . $_country['country_title'] . '</a>';
                            }
                            ?>

                        </div>
                    </div>
                    <div class="col-12 col-lg-6 dropdown show">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <input id="webshopCurrency_placeholder" class="dropdown-placeholder input-text" name="webshop_currency_placeholder" type="text" placeholder="Used currency" onpaste="return false;" ondrop="return false;" autocomplete="off">
                        </a>

                        <div class="dropdown-menu menu-webshopCurrency" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="#" name="webshop_currency_EUR">Euro</a>
                            <a class="dropdown-item" href="#" name="webshop_currency_GBP">GBP</a>
                            <a class="dropdown-item" href="#" name="webshop_currency_HKD">HKD</a>
                            <a class="dropdown-item" href="#" name="webshop_currency_CNY">CNY</a>
                        </div>
                    </div>

                </div>
            </div>

            <div class="block">
                <div class="block-title"><strong>Webshop Information</strong></div>
                <div class="row col-12">
                    <div class="col-12">
                        <input class="input-text" name="webshop_title" type="text" placeholder="Company Name" required onpaste="return false;" ondrop="return false;" autocomplete="off">
                    </div>
                    <div class="col-12">
                        <input class="input-text" name="webshop_order_nr" type="text" placeholder="Invoice Number" required onpaste="return false;" ondrop="return false;" autocomplete="off">
                    </div>
                </div>
                <div class="row col-12">

                    <div class="col-12">
                        <input class="input-text" name="webshop_tracking_number" type="text" placeholder="Tracking Number" required onpaste="return false;" ondrop="return false;" autocomplete="off">
                    </div>

                </div>
            </div>
        </div>
        <div class="carousel-item" style="min-height:600px;">


            <div class="block">
                <div class="block-title"><strong>Add new product</strong> <button type="button" style="float:right;" class="btn btn-tertiary btn-small btn-modal-unbook" data-toggle="modal" data-target="#unbookParcel">
                        I have a HS Code
                    </button></div>

                <div class="row col-12 my-20">
                    <div class="row col-12 dimensions">
                            <div class="col-12 container-category">
                                <div class="dropdown show">
                                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <input id="category_placeholder" class="dropdown-placeholder input-text" name="category_placeholder" type="text" placeholder="Choose category" onpaste="return false;" ondrop="return false;" autocomplete="off">
                                    </a>

                                    <div class="dropdown-menu menu-category" aria-labelledby="dropdownMenuLink">
                                        <?php

                                        $i = 1;
                                        foreach ($viewModel->getCategories() as $_item) {
                                            echo '<a class="dropdown-item" href="#" name="category_' . $_item['category_id'] . '">' . $_item['category_title'] . "</a>";
                                            $i++;
                                        }

                                        ?>
                                    </div>
                                </div>
                            </div>

                        <div class="col-12 container-subcategory">
                            <div class="dropdown show">
                                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <input id="subcategory_placeholder" class="dropdown-placeholder input-text" name="subcategory_placeholder" type="text" placeholder="Choose subcategory" onpaste="return false;" ondrop="return false;" autocomplete="off">
                                </a>

                                <div class="dropdown-menu menu-subcategory" aria-labelledby="dropdownMenuLink">
                                    <?php

                                    $i = 1;
                                    foreach ($viewModel->getSubCategories() as $_item) {
                                        echo '<a class="dropdown-item" href="#" name="cat_' . $_item['category_id'] . '_' . $_item['subcategory_id'] . '">' . $_item['subcategory_title'] . "</a>";
                                        $i++;
                                    }

                                    ?>
                                </div>
                            </div>

                        </div>
                        <div class="col-12 container-product">
                            <div class="dropdown show">
                                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <input id="product_placeholder" class="dropdown-placeholder input-text" name="product_placeholder" type="text" placeholder="Choose product" onpaste="return false;" ondrop="return false;" autocomplete="off">
                                </a>

                                <div class="dropdown-menu  menu-product" aria-labelledby="dropdownMenuLink">
                                    <?php

                                    $i = 1;
                                    foreach ($viewModel->getProductGroup() as $_item) {
                                        echo '<a class="dropdown-item" href="#" name="cat_' . $_item['category_id'] . '_' . $_item['subcategory_id'] . '_' . $_item['product_tax_nr'] . '">' . $_item['product_title'] . '<span class="volume-type" style="display:none">' . $_item['volume_type'] . '</span></a>';
                                        $i++;
                                    }

                                    ?>
                                </div>
                            </div>

                        </div>
                        <div class="row col-12 container-price-amount">
                            <div class="col-4 pr-6 container-price">
                                <input id="brand_placeholder" class="input-text" name="brand_placeholder" type="text" placeholder="brand" onpaste="return false;" ondrop="return false;" autocomplete="off">
                            </div>
                            <div class="col-2 pl-6 pr-6 container-price">
                                <input id="price_placeholder" class="input-text" name="price_placeholder" type="number" placeholder="Price" onpaste="return false;" ondrop="return false;" autocomplete="off">
                            </div>
                            <div class="col-2 pl-6 pr-6 container-price">
                                <input id="count_placeholder" class="input-text" name="count_placeholder" type="number" placeholder="Count" onpaste="return false;" ondrop="return false;" autocomplete="off">
                            </div>
                            <div class="col-4 pl-6">
                                <div class="container-amount" style="width: 100%;">
                                    <div class="row col-12">
                                        <div class="input-group">
                                            <input id="amount_placeholder" type="text" class="form-control input-text" name="amount_placeholder" type="number" placeholder="Amount" aria-label="Amount" aria-describedby="Amount" onpaste="return false;" ondrop="return false;" autocomplete="off">
                                            <div class="input-group-append">
                                                <span class="input-group-text" id="amount_shown"></span>
                                            </div>
                                        </div>


                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>

                    <div class="col-12 container-action">
                        <a href="#0" id="add-product" class="btn btn-primary">Add product</a>
                    </div>
                </div>

            </div>

            <div class="shown-holder added-products">
                <div class="block">
                    <div class="block-title"><strong>Added Products (<span>0</span>)</strong></div>
                    <div class="table-wrapper">
                        <table class="data table table-order-items history" id="my-orders-table">
                            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
                            <thead>
                            <tr>
                                <th scope="col" class="col date"><?= __('Product') ?></th>
                                <th scope="col" class="col date"><?= __('Brand') ?></th>
                                <th scope="col" class="col webshop"><?= __('Price') ?></th>
                                <th scope="col" class="col amount"><?= __('Amount') ?></th>
                                <th scope="col" class="col count"><?= __('Count') ?></th>
                                <th scope="col" class="col actions"><?= __('Action') ?></th>
                            </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <div class="block">
                <div class="block-title"><strong>Create order</strong></div>


                <div class="row col-12 mb-20">
                    <div class="col-6 pr-10 pl-0 form-check">
                        <div class="radio-holder radio-active">
                            <input class="form-check-input" type="radio" name="another-order" value="1" id="add-order" checked>
                            <label for="add-order" >Add another order</label>
                        </div>
                    </div>
                    <div class="col-6  pl-10 form-check">
                        <div class="radio-holder">
                            <input class="form-check-input" type="radio" name="another-order" value="0" id="next-step">
                            <label for="next-step">Go to next step</label>
                        </div>
                    </div>
                </div>
                <div class="hidden-holder"></div>
                <div class="row col-12">
                    <div class="col-12 mb-10 pl-0">
                        <input class="btn btn-primary btn-full" type="submit" value="Submit">
                    </div>
                    <div class="col-12 pl-0">
                        <a class="btn btn-tertiary btn-full" href="<?php echo $block->getBaseUrl() . 'portal/shipment/create'; ?>" disabled>Skip this step</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

    <div class="modal fade" id="unbookParcel" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header" style="border:0">
                    <h5 class="modal-title" id="exampleModalLongTitle">Add product by HS Code</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="col-12">
                        <input id="product_group_placeholder_hs" class="input-text" name="product_group_placeholder_hs" type="text" placeholder="HS Code" onpaste="return false;" ondrop="return false;" autocomplete="off">
                    </div>
                    <div class="row col-12">
                        <div class="col-3 pr-6">
                            <input id="price_placeholder_hs" class="input-text" name="price_placeholder_hs" type="number" placeholder="Price" onpaste="return false;" ondrop="return false;" autocomplete="off">
                        </div>
                        <div class="col-3 pl-6 pr-6">
                            <div class="" style="width: 100%;">
                                <div class="row col-12">
                                    <div class="input-group">
                                        <input id="amount_placeholder_hs" type="text" class="form-control input-text" name="amount_placeholder_hs" type="number" placeholder="Amount" aria-label="Amount" aria-describedby="Amount" onpaste="return false;" ondrop="return false;" autocomplete="off">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-3 pl-6 pr-6">
                            <div class="" style="width: 100%;">
                                <div class="row col-12">
                                    <div class="input-group">
                                        <input id="count_placeholder_hs" type="text" class="form-control input-text" name="count_placeholder_hs" type="number" placeholder="Count" aria-label="Count" aria-describedby="Count" onpaste="return false;" ondrop="return false;" autocomplete="off">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-3 pl-6">

                            <div class="dropdown show">
                                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <input id="volumeType_placeholder_hs" class="dropdown-placeholder input-text" name="volume_type_placeholder_hs" type="text" placeholder="Type" onpaste="return false;" ondrop="return false;" autocomplete="off">
                                </a>

                                <div class="dropdown-menu  menu-volumeType" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" href="#" name=""><span class="volume-type">Pieces</span></a>
                                    <a class="dropdown-item" href="#" name=""><span class="volume-type">Kg</span></a>
                                    <a class="dropdown-item" href="#" name=""><span class="volume-type">Pair</span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer" style="border:0">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal" id="add-product_hs">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</form>

<div class="row col-12">
    <div class="col-6">
        <a href="#carouselExampleSlidesOnly" role="button" data-slide="prev" class="btn btn-secondary btn-previous" style="display: none;">
            <span>Previous</span>
        </a>
    </div>
    <div class="col-6 text-right">
        <a href="#carouselExampleSlidesOnly" role="button" data-slide="next" id="carousel-next-1" class="btn btn-secondary btn-next" style="display:none">
            <span>Next</span>
        </a>
        <a href="#carouselExampleSlidesOnly" role="button" data-slide="next" id="carousel-next-2" class="btn btn-secondary btn-next" style="display:none">
            <span>Next</span>
        </a>
    </div>
</div>


<script>
    require(["jquery" , 'Eos_Base/js/packageDetails'], function ($) {

        $('input').attr('autocomplete','off');

        $('.menu-category .dropdown-item').on('click', function(e) {
            e.preventDefault();

            // When category selected, then show subcategory input field.
            $('.container-subcategory').show();

            // When customer redo a category selection, reset subcategory & product input fields
            $('.container-product').hide();
            $('#subcategory_placeholder').attr({"value":'',"placeholder": 'Choose subcategory'});
            $('#product_placeholder').attr({"value":'',"placeholder": 'Choose product'});

            // Attribute name = cat_{category id}
            var cat_id = $(this).attr('name').split('_')[1];

            $('.menu-subcategory .dropdown-item').each(function(){
                $(this).show();
                if(cat_id !== $(this).attr('name').split('_')[1]) {
                    $(this).hide();
                }

            });
            $('.menu-product .dropdown-item').each(function(){
                $(this).show();
                if(cat_id !== $(this).attr('name').split('_')[1]) {
                    $(this).hide();
                }

            });
        });

        $('.menu-subcategory .dropdown-item').on('click', function(e) {
            e.preventDefault();

            // When subcategory selected, then show product input field
            $('.container-product').show();

            // Attribute name = cat_{category id}
            var cat_id = $(this).attr('name').split('_')[1];

            // Attribute name = cat_{category id}_{category id}
            var subcat_id = $(this).attr('name').split('_')[2];

            // First show every Product in list, then hide every product that is not in Category or not in Subcategory
            $('.menu-product .dropdown-item').each(function(){
                $(this).show();

                if(cat_id !== $(this).attr('name').split('_')[1] || subcat_id !== $(this).attr('name').split('_')[2]) {
                    $(this).hide();
                }

            });
        });

        $('.menu-product .dropdown-item').on('click', function(e) {
            e.preventDefault();

            // In order to pass the Product Tax Number, placeholder attribute is being used. $(this).attr('name') = 'cat_2_2_2020100' so that is why .split('_')[3] is used.
            $('#product_placeholder').attr("placeholder", $(this).attr('name').split('_')[3]);

            // each $('.dropdown-item') has a hidden span with the related Volume type (i.e. ml, kg, etc) included
            var volumeType = $(this).find('.volume-type').text();
            $('#amount_shown').text(volumeType);

            $('.container-amount').show();
            $('.container-price').show();
            $('.container-action').show();
        });

        $('.createOrder-one input').on('change keyup click', function(e) {

            const inputArray = [
                $('.input-text[name="countrySender_placeholder"').val(),
                $('.input-text[name="countryReceiver_placeholder"').val(),
                $('.input-text[name="webshop_title"').val(),
                $('.input-text[name="webshop_order_nr"').val(),
                $('.input-text[name="webshop_tracking_number"').val(),
                $('.input-text[name="webshop_currency_placeholder"').val()
            ];

            const selector = $('#carousel-next-1');
            //console.log(inputArray);
            validateForm(inputArray,selector);

        })

        function validateForm(inputArray,selector) {

            let empty = false;

            for (let i = 0; i < inputArray.length; ++i) {
                if(!inputArray[i]) {
                    empty = true;
                }
            }
            if (!empty) {
                selector.show();


            }

        }

        $('.btn-next').on('click', function() {
            $(this).hide()
        });

        $('.btn-previous').on('click', function() {
            if($('.shown-holder .block-title span').text() !== '0') {
                $('#carousel-next-2').show()
                $('#carousel-next-1').hide()
            }
        })


      /*  $('#carouselExampleSlidesOnly').carousel({
            keyboard: false,
            pause:true,
            interval: false
        })*/

        $('.carousel').on('slid.bs.carousel', function () {
                if ($('.carousel-item:first').hasClass('active')) {
                    $('.btn-previous').hide();
                    // $('#carousel-next-1').show();
                    if($('.shown-holder .block-title span').text() !== '0') {
                        $('#carousel-next-2').show()

                    }else{
                        $('#carousel-next-1').show();
                    }
                } else {
                    $('.btn-previous').show();
                    if($('.shown-holder .block-title span').text() !== '0') {
                        $('#carousel-next-2').show()

                    }
                }
               if ($('.carousel-item:last').hasClass('active')) {
                    $('.btn-next').hide();
                }
        });

    });


</script>
