<?php
/** @var \Magento\Framework\View\Element\Template $block */
/**@var Eos\Base\ViewModel\Orders $viewModel*/
$viewModel = $block->getData('view_model');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey');

$orderParam = $block->getRequest()->getParam('order');
$edit = $block->getRequest()->getParam('new') < 1;
if((!$block->getRequest()->getParam('new') && !$orderParam) || $block->getRequest()->getParam('new') > 0){
    $edit = false;
}
$order = $orderParam ? $viewModel->getOrder($orderParam) : false;
$openOrders = $viewModel->getOrdersAmount(['open:init', 'open:webshop' , 'open:warehouse', 'open:product'],true);

?>

<form id="hiddenForm">
    <input name="form_key" type="hidden" value="<?php echo $FormKey->getFormKey();?>">
    <input name="order_id" type="hidden" value="<?= $orderParam ? $order['entity_id'] : '' ?>" />
</form>
