<?php
/** @var \Magento\Framework\View\Element\Template $block */
$viewModel = $block->getData('order_view_model');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey');

$orderParam = $block->getRequest()->getParam('order');
$edit = $block->getRequest()->getParam('new') < 1;
if((!$block->getRequest()->getParam('new') && !$orderParam) || $block->getRequest()->getParam('new') > 0){
    $edit = false;
}

$orderId = $viewModel->getOrders()
                           ->filterById($orderParam)
                           ->getFirstItem()
                           ->getId();

?>

<form id="hiddenForm">
    <input name="form_key" type="hidden" value="<?php echo $FormKey->getFormKey();?>">
    <input name="order_id" type="hidden" value="<?= $orderParam ? $orderId : '' ?>" />
</form>
