<?php
/** @var \Magento\Framework\View\Element\Template $block */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$stepActive = 1;
$search_results =$block->getRequest()->getOriginalPathInfo();

switch (true) {
    case preg_match('/^\/portal\/order\/create\.*/i',$search_results):
        $stepActive = 1;
        break;
    case preg_match('/^\/portal\/shipment\/create\.*/i',$search_results):
        $stepActive = 2;
        break;
    case preg_match('/^\/portal\/uploadid\/create\.*/i',$search_results):
        $stepActive = 3;
        break;
    case preg_match('/^\/portal\/shipment\/review\.*/i',$search_results):
        $stepActive = 4;
        break;
}
?>


<div class="row col-flex mb-40 order-steps">
    <div class="col step step-active">
        <p><span class="svg-holder"></span>Upload parcel info.</p>
    </div>
    <div class="col step <?= ($stepActive >= 2 ? 'step-active' : ''); ?>">
        <p><span class="svg-holder"></span>Create shipment</p>
    </div>
    <div class="col step <?= ($stepActive >= 3 ? 'step-active' : ''); ?>">
        <p><span class="svg-holder"></span>Upload ID card</p>
    </div>
    <div class="col step <?= ($stepActive >= 4 ? 'step-active' : ''); ?>">
        <p><span class="svg-holder"></span>Send shipment</p>
    </div>
</div>

<style>



    .order-steps .step:nth-child(1) .svg-holder {
        -webkit-mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/menu-icons/upload-parcel.svg"); ?>) no-repeat;
        mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/menu-icons/upload-parcel.svg"); ?>) no-repeat;
        -webkit-mask-size: cover;
        mask-size: cover;
    }
    .order-steps .step:nth-child(2) .svg-holder {
        -webkit-mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/menu-icons/create-shipment.svg"); ?>) no-repeat;
        mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/menu-icons/create-shipment.svg"); ?>) no-repeat;
        -webkit-mask-size: cover;
        mask-size: cover;
    }
    .order-steps .step:nth-child(3) .svg-holder {
        -webkit-mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/menu-icons/upload-id-card.svg"); ?>) no-repeat;
        mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/menu-icons/upload-id-card.svg"); ?>) no-repeat;
        -webkit-mask-size: cover;
        mask-size: cover;
    }
    .order-steps .step:nth-child(4) .svg-holder {
        -webkit-mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/menu-icons/confirm-send-shipment.svg"); ?>) no-repeat;
        mask: url(<?php echo $this->getViewFileUrl("Eos_Base::images/menu-icons/confirm-send-shipment.svg"); ?>) no-repeat;
        -webkit-mask-size: cover;
        mask-size: cover;
    }

</style>
